1PasswordHelper unlock handing improvements
- add --password option
- unlock using credential store value or password option

diff --git a/1PasswordHelper b/1PasswordHelper
--- a/1PasswordHelper
+++ b/1PasswordHelper
@@ -4,12 +4,16 @@
 usage() 
 {
 	ScriptUsage "$1" "\
-Usage: $(ScriptName) [OPTION]... [close|environment|IsInstalled|IsRunning|IsSignedin|program|restart|signin|start|startup|status](start)
+Usage: $(ScriptName) [OPTION]... [close|environment|IsInstalled|IsRunning|IsUnlocked|program|restart|start|startup|status|unlock](start)
 $(ScriptName) commands."
 }
 
 init()
 {
+	configDir="$HOME/.config/op"
+	sessionRefreshFile="$configDir/session_refreshed"
+	credentialPath="1Password"
+
 	case "$PLATFORM" in
 		mac) program="TBD";;
 		win) program="$UADATA/1Password/app/8/1Password.exe";;
@@ -23,48 +27,83 @@ closeCommand() { ! isRunningCommand && return 0; ProcessClose "$program"; }
 environmentCommand() { initSession && ScriptReturn --export OP_SESSION_my; }
 isInstalledCommand() { [[ -e "$program" ]]; }
 isRunningCommand() { IsTaskRunning "$(GetFileName "$program")"; }
-isSignedinCommand() {	[[ $OP_SESSION_my ]]; }
+isUnlockedCommand() {	[[ $OP_SESSION_my && -f "$sessionRefreshFile" && -f "$(find "$sessionRefreshFile" -mmin -29)" ]]; }
 programCommand() { echo "$program"; }
 restartCommand() { closeCommand && startCommand; }
-statusCommand() { isSignedinCommand && echo "signed in" || echo "not signed in"; }
+statusCommand() { isUnlockedCommand && echo "signed in" || echo "not signed in"; }
 startArgs() { startArgs=( "$@" ); shift="$#"; }
 startCommand() { isInstalledCommand && start $wait "$program" "${startArgs[@]}"; }
 startupCommand() { startCommand; }
 
-signinCommand()
-{	
-	[[ ! $force ]] && isSignedinCommand && return
+#
+# unlock command
+#
 
-	# validate we can get the password from the a user
-	if ! IsStdIn; then
+unlockArgStart() { unset -v password; }
+unlockUsage() { echot "Usage: $(ScriptName) unlock [PASSWORD]\nUnlock 1Password."; }
+unlockArgs() { [[ ! $1 ]] && return; ScriptArgGet "password" -- "$@"; }
+
+unlockCommand()
+{	
+	[[ ! $force ]] && isUnlockedCommand && return
+
+	# arguments
+	local args=(--cache); [[ $session ]] && args+=(--session "$OP_SESSION_my")
+
+	# get login information if there is no account configured yet
+	if [[ ! -f "$configDir/config" ]]; then
+		local url; url="$(credGet url)" || return
+		local email; email="$(credGet email)" || return
+		local key; key="$(credGet SecretKey)" || return
+		local session="$(getSession)"
+		args+=("$url" "$email" "$key")
+	fi
+
+	# password
+	if [[ ! $password ]] && credExists "password"; then
+		password="$(credGet "password")" || return
+	elif [[ ! $password && ! $noPrompt ]] && IsStdIn; then
+		echo hi
+		ask password "Enter your 1Password account password" || return
+	else
 		[[ ! $quiet ]] && ScriptErr "a terminal is required to read the password."
 		return 1
 	fi
 
-	# get login information
-	local url; url="$(credGet url)" || return
-	local email; email="$(credGet email)" || return
-	local key; key="$(credGet SecretKey)" || return
-	local session="$(getSession)"
-	local args=(); [[ $session ]] && args+=(--session "$OP_SESSION_my")
-
 	# signin
 	unset OP_SESSION_my
-	eval "$(op signin "$url" "$email" "$key" --cache "${args[@]}")" || return
-	[[ ! $OP_SESSION_my ]] && return 1
 
-	# save and return the new session
-	credSet "session" "$OP_SESSION_my" || return
-	ScriptReturn --export OP_SESSION_my
+	local script="$(cat <<-EOF
+		spawn op signin ${args[@]}
+		expect "Enter the password for"
+		send "$password\n";
+		expect "output the session token.\n"
+		EOF
+	)"
+
+	# with a carriage return, macOS completely butchers the value when saved then restore in the macOS credential store
+	eval "$(expect -c "$script" |& grep "^export" | RemoveCarriageReturn)" || return
+
+	# login failed if the session variable was not set
+	if [[ $OP_SESSION_my ]]; then
+		[[ ! $quiet ]] && EchoErr "successfully unlocked your 1Password account"
+	else
+		[[ ! $quiet ]] && ScriptErr "unable to unlock your 1Password account"
+		return 1
+	fi
+
+	# save and return
+	log1 "OP_SESSION_my=$OP_SESSION_my"
+	credSet "session" "$OP_SESSION_my" && touch "$sessionRefreshFile" && ScriptReturn --export OP_SESSION_my
 }
 
 #
 # helper
 #
 
-credExists() { credential 1Password exists "$1" --fallback --exclude-managers=op "${globalArgs[@]}"; }
-credGet() { credential gets 1Password "$1" --fallback --exclude-managers=op "${globalArgs[@]}"; }
-credSet() { credential set 1Password "$1" "$2" --fallback --exclude-managers=op "${globalArgs[@]}" > /dev/null; }
+credExists() { credential "$credentialPath" exists "$1" --fallback --exclude-managers=op "${globalArgs[@]}"; }
+credGet() { credential gets "$credentialPath" "$1" --fallback --exclude-managers=op "${globalArgs[@]}"; }
+credSet() { credential set "$credentialPath" "$1" "$2" --fallback --exclude-managers=op "${globalArgs[@]}" > /dev/null; }
 
 getSession()
 {
