improve TTY handling
- ask password: output message to the TTY if stderr is not available
- BashRun: do not run interactively if stdout is not connected
- bkm: cleanup and improve interactive test
- function.sh
  - add IsTtyOk to check if /dev/tty is usable
  - CurrentColumn: do not define unless /dev/tty is usable (IsTtyOk)
  - PasswordGet: do not ask for password if cannot read or write to the /dev/tty (IsTtyOk)
- SshHelper connect
  - improve usage and comments
  - only use a pseudo terminal of stdout is available

diff --git a/bkm b/bkm
--- a/bkm
+++ b/bkm
@@ -1,94 +1,107 @@
 #!/usr/bin/env bash
-. function.sh
-
-run()
-{
-	init $*
-	local c=${1}
-	[[ "$c" != "SetVars" ]] && echot "--- $c Test ---"
-	${c}Command ${@:2}
-	result="$?"
-	exit $result
-}
-
-init()
-{
-	{ [[ $# == 0 ]] || ! IsFunction ${1}Command; } && usage
-}
+. script.sh || exit
 
 usage()
 {
-	echot 'usage: bkm bash|echo|interactive|return|arg|SetVars'
+	ScriptUsage "$1" "\
+Usage: $(ScriptName) [OPTION]... bash|echo|interactive|return|arg|SetVars
+$(ScriptName) commands."
 	exit
 }
 
-SetVarsCommand()
+setvarsUsage() { ScriptUsageEcho "Usage: $(ScriptName) SetVars\nTest setting variables."; }
+
+setvarsCommand()
 {
-	# eval $(bkm SetVars); printf "a=%s\nb=%s\n" "$a" "$b"
+	header "Set Vars"
+	#eval $(bkm SetVars); printf "a=%s\nb=%s\n" "$a" "$b" # hangs
 	printf "a=%q;b=%q;" "result a" "result b"
 }
 
+bashUsage() { ScriptUsageEcho "Usage: $(ScriptName) bash\nShow Bash configuration."; }
+
 bashCommand()
 {
+	header "Bash"
 	echot "\
 BASH_DEBUG=$BASH_DEBUG
 BASH_STATUS_LOGIN_SHELL=$BASH_STATUS_LOGIN_SHELL
 BASH_STATUS_LOGIN_SHELL_CHILD=$BASH_STATUS_LOGIN_SHELL_CHILD
 BASH_STATUS_INTERACTIVE_SHELL=$BASH_STATUS_INTERACTIVE_SHELL"
-	ShowInteractive
-	ShowSsh
+	IsInteractiveShell
 	declare -p | grep BASH_STATUS
 	[[ "$(export -f)" != "" ]] && ( echo -n "first export function: "; export -f | head -1 ) || echo "No export functions"
+
 	# return 1 so script pauses if run from terminal
 	return 1
 }
 
+openUsage() { ScriptUsageEcho "Usage: $(ScriptName) open\nTest open command."; }
+
 openCommand()
 {
-	echo 'Open a document...'
-	start "$HOME\Dropbox\Current.docx"
+	header "Open"
+	start "$DATA/setup/Set Options ${PLATFORM_OS^}.docm"
 }
+
+interactiveUsage() { ScriptUsageEcho "Usage: $(ScriptName) interactive\nShow interactivity level of the script."; }
 
 # interactive - show level of interactivity of the script
 interactiveCommand()
 {
+	header "Interactive"
 	IsInteractiveShell && printf "SHELL_INTERACTIVE " # true if the script is sourced with "source" or "."
+	IsTty && printf "TTY "
+	IsTtyOk && printf "TTY_OK " # true if can use /dev/tty
 	IsSsh && printf "SSH "
 	IsSshTty && printf "SSH_TTY "
 	IsStdIn && printf "STDIN "
 	IsStdOut && printf "STDOUT "
-	IsStdErr && printf "STDERR "
-	IsTty && printf "TTY "
+	IsStdErr && printf "STDERR "	
 	[[ $TERM ]] && printf "TERM=$TERM "
 	[[ $USER ]] && printf "USER=$USER "
+
 	echo "PARENTS=\"$(ProcessParents)\""
 }
 
+returnUsage() { ScriptUsageEcho "Usage: $(ScriptName) return\nTest return command."; }
+
 returnCommand()
 {
-	ReturnTestHelper "fail"; echot "ReturnTest fail=$?";
-	ReturnTestHelper "success"; echot "ReturnTest success=$?";
+	header "Return"
+	returnTestHelper "fail"; echot "ReturnTest fail=$?";
+	returnTestHelper "success"; echot "ReturnTest success=$?";
 }
 
-ReturnTestHelper()
+returnTestHelper()
 {
 	[[ "$1" != "fail" ]]; result="$?"
 	return $result
 	echo 'not reached'
 }
 
-argCommand()
+argUsage() { ScriptUsageEcho "Usage: $(ScriptName) arg\nTest script arguments."; }
+
+argArgs()
 {
+	header "Args"
 	i=0
 	for arg in ${1:+"$@"}
 	do
 		((i++))
 		echo "arg$i=$arg"
 	done
+
+	(( shift+=$# ))
 }
+
+argCommand() { :; }
+
+echoUsage() { ScriptUsageEcho "Usage: $(ScriptName) echo\nTest echo command."; }
 
 echoCommand()
 {
+	header "Echo"
 	echo "\
 Double quotes: allow expansion
 - variables can be referenced: BIN=$BIN
@@ -117,4 +130,4 @@ Double quotes: allow expansion
 	echot "$s"
 }
 
-run $*
+ScriptRun "$@"
