bootstrap: improvements
- binDir: add additional directories
- initVariables: ensure get defaultDomain

diff --git a/bootstrap-remote b/bootstrap-remote
--- a/bootstrap-remote
+++ b/bootstrap-remote
@@ -116,20 +116,68 @@ bootstrapChroot()
 	bootstrapRun || return
 }
 
-# runCloud - bootstrap a remote host using a cloud service
+# bootstrapCloud - bootstrap a remote host using a cloud service
 bootstrapCloud()
 {
 	CloudConf || return
 	local dir="$CLOUD/data/download"
 	local exclude=('.git/*' '*.*_sync.txt')
 
-	# copy files
-	( cd "$bin" && rm -f "$dir/pbin.zip" && zip "$dir/pbin.zip" . -r --exclude "${exclude[@]}"; ) || return
-	( cd "$ubin" && rm -f "$dir/ubin.zip" && zip "$dir/ubin.zip" . -r --exclude "${exclude[@]}"; ) || return
+	# bin
+	hilight "Compressing bin folder..."
+	( cd "$BIN" && rm -f "$dir/SyncBin.zip" && zip "$dir/SyncBin.zip" . -r --exclude "${exclude[@]}"; ) || return
+
+	# user bin
+	hilight "Compressing user bin folder..."
+	( cd "$UBIN" && rm -f "$dir/SyncUserBin.zip" && zip "$dir/SyncUserbin.zip" . -r --exclude "${exclude[@]}"; ) || return
+
+	# user profile
+	hilight "Compressing user profile folder..."
+	( cd "$UDATA/profile/default" && rm -f "$dir/SyncUserProfile.zip" && zip "$dir/SyncUserProfile.zip" . -r --exclude "${exclude[@]}"; ) || return
+
+	# user SSH
+	hilight "Compressing user SSH folder..."
+	( cd "$HOME/.ssh" && rm -f "$dir/SyncUserSsh.zip" && zip "$dir/SyncUserSsh.zip" . -r --exclude "${exclude[@]}"; ) || return
+
+	# setup
+	hilight "Compressing setup folder..."
+	( cd "$DATA/setup" && rm -f "$dir/SyncSetup.zip" && zip "$dir/SyncSetup.zip" . -r --exclude "${exclude[@]}"; ) || return
+	
+	# platform
+	bootstrapCloudPlatform || return
+
+	# other
 	cp "$BIN/bootstrap-init" "$BIN/bootstrap-config.sh" "$dir" || return
 
 	# help
 	echo -e "\nOn the new system run './bootstrap-init' from the cloud data/download directory"
+}
+
+bootstrapCloudPlatform()
+{
+	# return if compressed platform archive exists as it does not change as much
+	[[ -f "$dir/SyncPlatform.zip" && ! $force ]] && return
+
+	# compress platform folder
+	hilight "Compressing platform folder..."
+	(
+		# copy platform directory
+		cd "$DATA" || return
+		rm -f "$dir/SyncPlatform.zip" || return
+		cp -rpL platform platform.bak || return
+
+		# cleanup win directory
+		cd "platform.bak/win" || return
+		eval eval rm -f "$(SyncLocalFiles exclude all)" || return
+
+		# compress platform directory
+		cd "$DATA/platform.bak" || return
+		zip "$dir/SyncPlatform.zip" . -r --exclude "${exclude[@]}"
+
+		# cleanup
+		cd "$DATA" || return
+		rm -fr "platform.bak" || return
+	) || return
 }
 
 # bootstrapSsh - bootstrap a remote host using SSH
