update for Raspberry Pi flashing

diff --git a/bootstrap-init b/bootstrap-init
--- a/bootstrap-init
+++ b/bootstrap-init
@@ -23,7 +23,7 @@ configureProxyServer()
 	[[ ! $HTTP_PROXY ]] && export {HTTP_PROXY,HTTPS_PROXY}="$proxy"
 
 	if [[ -d /etc/apt/apt.conf.d && ! -f "/etc/apt/apt.conf.d/proxy" ]]; then
-		header "Setting proxy server to $proxy"
+		hilight "Setting proxy server to $proxy..."
 		printf 'Acquire::http::Proxy "%s";\nAcquire::https::Proxy "%s";\n' "$proxy" "$proxy" | $sudo tee "/etc/apt/apt.conf.d/proxy"
 	fi
 
@@ -46,7 +46,7 @@ createUser()
 {
 	IsMac || [[ ! $user ]] || grep "$user" /etc/passwd >& /dev/null && return
 
-	header "Creating user $user"
+	hilight "Creating user $user"
 	sudo adduser "$user" --gecos "" || return
 	sudo usermod -aG sudo $user || return
 }
@@ -58,7 +58,7 @@ createUserHome()
 	local dir="$(grep "$user" /etc/passwd | cut -d: -f 6)"
 	[[ -d "$dir" ]] && return
 
-	header "Creating user $user home directory"
+	hilight "Creating user $user home directory..."
 	sudo mkhomedir_helper $user || return
 }
 
@@ -66,11 +66,11 @@ runAsUser()
 {
 	[[ $user && "$USER" == "$user" ]] && return
 
-	[[ $restart ]] && { header "Restarting to run as $user"; return 100; }
+	[[ $restart ]] && { hilight "Restarting to run as $user..."; return 100; }
 	
 	local script="${BASH_SOURCE[0]}"
 
-	header "Running $script as $user"
+	hilight "Running $script as $user..."
 	cd /tmp || return
 	sudo chmod ugo+rwx "$script" || return
 	sudo --preserve-env --user=$user --set-home "$script" # preserve entire environment so wslpath works properly and WSL_ environment variables are passed
@@ -79,16 +79,25 @@ runAsUser()
 
 runBootstrap()
 {
-	header "Bootstraping from $host"
+	hilight "Bootstraping from $host..."
 	export PATH=$bin:$PATH
 	$bash bootstrap "$host" "$install"
 }
 
 doReboot()
 {
-	header "Rebooting"
-	IsWin && wsl.exe --shutdown || $sudo reboot now
-	exit 100
+	hilight "Rebooting..."
+
+	IsWin && { sync; wsl.exe --shutdown; exit 100; }
+
+	# cache sudo credentials
+	[[ $sudo ]] && $sudo -v 
+
+	# reboot with a delay to allow exit
+	{ nohup bash -c "sleep 1; sudo reboot now" & } >& /dev/null
+
+	# status 100 indicates a retry to bootstrap-init
+	exit 100 
 }
 
 #
@@ -98,7 +107,8 @@ doReboot()
 configureOs() 
 {
 	! UpdateNeeded "os" && return
-	header "Configuring the operating system"
+
+	hilight "Configuring the operating system..."
 	configure-$platform || return
 	UpdateDone "os" || return
 }
@@ -112,7 +122,7 @@ configure-entware()
 		echo "jjbutare ALL=(ALL) ALL" > /usr/etc/sudoers.d/jjbutare || return
 	fi
 	
-	header "Change shell to /opt/bin/bash for all shells with /share/homes home directory"
+	hilight "Change shell to /opt/bin/bash for all shells with /share/homes home directory..."
 	nano "/etc/passwd"  || return
 	pause
 }
@@ -141,7 +151,7 @@ init()
 	. "${BASH_SOURCE[0]%/*}/bootstrap-config.sh" || return
 
 	# variables
-	RB_BLUE=$(printf '\033[38;5;021m') RB_INDIGO=$(printf '\033[38;5;093m') RESET=$(printf '\033[m')
+	GREEN=$(printf '\033[32m') RESET=$(printf '\033[m')
 
 	# arguments
 	[[ "$1" == "--force" ]] && { force="true"; shift; }
@@ -202,7 +212,7 @@ mountPublic()
 
 	IsWin && IsMountedDrive && { mountWinDrive "$host" || return; }
 
-	header "Mounting //$host/public"
+	hilight "Mounting //$host/public..."
 	mkdir -p "$mount" || return
 
 	if [[ "$platform_kernel" == "wsl1" ]]; then mountPublic-win
@@ -236,7 +246,8 @@ mountWinDrive() # dir - mounted directory for the drive, must start with /mnt, i
 installPackages()
 {
 	! UpdateNeeded "packages" && return
-	header "Installing packages"
+
+	hilight "Installing packages..."
 	installPackages-pre || return
 	installPackages-$platform || return
 	installPackages-post || return
@@ -296,7 +307,8 @@ packageInstalled() # return 0 if all passed packages are installed
 setupPackageManager()
 {
 	! UpdateNeeded "PackageManager" && return
-	header "Setting up the package manager"
+
+	hilight "Setting up the package manager..."
 	setupPackageManager-$platform || return
 	UpdateDone "PackageManager" || return
 }
@@ -327,7 +339,7 @@ debianPackageCore()
 
 debianPackageUpdate()
 {
-	header "Updating packages"
+	hilight "Updating packages..."
 	$sudo apt update -y || return
 	$sudo apt dist-upgrade -y || return
 	$sudo apt autoremove -y || return
@@ -344,7 +356,7 @@ debianUnminimizeDoc() # from /usr/local/sbin/unminimize
 	[[ ! -f "$config" && ! -f "$configTmp" && ! -f "$motd" ]] && return
 	[[ -f "$config" ]] && { $sudo mv "$config" "$configTmp" || return; }
 
-	header "Restoring documentation"
+	hilight "Restoring documentation..."
   $sudo apt-get update || return
   $sudo apt-get upgrade -y || return
   dpkg -S /usr/share/man/ |sed 's|, |\n|g;s|: [^:]*$||' | DEBIAN_FRONTEND=noninteractive xargs $sudo apt-get install --reinstall -y || return
@@ -382,7 +394,7 @@ IsQnap() { [[ "$platform_like" == "qnap" ]]; }
 
 GetDateStamp() { ${G}date '+%Y%m%d'; }
 GetFileDateStamp() { ${G}date '+%Y%m%d' -d "$(${G}stat --format="%y" "$1")"; }
-header() { printf "${RB_BLUE}$1...${RESET}\n"; }
+hilight() { printf "${GREEN}$1${RESET}\n"; }
 InPath () { which "$1" &> /dev/null; }
 IsMountedDrive() { [[ -d "$host/public" ]] || [[ "$host" =~ ^/mnt ]]; }
 pause() { local response; read -n 1 -s -p "${*-Press any key when ready...}"; echo; }
diff --git a/drive b/drive
--- a/drive
+++ b/drive
@@ -20,9 +20,9 @@ usage: drive COMMAND(detail)
 	DEVICE 	the drive device name to mount.  Ex: sdb1, d (Windows), or all (all available drives)
 	DIR			a directeory in the mounted drive
 
-	IsMounted|mount|unmount DEVICE
+	IsMounted|mount|unmount|remount DEVICE
 		IsMounted				if the specified device is mounted return the directory it is mounted to
-		mount|unmount		mount or unmount the specified device and return the directory it is mounted to
+		mount						mount the specified device and return the directory it is mounted to
 
 	device|fs|format|IsDrive|IsWin|label|resize|SetLabel|size|type DEVICE|DIR
 		device					get the device name of the drive
@@ -40,7 +40,6 @@ usage: drive COMMAND(detail)
 	win exists|GetOffline|list|online|offline - windows drives
 		use \`wsl mount\` to mount a windows drive in WSL
 
-	-ie,	--ignore-errors	ignore errors when operating on all drives
 	-q, 	--quiet					hide status messages
 	-v, 	--verbose				show verbose output"
 	exit ${1:-1}
@@ -48,12 +47,11 @@ usage: drive COMMAND(detail)
 
 args()
 {
-	unset -v all command device ignoreErrors quiet verbose
+	unset -v all command device quiet verbose
 
 	while (( $# != 0 )); do
 		case "$1" in
 			-h|--help) usage 0;;
-			-ie|--ignore-errors) ignoreErrors="true";;
 			-q|--quiet) quiet="--quiet";;
 			-v|--verbose) verbose="--verbose";;
 			IsDrive) command="isDrive";; IsMounted) command="isMounted";; IsWin) command="isWin";;
@@ -68,7 +66,7 @@ args()
 	done
 
 	command="${command:-detail}"
-	[[ "$command" == @(IsMounted|mount|unmount) && ! $device ]] && MissingOperand "device"
+	[[ "$command" == @(IsMounted|mount|unmount|remount) && ! $device ]] && MissingOperand "device"
 	[[ "$device" == "all" ]] && all="true"
 
 	args=("$@")
@@ -89,6 +87,7 @@ getDeviceArg()
 isMountedCommand() { [[ $all ]] && { areAllMounted; return; }; isMounted; }
 mountCommand() { [[ $all ]] && { allMount; return; }; doMount && returnMountDir; }
 unmountCommand() { [[ $all ]] && { allUnmount; return; }; doUnmount; }
+remountCommand() { [[ $all ]] && { allUnMount; allMount; return; }; doUnmount; doMount && returnMountDir; }
 
 deviceCommand() { getDevice "$@" || return; echo "$device"; }
 fsCommand() { getDevice "$@" || return; getFs; }
@@ -277,12 +276,13 @@ allMount()
 	areAllMounted && return
 
 	log "mounting..."
+
 	for device in "${devices[@]}"; do
 		unset mountDir
 		{ isMounted || ! canMount; } && continue
-		log "$device..."; doMount; result="$?"
-		[[ "$result" != "0" && ! $ignoreErrors ]] && return "$result"
+		log "$device"; doMount
 	done
+
 	log "done\n"
 
 	return 0
@@ -299,8 +299,7 @@ allUnmount()
 	for device in "${devices[@]}"; do
 		unset mountDir
 		{ ! isMounted || ! canUnmount; } && continue
-		log "$device..."; doUnmount; result="$?"
-		[[ "$result" != "0" && ! $ignoreErrors ]] && return "$result"
+		log "$device"; doUnmount
 	done
 
 	log "done\n"
@@ -347,7 +346,7 @@ canUnmount()
 
 	! IsPlatform linux return 0
 
-	local mountDir="$(getMountDir)"
+	local mountDir; mountDir="$(getMountDir)" || return
 	[[ "$mountDir" == "/boot/efi" ]] && { reason="firmware drive"; return 1; }
 	[[ "$mountDir" == "/" ]] && { reason="boot drive"; return 1; }
 
@@ -394,7 +393,7 @@ doMount()
 	if isDriveLetter "$device"; then
 		doMountDriveLetter	
 	else
-		sudoc mount "/dev/$device" "$mountDir"
+		doMountOther
 	fi
 
 	# check the mounted drive
@@ -410,18 +409,31 @@ doMountDriveLetter()
 {
 	[[ ! $all ]] && { sudoc mount -t drvfs "$device:" "$mountDir"; return; }
 
-	# when mounting all drives, do not error out for empty optical media drives
+	local result desc
 
-	local result
 	desc="$(sudoc mount -t drvfs "$device:" "$mountDir" 2>&1)"; result="$?"
-
+	
+	# when mounting all drives, do not error out for empty optical media drives
 	if echo "$desc" | grep "No medium found" >& /dev/null; then
-		log "(no media)..."; cleanupMountDir; return 0
+		log " (no media)..."; cleanupMountDir; return 0
+	elif [[ "$result" != "0" ]]; then
+		log " (failed)..."
+	else
+		log "..."
 	fi
 
-	[[ "$result" != "0" ]] && { ScriptErr "$result"; return $result; }
+	[[ "$result" == "0" ]]
+}
 
-	return 0
+doMountOther()
+{
+	[[ ! $all ]] && { sudoc mount "/dev/$device" "$mountDir"; return; }
+
+	local result desc
+	desc="$(sudoc mount "/dev/$device" "$mountDir"  2>&1)"; result="$?"
+	[[ "$result" == "0" ]] && log "..." || log " (failed)..."
+
+	[[ "$result" == "0" ]]
 }
 
 doUnmount()
@@ -431,7 +443,13 @@ doUnmount()
 	# return if we cannot unmount this drive
 	! canUnmount && { ScriptErr "cannot unmount $device ($reason)"; return 1; }
 
-	platformUnmount && cleanupMountDir
+	[[ ! $all ]] && { platformUnmount && cleanupMountDir; return; }
+
+	local result desc
+	desc="$(platformUnmount 2>&1 && cleanupMountDir 2>&1)"; result="$?"
+	[[ "$result" == "0" ]] && log "..." || log " (failed)..."
+
+	[[ "$result" == "0" ]]	
 }
 
 getAllDevices() # sets devices array
@@ -520,11 +538,16 @@ getLabel()
 
 getMountDir()
 {
+	local dir
+
 	if isDriveLetter "$device"; then
-		findmnt --list --output=TARGET,OPTIONS | grep -iE "path=$device"':?\\?' | cut -d" " -f1
+		dir="$(findmnt --list --output=TARGET,OPTIONS | grep -iE "path=$device"':?\\?' | cut -d" " -f1)"
 	else
-		findmnt --noheadings --output=TARGET --source "/dev/$device"
+		dir="$(findmnt --noheadings --output=TARGET --source "/dev/$device")"
 	fi
+
+	[[ $dir ]] && echo "$dir"
+	[[ $dir ]]
 }
 
 getType()
diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -249,7 +249,7 @@ run() # run EXE [OPTIONS...]
 
 runDone()
 {
-	[[ $noPrompt ]] && IsPlatform win && echo "${RB_GREEN}done${RESET}"
+	[[ $noPrompt ]] && IsPlatform win && echo "${GREEN}done${RESET}"
 	[[ $pause ]] && pause "When the installation has finished press any key..."
 	return 0
 }
@@ -257,7 +257,7 @@ runDone()
 runPrompt()
 {
 	if [[ $noPrompt ]]; then
-		printf "${RB_GREEN}Running $1...${RESET}"
+		printf "${GREEN}Running $1...${RESET}"
 		{ ! IsPlatform win || [[ $verbose ]]; } && echo
 		return 0
 	else
@@ -459,7 +459,7 @@ appPhysical() { i chrony IntelDriverUpdate JumpCloud LogitechOptions ninite nVid
 
 appDebian()
 {
-	i CredentialStore sublime xClient SevenZip || return
+	i CredentialStore CloudInit sublime xClient SevenZip || return
 
 	{ [[ ! $force ]] && minimalInstall; } && return
 
@@ -497,10 +497,8 @@ appHostname()
 		0) # name changed
 			UpdateDone "HostnameChanged" || return
 			SleepStatus "Rebooting in 5 seconds" 5 || return
-			power reboot || return
-			exit 100 # return 100 to retry
-			;;
-		1) UpdateDone "HostnameChanged" || return; return 0;; # name unchanged
+			power reboot --exit 100; return;; # return 100 for bootstrap-init to retry
+		1) UpdateDone "HostnameChanged"; return;; # name unchanged
 		2) return 1;; # error
 	esac
 }
@@ -1068,7 +1066,7 @@ BeyondCompareInstall()
 DebianSetup()
 {
 	header "Debian Setup"
-	i apt DebianDns DebianFileSharing DebianFonts DebianLocale DebianPolicies DebianProxyServer DebianSudo || return
+	i apt DebianDns DebianFileSharing DebianFonts DebianLocale DebianPolicies DebianProxyServer DebianSudoSecurePath || return
 	DbusSetup || return
 }
 
@@ -1166,7 +1164,7 @@ DebianProxyServer()
 	echo 'Defaults env_keep += "ftp_proxy http_proxy https_proxy no_proxy FTP_PROXY HTTP_PROXY HTTPS_PROXY NO_PROXY"' | sudo tee -a /etc/sudoers || return
 }
 
-DebianSudo()
+DebianSudoSecurePath() # add /usr/local/data/bin to the sudo secure path
 {
 	sudo grep "/usr/local/data/bin" "/etc/sudoers" >& /dev/null && return
 
@@ -2188,7 +2186,7 @@ BalenaEtcher() # disc image burner
 	local v="1.5.79" dir="hardware/Balena/Etcher"
 	run "$dir/" -p "balenaEtcher-Setup-$v.exe" "balenaEtcher-$v.dmg" "balena-etcher-electron-$v-linux-x64.zip" || return
 
-	v="v12.14.1" #
+	v="v12.25.1" #
 	run "$dir/balena-cli-$v-" -p "windows-x64-standalone.zip" "macOS-x64-standalone.zip" "linux-x64-standalone.zip" --elevate "$P/balena-cli" || return
 
 	if IsPlatform win; then
@@ -2986,7 +2984,29 @@ NodeJsInstall()
 # Network
 #
 
-NetworkCore() { i domotz domotzAgent fiddler GlassWire JumpCloud JumpDesktop mDns Ninite NordVpn Proxifier TigerVnc Tribler UnifiController Wireshark; }
+NetworkCore() { i CloudInit domotz domotzAgent fiddler GlassWire JumpCloud JumpDesktop mDns MozillaVpn Ninite NordVpn Proxifier TigerVnc Tribler UnifiController Wireshark; }
+
+CloudInitInstall() { CloudInitLimitUser; }
+
+# limit the users sudo rights if they are too broad (cloud-init adds NOPASSWD:ALL)
+CloudInitLimitUser()
+{
+	local file="/etc/sudoers.d/90-cloud-init-users"
+	local line="$USER ALL=(ALL) NOPASSWD:ALL"
+
+	! sudoc ls "$file" >& /dev/null && return 						# no cloud-init sudo file
+	! sudoc grep "$line" "$file" >& /dev/null && return		# user is already limited
+
+	# add the user to the sudo group as a fail-safe
+	sudoc usermod -aG sudo $USER || return
+
+	# change the users password if not know since it is set randomly in cloud-init
+	hilight "Enter $USER password and change if not known..."		
+	[[ "$(su -c whoami $USER)" != "$USER" ]] && sudo passwd $USER
+
+	# remove NOPASSWD:ALL from the user in the sudo cloud-init settings	
+	sudoc sed -i "s/^$line/$USER ALL=(ALL) ALL/" "$file" || return
+}
 
 DomotzInstall()
 {
@@ -4151,6 +4171,7 @@ ZshInstall()
 	[[ -d "$dir/site-functions" ]] && { sudo chmod go-w "$dir/site-functions" || return; }
 
 	# plugins
+	#zplug-install "mafredri/zsh-async", from:"github", use:"async.zsh" || return
 	zplug-install "b4b4r07/enhancd", use:init.sh || return
 	zplug-install "zsh-users/zsh-syntax-highlighting", from:github, defer:3 || return
 	zplug-install || return
@@ -4640,9 +4661,9 @@ AutoHotKeyInstall()
 	# https://www.autohotkey.com/ https://autohotkey.com/download/2.0/
 	run "shareware/AutoHotKey/image/AutoHotkey_2.0-a115-f7c71ea8.zip" --elevate -- "$P/AutoHotKey" || return
 
-	printf "${RB_GREEN}Starting AutoHotKey...${RESET}"
+	printf "${GREEN}Starting AutoHotKey...${RESET}"
 	AutoHotKey startup || return
-	echo "${RB_GREEN}done${RESET}"
+	echo "${GREEN}done${RESET}"
 }
 
 altTabTerminatorInstall()
diff --git a/power b/power
--- a/power
+++ b/power
@@ -32,6 +32,7 @@ usage: power on|off|reboot|sleep|firmware|hibernate [host]:[port|all]
 															Return 0 if the host (or host PoE port) is on, and 1 if off
 	fix info|sleep|wake				examine issues preventing computer sleep or wake
 
+  -e, --exit 								return the specified exit code after the power command
   -f, --force 							force the power operation even if we believe the host is in the correct state
   -s, --ssh 								make an ssh connection
 	-t, --timeout [500]				milliseconds to wait for a response from the host.
@@ -43,11 +44,12 @@ usage: power on|off|reboot|sleep|firmware|hibernate [host]:[port|all]
 
 args()
 {
-	unset force host op port ssh switch user verbose waitSeconds waitSsh
+	unset exit force host op port ssh switch user verbose waitSeconds waitSsh
 	timeoutMilliseconds=500 waitDefault=120 poeSwitchDefault="StudyDeskSwitch"
 
 	while [ "$1" != "" ]; do
 		case "$1" in
+			--exit|-e) exit="$2"; shift;;
 			--force|-f) force="true";;
 			--help|-h) IsFunction "${command}Usage" && ${command}Usage || usage 0;;
 			--ssh|-s) ssh="true"; waitSsh="true"; [[ ! $waitSeconds ]] && waitSeconds="$waitDefault";;
@@ -173,9 +175,29 @@ powercfg.exe -RequestsOverride SERVICE "\Device\HarddiskVolume1\Windows\System32
 
 powerCommand()
 {
-	IsLocalHost "$host" && { setLocalPower "$op"; return; }
+	if ! IsLocalHost "$host"; then doRemotePower
+	elif [[ $exit ]]; then doExitPower
+	else doLocalPower "$op"
+	fi
+}
 
-	local opf="$(ProperCase "$op")"
+# run the power command and ensure the exit code is returned to the callers
+doExitPower()
+{
+	# ensure sudo credentials are active
+	sudoc -v 
+
+	# perform the power operation in a delayed sub-shell so this shell can process the exit code
+	# the sub-shell is disconnected so the power command still runs if this shell terminates
+	{ nohup bash -c 'sleep 2; power $op' & } 
+
+	exit $exit
+}
+
+
+doRemotePower()
+{
+	local opf="$(ProperCase "$op")" # op for function
 
 	# control switch port only
 	if [[ $port ]]; then
@@ -298,7 +320,7 @@ doReboot()
 	waitOn "${waitSeconds}" || return
 }
 
-setLocalPower() # op
+doLocalPower() # op
 {
 	local op="$1"
 
