updates

diff --git a/credential b/credential
--- a/credential
+++ b/credential
@@ -47,16 +47,20 @@ Other commands:
 	store						manage credential stores
 	test						test the credential manager
 
+Store options:
+	-s, --store=STORE 				credential store name, defaults to secret
+	-pp, --path-prefix=PATH 	path prefix, defaults to none
+
 Other options:
-	-s, --store=STORE 				name of the storage, defaults to secret
 	-g, --gui									use a GUI prompt for the password
 	-nfp, --no-find-pass			do not search for a password to unlock this manager
 	-p, --password=PASSWORD 	password to unlock the credential manager
 	-t, --timeout							$(ScriptOptTimeoutUsage)
 
 Environment variables (writable):
-	CREDENTIAL_MANAGER					if set, the credential manager to use
-	CREDENTIAL_STORE						if set, the credential store to use
+	CREDENTIAL_MANAGER			if set, the credential manager to use
+	CREDENTIAL_STORE				if set, the credential store to use
+	CREDENTIAL_PATH_PREFIX	if set, the credential store path prefix to use	
 
 Environment variables (view):
 	CREDENTIAL_MANAGER_CHECKED  if true, a search for a credential manager was performed.  Otherwise unset.
@@ -87,9 +91,9 @@ init()
 
 argStart()
 {
-	unset -v fallback gui manager noFindPass password store unlock; ScriptOptTimeoutArgStart
+	unset -v fallback gui manager noFindPass password pathPrefix store unlock; ScriptOptTimeoutArgStart
 	unset -v path key # for getCredentialArg
-	excludeManagers=() excludeManagersArg=() storeArg=()
+	excludeManagers=() excludeManagersArg=() pathPrefixArg=() storeArg=()
 }
 
 opt()
@@ -101,6 +105,7 @@ opt()
 		--manager|--manager=*|-m|-m=*) ScriptOptGet "manager" "$@" && aliasValidate "$manager";;
 		--no-find-pass|-nfp) noFindPass="--no-find-pass";;
 		--password|--password=*|-p|-p=*) ScriptOptGet "password" "$@";;
+		--path-prefix|--path-prefix=*|-pp|-pp=*) ScriptOptGet "pathPrefix" "$@" && pathPrefixArg=( --path-prefix "$pathPrefix" );;
 		--store|--store=*|-s|-s=*) ScriptOptGet "store" "$@" && storeArg=( --store "$store" );;
 		--timeout|--timeout=*|-t|-t=*) ScriptOptTimeout "$@";;
 		--unlock|-u) unlock="--unlock";;
@@ -112,7 +117,6 @@ argEnd()
 {
  	# set configuration
  	[[ ! $password ]] && password="$CREDENTIAL_MANAGER_PASSWORD"
- 	[[ ! $store ]] && store="${CREDENTIAL_STORE:-secret}"
 
 	# determine if we need to unlock the manager
  	[[ "$command" == @(copy|exists|get|ls|managerPassword|rm|set|store|testAll|testRead|testWrite) ]] && unlock="--unlock";
@@ -129,6 +133,21 @@ argEnd()
 	[[ "$command" == @(managerIs*) && $manager ]] && unset find
 	[[ $find ]] && { managerFind "$manager" || return; }
 
+	# determine store
+ 	if [[ ! $store ]]; then
+ 		if [[ $CREDENTIAL_STORE ]]; then store="$CREDENTIAL_STORE"
+ 		else store="$(ConfigGetCurrent "${manager}StoreDefault")"
+ 		fi
+ 		store="${store:-secret}"
+ 	fi
+
+	# determine path prefix
+ 	if [[ ! $pathPrefix ]]; then
+ 		if [[ $CREDENTIAL_PATH_PREFIX ]]; then pathPrefix="$CREDENTIAL_PATH_PREFIX"
+ 		else pathPrefix="$(ConfigGetCurrent "${manager}PathPrefix")"
+ 		fi
+ 	fi
+ 	
 	return 0
 }
 
@@ -183,7 +202,8 @@ environment()
 	cat <<-EOF
 		export CREDENTIAL_MANAGER="$manager"
 		export CREDENTIAL_MANAGER_CHECKED="true"
-		export CREDENTIAL_STORE="$store"	
+		export CREDENTIAL_STORE="$store"
+		export CREDENTIAL_PATH_PREFIX="$pathPrefix"
 		export CREDENTIAL_USER_PATH=""
 		export CREDENTIAL_UNLOCK_PATH="/secure/default"
 	EOF
@@ -642,6 +662,9 @@ isAvailableWin()
 	# check if exclude or not Windows
 	{ isExcluded win || ! IsPlatform win; } && return 1
 
+	# return if recently checked
+	local cache="credential-manager-win-ok"; ! UpdateNeeded "$cache" && return
+
 	# check wincred.exe
 	InPath "wincred.exe" || \
 		{ log3 "isAvailableWin: wincred.exe is not in the path"; return 1; }
@@ -654,7 +677,7 @@ isAvailableWin()
 	[[ "$(RunWin wincred.exe get secret-test-check 2>&1)" == "win-success" ]] || \
 		{ log3 "isAvailableWin: 'wincred.exe get secret-test-check' failed (expected win-success) "; return 1; }
 
-	return 0
+	UpdateDone "$cache"
 }
 
 #
@@ -1026,15 +1049,19 @@ unlockTerminalRequired() { ScriptErrQuiet "a terminal is required to read the $(
 mirrorUsage()
 {
 		echot "Usage: $(ScriptName) mirror PATH [KEY]
-Mirror keys from one credential manager to another.
-This will ensure the 'to' credential manager is identical to 
-the 'from' credential manager at the specified PATH and KEY.
-The 'from' credential manager is not modified.
+Mirror keys from one credential manager to another.  This will ensure the 'to' credential manager is identical to \
+the 'from' credential manager at the specified PATH and KEY.  The 'from' credential manager is not modified.
 
-	-F,	--from MANAGER	first credential manager, defaults to local
-	-T,	--to MANAGER		second credential manager, defaults to remote
-	-ie, --ignore-empty	ignore paths with no keys
-	-r, --recursive			copy all paths starting at PATH"
+	-ie, --ignore-empty						ignore paths with no keys
+	-r, --recursive								copy all paths starting at PATH
+
+	-F, --from=MANAGER						from credential manager, defaults to local
+	-fpp, --from-path-prefix=PATH	from path prefix, defaults to none
+	-fs, --from-store=STORE				from credential store name, defaults to secret
+
+	-T,	--to MANAGER							to credential manager, defaults to remote
+	-tpp, --to-path-prefix=PATH		to path prefix, defaults to none
+	-ts, --to-store=STORE					to credential store name, defaults to secret"
 }
 
 mirrorArgStart() { syncArgStart "$@"; }
@@ -1042,15 +1069,28 @@ mirrorArgStart() { syncArgStart "$@"; }
 mirrorOpt() 
 {
 	case "$1" in
-		-ie|--ignore-empty) ignoreEmpty="--ignore-empty";;
-		-r|--recursive) recursive="--recursive" ignoreEmpty="--ignore-empty";;
-		-F|--from|-F=*|--from=*) ScriptOptGet m1 "$@" && aliasValidate "$m1";;
-		-T|--to|-T=*|--to=*) ScriptOptGet m2 "$@" && aliasValidate "$m2";;
+		--ignore-empty|-ie) ignoreEmpty="--ignore-empty";;
+		--recursive|-r) recursive="--recursive" ignoreEmpty="--ignore-empty";;
+
+		--from|--from=*|-F|-F=*) ScriptOptGet m1 "$@" && aliasValidate "$m1";;
+		--from-path-prefix|--from-path-prefix=*|-fpp|-fpp=*) ScriptOptGet "o" "$@" && cred1Args+=(--path-prefix="$o") credBothArgs+=(--from-path-prefix="$o");;
+		--from-store|--from-store=*|-fs|-fs=*) ScriptOptGet "o" "$@" && cred1Args+=(--store="$o") credBothArgs+=(--from-store="$o");;
+
+		--to|--to=*|-T|-T=*) ScriptOptGet m2 "$@" && aliasValidate "$m2";;
+		--to-path-prefix|--to-path-prefix=*|-tpp|-tpp=*) ScriptOptGet "o" "$@" && cred2Args+=(--path-prefix="$o") credBothArgs+=(--to-path-prefix="$o");;
+		--to-store|--to-store=*|-ts|-ts=*) ScriptOptGet "o" "$@" && cred2Args+=(--store="$o") credBothArgs+=(--to-store="$o");;
+
 		*) return 1
 	esac
 }
 
 mirrorArgs() { syncArgs "$@"; }
+
+mirrorArgsEnd()
+{
+	cred1Args+=(--manager=$m1) credBothArgs+=(--from=$m1)
+	cred2Args+=(--manager=$m2) credBothArgs+=(--to=$m2)
+}
 
 mirrorCommand()
 {
@@ -1080,7 +1120,7 @@ mirrorCommand()
 	local paths; IFS=$'\n' ArrayMake paths "$(cred1 ls --paths "$path")"
 	for path in "${paths[@]}"; do
 		echo "Mirroring '$path to '$(description "$m2")'..."
-		credential mirror --from="$m1" --to="$m2" "$path" --ignore-empty "${globalArgs[@]}" || return
+		credBoth mirror "$path" $ignoreEmpty || return
 	done	
 }
 
@@ -1248,18 +1288,34 @@ Syncronize keys betwen the specified credential managers.
 Both credential managers are modified to ensure they are the same
 at the at the specified PATH and KEY.
 
-	-m1,	--manager1			first credential manager, defaults to local
-	-m2,	--manager2			second credential manager, defaults to remote"
+	-m1,	--manager1							first credential manager, defaults to local
+	-m1pp, --m1-path-prefix=PATH	first path prefix, defaults to none
+	-m1s, --m1-tore=STORE					first credential store name, defaults to secret
+
+	-m2,	--manager2							second credential manager, defaults to remote
+	-m2pp, --m2-path-prefix=PATH	second path prefix, defaults to none
+	-m2s, --m2-store=STORE				second credential store name, defaults to secret"
 }
 
-syncArgStart() { unset -v ignoreEmpty key path recursive; m1="local" m2="remote"; }
+syncArgStart()
+{
+	unset -v ignoreEmpty key path recursive
+	m1="local" m2="remote" cred1Args=() cred2Args=() credBothArgs=()
+}
 
 syncOpt() 
 {
 	case "$1" in
-		-m1|--manager1|-m1=*|--manager1=*) ScriptOptGet m1 "$@" && aliasValidate "$m1";;
-		-m2|--manager2|-m2=*|--manager2=*) ScriptOptGet m2 "$@" && aliasValidate "$m2";;
 		-r|--recursive) recursive="--recursive";;
+
+		-m1|--manager1|-m1=*|--manager1=*) ScriptOptGet m1 "$@" && aliasValidate "$m1";;
+		--m1-path-prefix|--m1-path-prefix=*|-m1pp|-m1pp=*) ScriptOptGet "o" "$@" && cred1Args+=(--path-prefix="$o") credBothArgs+=(--m1-path-prefix="$o");;
+		--m1-store|--m1-store=*|-m1s|-m1s=*) ScriptOptGet "o" "$@" && cred1Args+=(--store="$o") credBothArgs+=(--m1-store="$o");;
+
+		-m2|--manager2|-m2=*|--manager2=*) ScriptOptGet m2 "$@" && aliasValidate "$m2";;
+		--m2-path-prefix|--m2-path-prefix=*|-m2pp|-m2pp=*) ScriptOptGet "o" "$@" && cred2Args+=(--path-prefix="$o") credBothArgs+=(--m2-path-prefix="$o");;
+		--m2-store|--m2-store=*|-m2s|-m2s=*) ScriptOptGet "o" "$@" && cred2Args+=(--store="$o") credBothArgs+=(--m2-store="$o");;
+
 		*) return 1
 	esac
 }
@@ -1269,6 +1325,12 @@ syncArgs()
 	ScriptArgGet "path" -- "$@"; shift
 	[[ $1 ]] && { ScriptArgGet "key" -- "$@"; shift; }
 	return 0
+}
+
+syncArgsEnd()
+{
+	cred1Args+=(--manager=$m1) credBothArgs+=(--manager1=$m1)
+	cred2Args+=(--manager=$m2) credBothArgs+=(--manager2=$m2)
 }
 
 syncCommand()
@@ -1283,7 +1345,7 @@ syncCommand()
 
 	for key in "${keys[@]}"; do
 		[[ ! $quiet ]] && header "$path $key"
-		cred sync "$path" "$key" "-m1=$m1" "-m2=$m2" || return
+		credBoth sync "$path" "$key" || return
 	done
 }
 
@@ -1382,7 +1444,7 @@ getExcludeManagersOpt()
 #
 
 gnomeKeyringDaemonIsHealthy()
-{	
+{
 	gnomeKeyringDaemonEnvironment || return
 
 	# check running
@@ -1559,7 +1621,7 @@ vaultValidateServer()
 {
 	[[ ! $VAULT_ADDR ]] && { ScriptErrQuiet "the Vault environment is not set."; return 1; }
 
-	local server="$(GetUriServer "$VAULT_ADDR")" port="$(GetUriPort "$VAULT_ADDR")"
+	local server="$(GetUriServer "$VAULT_ADDR")" port="$(GetUrlPort "$VAULT_ADDR")"
 	
 	if IsAvailablePort "$server" "$port" $timeout; then
 		log3 "the Vault server '$server' is available on port $port"
@@ -1585,9 +1647,11 @@ vaultValidateUnsealed()
 aliasValidate() { listManagers "$1" > /dev/null; }
 canFallbackRemote() { ! isManagerRemote "$1" && [[ $fallback ]] && isAvailable "remote"; }
 askPassword() { ask password "Enter the $(description) credential store password"; }
-cred() { RunLog credential --unlock "${storeArg[@]}" "${excludeManagersArg[@]}" $fallback "${globalArgs[@]}" "$@"; }
-cred1() { cred "--manager=$m1" "$@"; }
-cred2() { cred "--manager=$m2" "$@"; }
+credDo() { RunLog credential --unlock "${excludeManagersArg[@]}" $fallback "${globalArgs[@]}" "$@"; }
+cred() { credDo "${storeArg[@]}" "${pathPrefixArg[@]}" "$@"; }
+cred1() { credDo "${cred1Args[@]}" "$@"; }
+cred2() { credDo "${cred2Args[@]}" "$@"; }
+credBoth() { credDo "${credBothArgs[@]}" "$@"; }
 isExcluded() { ! IsInArray "${1,,}" excludeManagers && return 1; log1 "$1 is excluded"; return 0; }
 isManager() { IsInArray "${1,,}" allManagers; } 
 isManagerRemote() { local manager="$1" a=( $(listManagers "remote") ); IsInArray "$manager" a; }
@@ -1623,22 +1687,40 @@ keyNotFound()
 	return 1
 }
 
-# managerPath PATH - return the manager specific path, i.e. : /a/b/ -> $store-a-b	
+# managerPath PATH - return the manager specific path, i.e. : /a/b/ -> $store-$pathPrefix-a-b	
 managerPath()
 {
-	# manager custom path
-	RunFunctionExists "managerPath" "$manager" && { RunFunction "managerPath" "$manager" -- "$1"; return; }
+	local path="$1"
 
-	# default path - /a/b/ -> $store-a-b	 
-	local prefix; [[ $store ]] && prefix="$store-"
-	echo "$prefix$(RemoveTrim "${1//\//-}" "-")"
+	# cleanup path - //a////b/c/ -> a/b/c
+	path="$(echo "$path" | sed 's/\/\///g' | RemoveTrim "/")"
+
+	# manager custom path
+	RunFunctionExists "managerPath" "$manager" && { RunFunction "managerPath" "$manager" -- "$path"; return; }
+
+	# default path - a/b -> $store-$pathPrefix-a-b	 
+	local prefix=""
+	[[ $store ]] && prefix+="$store-"
+	[[ $pathPrefix ]] && prefix+="${pathPrefix//\//-}-"
+	echo "$prefix$(RemoveTrim "${path//\//-}" "-")"
 }
 
-# managerPathVault PATH: /a/b/ -> /a/b/ (does not change)
-managerPathVault() { echo "$1"; }
+# managerPathVault PATH: /a/b/ -> /$pathPrefix/a/b/
+managerPathVault()
+{
+	local prefix=""
+	[[ $pathPrefix ]] && prefix+="/$(RemoveTrim "$pathPrefix" "/")"
+	echo "${prefix}/$1"
+}
 
-# managerPathPass PATH: /a/b/ -> /$store/a/b
-managerPathPass() { echo "$store/$1"; }
+# managerPathPass PATH: /a/b/ -> /$store/$pathPrefix/a/b
+managerPathPass()
+{
+	local prefix=""
+	[[ $store ]] && prefix+="/$store"
+	[[ $pathPrefix ]] && prefix+="/$(RemoveTrim "$pathPrefix" "/")"
+	echo "${prefix}/$1"
+}
 
 # operationInit OPERATION PATH KEY - set managerPathKey and managerKey to the manager specific values for the operation
 operationInit()
