credential: improvements
- bug fixes for credential handling
- consistent output for credential operations

diff --git a/credential b/credential
--- a/credential
+++ b/credential
@@ -29,7 +29,7 @@ Common commands:
 Common options:
 	-F, --fallback			 							fallback to a remote credential manager if possible
 	-em, --exclude-managers=MANAGERS	comma separated list of managers to exclude
-	-m, --manager											force the use of a specific credential manager
+	-m, --manager=MANAGER							force the use of a specific credential manager
 	-ul, --unlock											force unlocking of the credential manager"
 }
 
@@ -96,14 +96,15 @@ opt()
 
 argEnd()
 {
-	# set the credential engine
+	# set arguments from environment variables
+ 	[[ ! $manager ]] && { [[ $CREDENTIAL_MANAGER ]] && manager="$(managerNameValidate "$CREDENTIAL_MANAGER")" || manager="all"; }
  	[[ ! $engine ]] && { [[ $CREDENTIAL_ENGINE ]] && engine="$CREDENTIAL_ENGINE" || engine="secret"; }
 
 	# unlock the manager if we are running a command the requires us to be unlocked
  	[[ "$command" != @(environment|managerAvailable|managerDescription|managerName|lock|unlock|status|manager) ]] && unlock="--unlock";
 
  	# find a credential manager
- 	managerFind || return
+ 	managerFind
 }
 
 getCredentialArg() # PATH [KEY](default)
@@ -139,6 +140,7 @@ environment()
 
 	cat <<-EOF
 		export CREDENTIAL_MANAGER="$manager"
+		export CREDENTIAL_MANAGER_CHECKED="true"
 		export CREDENTIAL_ENGINE="$engine"	
 		export CREDENTIAL_USER_PATH=""
 		export CREDENTIAL_TMP_PATH="/tmp"
@@ -189,7 +191,7 @@ copyCommand()
 	local key keys value; IFS=$'\n' keys=( $(lsCommand) )
 	for key in "${keys[@]}"; do
 		value="$(getCommand)" || return
-		RunLog cred set "$dest" "$key" "$value" || return
+		cred set "$dest" "$key" "$value" || return
 	done
 
 }
@@ -207,17 +209,22 @@ existsCommand() { exists "$path" "$key" || existsFallbackRemote "$path" "$key"; 
 existsFallbackRemote()
 {
 	local path="$1" key="$2"; ! canFallbackRemote && return 1
-	log1 "credential '$path $key' does not exist in the $(managerDescription) credential store, falling back to remote store"
-	RunLog cred exists "$path" "$key" --manager=remote "$(excludeManagers "$manager")"
+	log1 "credential '$path $key' does not exist in the $(managerDescription) credential store, falling back to a remote store"
+	test="" cred exists "$path" "$key" --manager=remote "${globalArgs[@]}"
 }
 
-exists() { local path="$1" key="$2"; managerPathInit "$path" "$key" && RunSilent RunFunction "exists" "$manager"; }
+exists()
+{
+	local path="$1" key="$2"; opInit "exists" "$path" "$key" || return
+	local result return; result="$(RunFunction "exists" "$manager" 2>&1)"; return="$?"
+	log1 "exists: $result"; return "$return"
+}
 
-existsMac() { security find-generic-password -gwa $USER -s "$managerPathKey" > /dev/null; }
-existsOp() { op get item "$managerPathKey" --fields username --cache > /dev/null; }
+existsMac() { security find-generic-password -gwa $USER -s "$managerPathKey"; }
+existsOp() { op get item "$managerPathKey" --fields username --cache; }
 existsPass() { [[ -f "$HOME/.password-store/$managerPathKey.gpg" ]]; }
 existsVault() { vaultKeyExists "$managerPath" "$key"; }
-existsWin() { wincred.exe exists "$managerPathKey" > /dev/null; }
+existsWin() { wincred.exe exists "$managerPathKey"; }
 existsGk() { secret-tool search "$managerPath" "$key" | ${G}grep --quiet "^label ="; }
 
 #
@@ -247,22 +254,24 @@ getCommand() { get "$path" "$key" || getFallbackRemote "$path" "$key" || getProm
 
 get()
 {
-	[[ $quiet ]] && ! exists "$path" "$key" && return 1
-	local path="$1" key="$2"; log1 "running get: path=$path key=$key"; managerPathInit "$path" "$key" && RunFunction "get" "$manager"
+	local path="$1" key="$2"; opInit "get" "$path" "$key" || return
+	local return value; value="$(RunFunction "get" "$manager" |& RemoveNewline)"; return="$?"
+	log1 "get: $value"; (( return != 0 )) && { keyNotFound "$path" "$key"; return 1; }
+	echo "$value"
 }
 
-getMac() { security find-generic-password -gwa $USER -s "$managerPathKey" 2> /dev/null && return; keyNotFound "$path" "$key"; }
+getMac() { security find-generic-password -gwa $USER -s "$managerPathKey"; }
 getOp() { op get item "$managerPathKey" --fields "password" --cache; }
 getPass() { pass show "$managerPathKey"; }
-getGk() {	secret-tool lookup "$managerPath" "$key" | RemoveNewline; [[ "${PIPESTATUS[0]}" == 0 ]] && return; keyNotFound "$path" "$key"; }
-getVault() { vault kv get -field="$key" "$managerPath" | RemoveNewline; return "${PIPESTATUS[0]}"; }
+getGk() {	secret-tool lookup "$managerPath" "$key"; }
+getVault() { vault kv get -field="$key" "$managerPath"; }
 getWin() { wincred.exe get "$managerPathKey"; }
 
 getFallbackRemote()
 {
 	local path="$1" key="$2"; ! canFallbackRemote && return 1		
 	log1 "credential '$path $key' does not exist in the '$(managerDescription)' credential manager, falling back to a remote store"
-	test="" RunLog cred get "$path" "$key" --manager=remote "${globalArgs[@]}" || return
+	test="" cred get "$path" "$key" --manager=remote "${globalArgs[@]}"
 }
 
 getPrompt()
@@ -296,8 +305,8 @@ getTimeCommand() { getTime "$path" "$key"; }
 
 getTime()
 {
-	local path="$1" key="$2"; managerPathInit "$path" "$key" || return
-	local time="$(RunFunction "getTime" "$manager")"
+	local path="$1" key="$2"; opInit "get time" "$path" "$key" || return
+	local time; time="$(RunFunction "getTime" "$manager" 2>&1)"
 	[[ ! $time ]] && { ScriptErr "unable to determine '$path $key' modifification time"; return 1; }
 	printf "$time"
 }
@@ -348,7 +357,7 @@ lsArgs()
 
 lsCommand() { lsDo "$path"; }
 
-lsDo() { local path="$1"; log1 "running ls: path=$path"; managerPathInit "$path" && RunFunction "ls" "$manager"; }
+lsDo() { local path="$1"; opInit "ls" "$path" && RunFunction "ls" "$manager"; }
 lsMac() { lsWorker "lsMacFilter"; }
 lsOp() {	lsWorker "lsOpFilter"; }
 lsGk() { lsWorker "lsGkFilter"; }
@@ -382,16 +391,15 @@ lsVault()
 			return
 		fi
 
-		vault kv list "$path" | tail +3 | sort | sed 's/\/$//' | sed 's/$/\//' | uniq # add / suffix
-		(( ${PIPESTATUS[0]} != 0 )) && return 1
+		vault kv list "$path" | tail +3 | sort | sed 's/\/$//' | sed 's/$/\//' | uniq || return
 	fi
 
 	# keys
 	if [[ ! $onlyPaths ]] && vaultLeafHasData "$path"; then
-		vault kv get -format=json "$path" | jq '.data.data|keys|.[]' -r
-		(( ${PIPESTATUS[0]} != 0 )) && return 1
+		vault kv get -format=json "$path" | jq '.data.data|keys|.[]' -r || return
 	fi
-	
+
+	return 0	
 }
 
 lsWorker()
@@ -455,102 +463,58 @@ isManagerRemote() { [[ "${manager,,}" == @(op|vault) ]]; }
 # managerFind - find and initialize and optionally unlock a credential manager
 managerFind()
 {
-	log1 "finding a credential manager"
+ 	# if no credential manager was found and we are forcing, search for any credential manager
+	[[ $force && "$manager" == "None" ]] && manager="all"
 
-	local managerSpecified="$manager"
-
-	# use the CREDENTIAL_MANAGER variable if set
-	[[ ! $manager && $CREDENTIAL_MANAGER ]] && { manager="$CREDENTIAL_MANAGER"; manager="$(managerNameValidate "$manager")" || unset manager; }
-
-	# if manager is excluded do not use it
+	# if a manager was specified on the command line use it
 	if isManagerExcluded "$manager"; then
-		if [[ $managerSpecified ]]; then
-			[[ ! $quiet ]] && ScriptErr "the requested credential manager '$(managerDescription "$managerSpecified")' is excluded"
-			return 1
-		fi
-		log2 "managerFind: the '$manager' credential manager is excluded"
-		unset manager
-	fi
-
-	# if no credetial manager was found last time don't try again
-	if [[ "$manager" == "None" ]]; then
-		 if [[ ! $force ]]; then
-		 	[[ ! $quiet ]] && ScriptErr "no credential manager is available"
-		 	return 1;
-		 fi
-	 	unset manager
-	fi
-
-	# if an actual credential manager was specified (i.e. win not local) unlock and use it
-	if [[ $manager && $managerSpecified ]] && isManager "$manager"; then
-		unlock && return
-		[[ ! $quiet ]] && ScriptErr "unable to unlock the '$(managerDescription)' credential manager"
+		[[ ! $quiet ]] && ScriptErr "the credential manager '$(managerDescription "$manager")' is excluded"
 		return 1
 	fi
 
- 	# default to the specified credential manager, then find others if we can't unlock it
-	[[ $manager ]] && log3 "managerFind: defaulting to the '$manager' credential manager"
-
-	# if a credential manager was not specified, default to searching for all credential managers
- 	if [[ ! $manager ]]; then
- 		log3 "managerFind: no credential manager specified, finding any credential manager"
- 		manager="All" 	
- 	fi
-
- 	# find the specified credential manager
-	managerFindDo && { return; }
-
- 	# widen the credential manager search if possible
- 	[[ "$manager" != "All" ]] && manager="All" && { managerFindDo && return; }
-
- 	# credential manager is not available message
- 	manager="None"
- 	[[ ! $quiet ]] && ScriptErr "no credential manager is available"
-
-	return 1
-}
-
-managerFindDo()
-{
 	if managerFind_${manager^}; then
 		log2 "managerFind: using the $(managerDescription) credential manager ($(managerLockedStatus))"
 		return 0
+	else
+		log2 "managerFind: no credential manager is available"
+		return 1
 	fi
-	log3 "managerFind: no credential manager is available"
-	return 1
 }
 
 # managerFind_* - these function names are valid for the name of the credential manager to find
-
 managerFind_All() { log2 "managerFind: all"; managerFind_Local || managerFind_Remote; }
 managerFind_Local() { log2 "managerFind: local"; managerFind_Mac || managerFind_Win || managerFind_Gk || managerFind_Pass; }
 managerFind_Native() { log2 "managerFind: native"; managerFind_Mac || managerFind_Win; }
 managerFind_Remote() { log2 "managerFind: remote"; managerFind_Vault || managerFind_Op; }
 managerFind_None() { log2 "managerFind: none"; return 1; }
 
-managerFind_Op() { log2 "managerFind: op"; isManagerAvailableOp && managerFindUnlock "op"; }
-managerFind_Mac() { IsPlatform mac || return; log2 "managerFind: mac"; isManagerAvailableMac && managerFindUnlock "mac"; }
-managerFind_Pass() { log2 "managerFind: pass"; isManagerAvailablePass && managerFindUnlock "pass"; }
-managerFind_Gk() { IsPlatform debian || return; log2 "managerFind: GNOME Keyring"; isManagerAvailableGk && managerFindUnlock "gk"; }
-managerFind_Vault() { log2 "managerFind: Vault"; isManagerAvailableVault && managerFindUnlock "vault"; }
-managerFind_Win() { IsPlatform win || return; log2 "managerFind: win"; isManagerAvailableWin && managerFindUnlock "win"; }
+managerFind_Op() { managerFindUnlock "op"; }
+managerFind_Mac() { managerFindUnlock "mac"; }
+managerFind_Pass() { managerFindUnlock "pass"; }
+managerFind_Gk() { managerFindUnlock "gk"; }
+managerFind_Vault() { managerFindUnlock "vault"; }
+managerFind_Win() { managerFindUnlock "win"; }
 
+# managerFindUnlock MANAGER - if the manager is available and optionally unlocked return it's name
 managerFindUnlock()
 {
-	local managerTry="$1"
-	[[ ! $unlock ]] && { manager="$managerTry"; return; } # use managerTry
-	manager="$managerTry" quiet="--quiet" unlock || return
-	manager="$managerTry" # managerTry was unlocked, use it
-}
+	manager="$1"
 
-# managerPathInit PATH KEY - set managerPathKey and managerKey to the manager specific values
-managerPathInit()
-{
-	local path="$1" key="$2"
-	managerPath="$(managerPath "$path")"
-	managerPathKey="$(managerPath "$path/$key")"
-	log3 "managerPath=$managerPath managerPathKey=$managerPathKey"
-	return 0
+	# check if the manager is available
+	! isManagerAvailable${manager^} && return 1
+	log2 "managerFind: the $(managerDescription) credential manager is available"
+
+	# return the manager if we do not need to unlock it
+	[[ ! $unlock ]] && return
+
+	# use the passed manager if we can unlock it
+	if quiet="--quiet" unlock; then
+		log2 "managerFind: the $(managerDescription) credential manager was unlocked"
+		return 0
+	else
+		log2 "managerFind: unable to unlock the $(managerDescription) credential manager"
+		return 1
+	fi
 }
 
 # managerPath PATH - return the manager specific path, i.e. : /a/b/ -> $engine-a-b	
@@ -599,7 +563,7 @@ managerDescription()
 managerNameValidate()
 {
 	local name="$1" nameOrig="$1"
-	[[ $name ]] && name="$(managerNameAlias "$name")" || name="local"
+	[[ $name ]] && name="$(managerNameAlias "$name")"
 
 	# ensure correct case
 	name="$(ProperCase "$name")"
@@ -678,12 +642,13 @@ lockPass() { gpgconf --kill gpg-agent; }
 # manager password
 #
 
-managerPasswordUsage() { echot "Usage: $(ScriptName) manager password manager\nGet the password for the specified credential manager."; }
+managerPasswordUsage() { echot "Usage: $(ScriptName) manager password MANAGER\nGet the password for the specified credential manager."; }
 managerPasswordArgStart() { unset -v managerArg; }
 managerPasswordArgs() {	ScriptArgGet "managerArg" "manager" -- "$@"; managerArg="$(managerNameValidate "$managerArg")"; }
 
 managerPasswordCommand()
 {
+	# find the location of the credential manager password
 	local unlockPath
 	unlockPath="$(
 		local environment; environment="$(environment "$managerArg")" || return
@@ -692,7 +657,6 @@ managerPasswordCommand()
 	)"
 
 	local args=(); StringToArray "$unlockPath" ":" args
-	[[ $quiet ]] && ! exists "${args[@]}" && return 1
 	RunLog get "${args[@]}"
 }
 
@@ -828,12 +792,12 @@ mirrorCommand()
 	[[ $verbose ]] && { PrintErr "$m1 keys: "; ArrayShow keys; }
 
 	echo "Deleting all keys at '$path' in $m2..."
-	RunLog cred2 rm "$path" all || return
+	cred2 rm "$path" all || return
 
 	for key in "${keys[@]}"; do
 		echo "Adding '$path $key' to $m2..."
 		local value; value="$(cred1 get "$path" "$key")" || return
-		RunLog cred2 set "$path" "$key" "$value" || return
+		cred2 set "$path" "$key" "$value" || return
 	done
 }
 
@@ -869,14 +833,20 @@ rmFallbackRemote()
 
 rmDo()
 {
-	local path="$1" key="$2"; managerPathInit "$path" "$key" || return
+	local path="$1" key="$2"; opInit "rm" "$path" "$key" || return
 
 	# remove a single credential or Vault credentials
-	[[ "$key" != "all" || "$manager" == "vault" ]] && { RunFunction "rm" "$manager"; return; }
+	[[ "$key" != "all" || "$manager" == "vault" ]] && { rmWorker; return; }
 
 	# remove all credentials
 	local key keys onlyKeys="true"; IFS=$'\n' keys=( $(lsCommand) )
-	for key in "${keys[@]}"; do RunFunction "rm" "$manager" || return; done
+	for key in "${keys[@]}"; do rmWorker || return; done
+}
+
+rmWorker()
+{
+	local result return; result="$(RunFunction "rm" "$manager" 2>&1)"; return="$?"
+	log1 "rm: $result"; return "$return"
 }
 
 rmMac() { RunLog security delete-generic-password -a $USER -s "$managerPathKey"; }
@@ -924,11 +894,12 @@ setArgs()
 setCommand() { setDo "$path" "$key" "$value"; }
 
 setDo()
-{
-	local path="$1" key="$2" value="$3"
-	log1 "running set: path=$path key=$key"
-	managerPathInit "$path" "$key" && RunFunction "set" "$manager"
+{ 
+	local path="$1" key="$2" value="$3"; opInit "set" "$path" "$key" || return
+	local result return; result="$(RunFunction "set" "$manager" 2>&1)"; return="$?"
+	log1 "set: $result"; return "$return"
 }
+
 
 setMac() { security add-generic-password -U -a $USER -s "$managerPathKey" -w "$value"; }
 setPass() { echo -n "$value" | pass insert -m --force "$managerPathKey"; }
@@ -1077,13 +1048,13 @@ managerUnlockCommand()
 	return 0
 }
 
-# unlock - unlock the credential manager
+# unlock [MANAGER] - unlock the credential manager
 unlock()
 {
-	log1 "unlocking the '$manager' credential manager"
-
 	# already unlocked
 	[[ ! $force ]] && isUnlocked && verify && return
+
+	log1 "unlocking the '$manager' credential manager"
 
 	# try and find a password to unlock the credential manager
 	[[ ! $password && ! $noFindPass ]] && { unlockFindPassword || return; }
@@ -1168,9 +1139,9 @@ unlockFindPasswordTry()
 {
 	[[ "$manager" == "$managerTry" ]] && return
 
-	log1 "looking for the '$(managerDescription)' credential manager password in '$(managerDescription "$managerTry")' credential manager"
+	log1 "looking for the '$(managerDescription)' password in '$(managerDescription "$managerTry")'"	
 	password="$(RunLog credential manager password "$manager" --manager="$managerTry" "$(excludeManagers "$manager")" --no-find-pass --quiet --no-prompt "${globalArgs[@]}")" || return
-	log1 "found the '$(managerDescription)' credential manager password using the '$(managerDescription "$managerTry")' credential manager"
+	log1 "found the '$(managerDescription)' password in '$(managerDescription "$managerTry")'"
 }
 
 unlockTerminalCheck() { IsStdIn || unlockTerminalRequired; }
@@ -1180,7 +1151,9 @@ unlockTerminalRequired() { [[ ! $quiet ]] && ScriptErr "a terminal is required t
 # helper - GNOME Keyring
 #
 
-gnomeKeyringDaemonRun() {	RunQuiet gnome-keyring-daemon --replace "$@"; }
+# gnomeKeyringDaemonRun - run the gnome-keyring-daemon for secrets and pkcs11.
+#   Do not use ssh as it interferes with existing SSH agents.
+gnomeKeyringDaemonRun() {	RunQuiet gnome-keyring-daemon --components=secrets,pkcs11 --replace "$@"; }
 
 gnomeKeyringDaemonIsHealthy()
 {	
@@ -1270,7 +1243,19 @@ excludeManagers()
 keyNotFound()
 { 
 	canFallbackRemote && return 1
-	ScriptErr "key '$1 $2' does not exist in the $(managerDescription) credential store"; return 1
+	[[ ! $quiet ]] && ScriptErr "'$1 $2' does not exist in the '$(managerDescription)' credential store"
+	return 1
+}
+
+# opInit OPERATION PATH KEY - set managerPathKey and managerKey to the manager specific values for the operation
+opInit()
+{
+	local operation="$1" path="$2" key="$3"; 
+
+	managerPath="$(managerPath "$path")" || return
+	managerPathKey="$(managerPath "$path/$key")" || return
+
+	log1 "$operation: path='$path' key='$key' mp='$managerPath' mpk='$managerPathKey'"
 }
 
 ScriptRun "$@"
