manager: add rebuild command, cleanup function signatures

diff --git a/credential b/credential
--- a/credential
+++ b/credential
@@ -124,7 +124,7 @@ argEnd()
 
 	# find a manager if needed
 	local find="true"
-	[[ "$command" == @(managerFind|managerList*) ]] && unset find
+	[[ "$command" == @(managerFind|managerList*|managerRebuild) ]] && unset find
 	[[ "$command" == @(managerIs*) && $manager ]] && unset find
 	[[ $find ]] && { managerFind "$manager" || return; }
 
@@ -478,7 +478,7 @@ lsPathsRecursive()
 # manager commands
 #
 
-managerUsage() { echot "Usage: $(ScriptName) manager [cleanup|debug|find|lock|name|password|status|unlock](status)\nManage credential managers."; }
+managerUsage() { echot "Usage: $(ScriptName) manager [cleanup|debug|find|lock|name|password|rebuild|status|unlock](status)\nManage credential managers."; }
 managerCommand() { managerStatus; }
 
 managerNameUsage() { echot "Usage: $(ScriptName) manager name\nShow the name of the credential manager."; }
@@ -492,9 +492,9 @@ managerNameValidate() { isManager "$1" && return; managerInvalid "$1"; }
 #
 
 managerCleanupUsage() { echot "Usage: $(ScriptName) manager cleanup\nCleanup the credential manager by terminating resident processes."; }
-managerCleanupCommand() { cleanupDo; }
+managerCleanupCommand() { cleanupDo "$manager"; }
 
-cleanupDo() { lock; RunFunction "cleanup" "$manager"; }
+cleanupDo() { local manager="$1"; lock "$manager"; RunFunction "cleanup" "$manager"; }
 cleanupGk() { ProcessCloseWait --full "gnome-keyring-daemon"; }
 cleanupOp() { ProcessCloseWait "op"; }
 
@@ -554,35 +554,36 @@ managerFind()
 	# single manager specified
 	if (( ${#managers[@]} == 1 )); then
 		manager="${managers[0]}"
-		isAvailable "$manager" && { [[ ! $unlock ]] || unlock; } && { managerFound; return; }
-		managerNotFound; return
+		isAvailable "$manager" && { [[ ! $unlock ]] || unlock; } && { managerFound "$manager"; return; }
+		managerNotFound "$alias"; return
 	fi
 
 	# search for the first unlocked manager
 	local available=()
 	for manager in "${managers[@]}"; do
 		isAvailable "$manager" && available+=("$manager") || continue
-		{ [[ ! $unlock ]] || isUnlocked; } && { managerFound; return; }
+		{ [[ ! $unlock ]] || isUnlocked "$manager"; } && { managerFound "$manager"; return; }
 	done
 
 	# search for the first available manager which we can unlock
 	for manager in "${available[@]}"; do
-		[[ $unlock ]] && quiet="--quiet" unlock && { managerFound; return; }
+		[[ $unlock ]] && quiet="--quiet" unlock && { managerFound "$manager"; return; }
 	done
 
 	# no manager found
-	managerNotFound
+	managerNotFound "$alias"
 }
 
-managerFound() { log2 "managerFind: using the '$(description)' credential manager"; }
+managerFound() { local manager="$1"; log2 "managerFind: using the '$(description "$manager")' credential manager"; }
 
 managerNotFound()
 {
-	local message
-	if [[ "${alias,,}" == @(|all|none) ]]; then
+	local manager="$1" message
+
+	if [[ "${manager,,}" == @(|all|none) ]]; then
 		message="no credential manager is available"
 	else
-		message="the '$(description "$alias")' credential manager is not available"
+		message="the '$(description "$manager")' credential manager is not available"
 	fi
 
 	[[ $quiet ]] && log2 "managerFind: $message" || ScriptErr "$message"
@@ -603,6 +604,7 @@ managerIsCommand() { managerIsAvailableCommand; }
 managerIsAvailableUsage() { echot "Usage: $(ScriptName) is available\nReturn 0 if the credential manager is available."; }
 managerIsAvailableCommand() { isAvailable "$manager"; }
 
+# isAvailable [MANAGER]($manager)
 isAvailable()
 {
 	local alias="${1:-$manager}" manager
@@ -649,11 +651,12 @@ isLocked() { ! isUnlocked "$1"; }
 managerIsUnlockedUsage() { echot "Usage: $(ScriptName) is available\nReturn 0 if the credential manager is unlocked."; }
 managerIsUnlockedCommand() { isUnlocked "$manager"; }
 
+# isUnlocked MANAGER
 isUnlocked()
 {
-	local alias="${1:-$manager}" manager
+	local manager="$1" manager
 
-	for manager in $(listManagers "$alias"); do 
+	for manager in $(listManagers "$manager"); do 
 		{ isExcluded "$manager" || ! isAvailable "$manager"; } && continue
 		log2 "isUnlocked: checking if the '$(description)' credential manager is unlocked"; 	
 		RunFunctionLog "isUnlocked" "$manager" 2 "isUnlocked: the '$(description)' credential manager IS\$fail unlocked" " NOT" && return
@@ -785,12 +788,15 @@ managerLockUsage() { echot "Usage: $(ScriptName) lock\nLock the credential manag
 managerLockCommand()
 {
 	! RunFunctionExists "lock" "$manager" && return
-	lock || { ScriptErrQuiet "unable to lock the $(description) credential manager."; return 1; }
+	lock "$manager" || { ScriptErrQuiet "unable to lock the $(description) credential manager."; return 1; }
 	EchoQuiet "The $(description) credential manager was locked."
 }
 
+# lock MANAGER
 lock()
 { 
+	local manager="$1"
+
 	# manager does not support locking
 	! RunFunctionExists "lock" "$manager" && return
 
@@ -832,12 +838,52 @@ managerPasswordNeededWin() { return 1; }
 managerPasswordNeededMac() { return 1; }
 
 #
+# manager rebuild command
+#
+
+managerRebuildUsage() { echot "Usage: $(ScriptName) manager rebuild MANAGER\nDelete and rebuild the specified credential manager."; }
+managerRebuildArgStart() { unset -v managerArg; }
+managerRebuildArgs() { ScriptArgGet "managerArg" "manager" -- "$@"; managerNameValidate "$managerArg"; }
+
+managerRebuildCommand()
+{
+	# require force as all passwords are deleted
+	[[ ! $force ]] && { ScriptErr "to rebuild the '$(description "$managerArg")' credential manager --force is required."; return 1; }
+
+	# check if the manager is available
+	! isAvailable${managerArg^} && { managerNotFound "$managerArg"; return 1; }
+
+	# cleanup
+	hilight "Cleaning up the '$(description "$managerArg")' credential manager..."
+	cleanupDo "$managerArg" || return
+
+	# rebuild
+	hilight "Cleaning the '$(description "$managerArg")' credential manager..."
+	RunFunction managerClean "$managerArg";
+
+	# initialize
+	hilight "Initializing the '$(description "$managerArg")' credential manager..."
+	ScriptEval credential environment -vvv --unlock --force "${globalArgs}" || return
+	credential test all -vvv  || return
+
+}
+
+managerCleanGk() { rm -fr "$HOME/.local/share/keyrings"; }
+
+#
 # manager status command
 #
 
 managerStatusUsage() { echot "Usage: $(ScriptName) status\nShow the credential manager status."; }
-managerStatusCommand() { managerStatus; }
-managerStatus() {	[[  $quiet ]] && return; EchoWrap "Using the '$(description)' credential manager ($(lockedStatus))"; }
+managerStatusCommand() { managerStatus "$manager"; }
+
+# managerStatus MANAGER
+managerStatus()
+{
+	local manager="$1"
+	[[ $quiet ]] && return
+	EchoWrap "Using the '$(description "$manager")' credential manager ($(lockedStatus "$manager"))"
+}
 
 #
 # manager unlock command
@@ -846,18 +892,20 @@ managerStatus() {	[[  $quiet ]] && return; EchoWrap "Using the '$(description)' 
 managerUnlockCommand()
 {
 	! RunFunctionExists "unlock" "$manager" && return
-	unlock || { ScriptErrQuiet "Unable to unlock the $(description) credential manager."; return 1; }
+	unlock "$manager" || { ScriptErrQuiet "Unable to unlock the $(description) credential manager."; return 1; }
 	EchoQuiet "The $(description) credential manager was unlocked."
 }
 
-# unlock [MANAGER] - unlock the credential manager
+# unlock [MANAGER]($manager) - unlock the credential manager
 unlock()
 {
+	local manager="${1:-$manager}"
+
 	# manager does not support unlocking
 	! RunFunctionExists "unlock" "$manager" && return
 
 	# already unlocked
-	[[ ! $forceUnlock ]] && isUnlocked && return
+	[[ ! $forceUnlock ]] && isUnlocked "$manager" && return
 
 	log1 "unlock: unlocking the '$(description)' credential manager"
 
@@ -865,7 +913,7 @@ unlock()
 	[[ ! $password && ! $noFindPass ]] && { unlockFindPassword || return; }
 		
 	# unlock the credential manager
-	RunFunction "unlock" "$manager" && isUnlocked && return
+	RunFunction "unlock" "$manager" && isUnlocked "$manager" && return
 
 	# unable to unlock
  	ScriptErrQuiet "unable to unlock the '$(description)' credential manager"
@@ -888,7 +936,7 @@ unlockGk()
 		for (( i=1; i<=3; ++i )); do
 	  	password="$(askPassword)" || return		
 			echo -n "$password" | gnomeKeyringDaemonStart --unlock
-			isUnlocked && break
+			isUnlockedGk && break
 		done
 
 	# unlock with an X Windows dialog, which retries if the password is not correct
@@ -959,6 +1007,7 @@ mirrorUsage()
 Mirror keys from one credential manager to another.
 This will ensure the 'to' credential manager is identical to 
 the 'from' credential manager at the specified PATH and KEY.
+The 'from' credential manager is not modified.
 
 	-F,	--from MANAGER	first credential manager, defaults to local
 	-T,	--to MANAGER		second credential manager, defaults to remote
@@ -988,7 +1037,7 @@ mirrorCommand()
 	[[ $key ]] && { mirrorKey; return; }
 
 	# require force as can't check if a path exists, only a specific credential
-	[[ ! $force ]] && { ScriptErr "to overwrite all values at '$path' in '$(description "$m2")' --force must be specified."; return 1; }
+	[[ ! $force ]] && { ScriptErr "to overwrite all values at '$path' in '$(description "$m2")' --force is required."; return 1; }
 
 	# get m1 keys at path
 	local key keys; IFS=$'\n' ArrayMake keys "$(cred1 ls --keys "$path")"
@@ -1174,6 +1223,8 @@ syncUsage()
 {
 		echot "Usage: $(ScriptName) sync PATH [KEY](default)
 Syncronize keys betwen the specified credential managers.
+Both credential managers are modified to ensure they are the same
+at the at the specified PATH and KEY.
 
 	-m1,	--manager1			first credential manager, defaults to local
 	-m2,	--manager2			second credential manager, defaults to remote"
@@ -1272,10 +1323,10 @@ testAllCommand() { testSetCommand && testGetCommand; }
 testPathUsage() { EchoWrap "Usage: $(ScriptName) test path\nThe path for the credential manager test."; }
 testPathCommand() { testPath; }
 
-testGetUsage() { EchoWrap "Usage: $(ScriptName) test get\nTest a credential manager get."; }
+testGetUsage() { EchoWrap "Usage: $(ScriptName) test get\nTest credential manager get."; }
 testGetCommand() { local path key; pathToKey "$(testPath)" && get "$path" "$key" > /dev/null; }
 
-testSetUsage() { EchoWrap "Usage: $(ScriptName) test path\nTest a credential manager set."; }
+testSetUsage() { EchoWrap "Usage: $(ScriptName) test set\nTest credential manager set."; }
 testSetCommand() { local path key; pathToKey "$(testPath)" && setDo "$path" "$key" "$manager-success"; }
 
 testPath() { echo "$CREDENTIAL_USER_PATH/test/check"; }
@@ -1508,7 +1559,7 @@ cred2() { cred "--manager=$m2" "$@"; }
 isExcluded() { ! IsInArray "${1,,}" excludeManagers && return 1; log1 "$1 is excluded"; return 0; }
 isManager() { IsInArray "${1,,}" allManagers; } 
 isManagerRemote() { local manager="$1" a=( $(listManagers "remote") ); IsInArray "$manager" a; }
-lockedStatus() { isUnlocked && echo "unlocked" || echo "locked"; }
+lockedStatus() { isUnlocked "$1" && echo "unlocked" || echo "locked"; }
 pathToKey() { path="$1"; key="$(GetFileName "$path")" path="$(GetFilePath "$path")"; }
 
 # description [MANAGER] - return the description of the credential manager 
