script.sh: add log functions

diff --git a/credential b/credential
--- a/credential
+++ b/credential
@@ -107,7 +107,7 @@ managerCommand()
 statusCommand()
 {	
 	echo "Credential store is $type"
-	
+
 	if [[ "$type" == "vault" ]]; then
 		echo; vault status 
 	elif findManagerVault; then
@@ -136,7 +136,7 @@ copyCommand()
 {
 	local path="$originalPath"
 
-	[[ $verbose ]] && echo "Copying path $src to $dest..."
+	log1 "copying path $src to $dest..."
 	initPath "$src" || return
 
 	local key keys value; IFS=$'\n' keys=( $(listCommand) )
@@ -163,7 +163,7 @@ deleteCommand() { deleteDo && deleteFallbackRemote; }
 deleteFallbackRemote()
 {
 	! canFallbackRemote && return
-	[[ $verbose ]] && EchoErr "deleting credential '$originalPath $key' from the remote store"
+	log1 "deleting credential '$originalPath $key' from the remote store"
 	cred delete "$originalPath" "$key" --manager=remote || return
 }
 
@@ -234,7 +234,7 @@ existsCommand() { existsDo || existsFallbackRemote; }
 existsFallbackRemote()
 {
 	! canFallbackRemote && return 1
-	[[ $verbose ]] && EchoErr "credential '$originalPath $key' does not exist in the local store, falling back to remote store"
+	log1 "credential '$originalPath $key' does not exist in the local store, falling back to remote store"
 	cred exists "$originalPath" "$key" --manager=remote
 }
 
@@ -273,7 +273,7 @@ getCommand() { getDo || getFallbackRemote || getPrompt; }
 getFallbackRemote()
 {
 	! canFallbackRemote && return 1		
-	[[ $verbose ]] && EchoErr "credential '$originalPath $key' does not exist in the local store, falling back to remote store"
+	log1 "credential '$originalPath $key' does not exist in the local store, falling back to remote store"
 	cred get "$originalPath" "$key" --manager=remote || return
 }
 
@@ -287,12 +287,12 @@ getPrompt()
 	[[ ! $value ]] && { ScriptErr "no credential specified"; return 1; }
 
 	# set the credential
-	[[ $verbose ]] && EchoErr "setting credential '$originalPath $key' to '$value'"
+	log1 "setting credential '$originalPath $key' to '$value'"
 	setCommand || return
 
 	# set the credential in the remote credential store if needed
 	{ isManagerRemote || [[ ! $fallback ]] || ! checkManagerRemote; } && return
-	[[ $verbose ]] && EchoErr "setting credential '$originalPath $key' to '$value' in the remote credential store"
+	log1 "setting credential '$originalPath $key' to '$value' in the remote credential store"
 	cred set "$originalPath" "$key" "$value" --manager=remote || return
 
 	echo "$value"
@@ -514,13 +514,13 @@ syncCommand()
 {
 	local path="$originalPath"
 
-	[[ $verbose ]] && echo "credential: syncing $path from $m1 to $m2"
+	log1 "syncing $path from $m1 to $m2"
 
 	[[ $key ]] && { syncKey; return; }
 	
 	# get all keys at path
 	local key keys; IFS=$'\n' keys=( $({ cred1 list --keys "$path"; cred2 list --keys "$path"; } | sort | uniq) )
-	[[ $verbose ]] && { printf "credential: all keys: "; ArrayShow keys; }
+	[[ $verbose ]] && { PrintErr "all keys: "; ArrayShow keys; }
 
 	for key in "${keys[@]}"; do
 		header "$path $key"
@@ -560,8 +560,8 @@ syncKey()
 	local time2; time2="$(cred2 get time "$path" "$key" | GetSeconds -)" || return
 
 	if [[ $verbose ]]; then
-		echo "credential: $m1 modifification time is $(cred1 get time "$path" "$key") ($time1 seconds)"
-		echo "credential: $m2 modifification time is $(cred2 get time "$path" "$key") ($time2 seconds)"
+		log1 "$m1 modifification time is $(cred1 get time "$path" "$key") ($time1 seconds)"
+		log1 "$m2 modifification time is $(cred2 get time "$path" "$key") ($time2 seconds)"
 	fi
 
 	if (( $(echo "$time1 > $time2" | bc -l) )); then
@@ -605,7 +605,7 @@ mirrorCommand()
 {
 	local path="$originalPath"
 
-	[[ $verbose ]] && echo "credential: mirroring $path from $m1 to $m2..."
+	log1 "mirroring $path from $m1 to $m2..."
 
 	[[ $key ]] && { mirrorKey; return; }
 
@@ -614,7 +614,7 @@ mirrorCommand()
 	# get m1 keys at path
 	local key keys; IFS=$'\n' keys=( $(cred1 list --keys "$path") )
 	[[ ! $keys ]] && { ScriptErr "no permission or no keys at '$path' in $m1"; return 1; }
-	[[ $verbose ]] && { printf "credential: $m1 keys: "; ArrayShow keys; }
+	[[ $verbose ]] && { PrintErr "$m1 keys: "; ArrayShow keys; }
 
 	echo "Deleting all keys at '$path' in $m2..."
 	$testEcho cred2 delete "$path" all || return
@@ -651,7 +651,7 @@ validateManager()
 
 	# check if the credential manage is valid
 	if ! IsFunction "findManager${type}"; then
-		[[ ! $quiet ]] && EchoErr "credential: '$type' is not a valid credential manager"
+		[[ ! $quiet ]] && ScriptErr "'$type' is not a valid credential manager"
 		return 1
 	fi
 
@@ -662,10 +662,11 @@ findManager()
 {
 	# default to the local credential manager
  	[[ ! $type ]] || { [[ "$type" == "None" && $force ]]; } && type="local"
+	log3 "defaulting to the '$type' credential manager"
 
  	# find the specified credential manager
 	if findManager${type^}; then
-		(( verboseLevel > 1 )) && ScriptErr "using the '$type' credential manager"
+		log2 "using the '$type' credential manager"
 		return 0
 	fi
 
@@ -728,16 +729,18 @@ checkManagerSecretTool()
 checkManagerVault()
 {
 	# return if Vault is excluded or not installed
-	{ IsInArray "vault" excludeManagers || ! InPath vault; } && return 1
+	IsInArray "vault" excludeManagers && { log2 "vault is excluded"; return 1; }
+	! InPath vault && { log2 "vault is not installed"; return 1; }
 
 	# ensure the vault configuration is set
-	[[ ! $VAULT_ADDR || ! $VAULT_TOKEN ]] && { eval "$(hashi vault environment $quiet)" || return; }
-	[[ ! $VAULT_ADDR || ! $VAULT_TOKEN ]] && return 1
+	[[ ! $VAULT_ADDR || ! $VAULT_TOKEN ]] && { log2 "configuring vault environment"; eval "$(hashi vault environment $quiet $verbose)" || return; }
+	[[ ! $VAULT_ADDR ]] && { log2 "vault server address not found"; return 1; }
+	[[ ! $VAULT_TOKEN ]] && { log2 "vault authentication token not found"; return 1; }
 
 	# check if the Vault verver is available
 	local server="$(GetUriServer "$VAULT_ADDR")" port="$(GetUriPort "$VAULT_ADDR")"
 	if ! IsAvailablePort "$server" "$port"; then
-		EchoErr "The Vault server $server is not responding on port $port"
+		ScriptErr "the Vault server $server is not responding on port $port"
 		return 1
 	fi
 
@@ -792,15 +795,14 @@ vaultPathHasChildren() { vault kv list "$1" >& /dev/null; } 							# vaultPathHa
 canFallbackRemote() { ! isManagerRemote && [[ $fallback ]] && checkManagerRemote; }
 
 cred()
-{
-	[[ $verbose ]] && EchoErr credential: credential "${engineArg[@]}" "${excludeManagersArg[@]}" $fallback $force $quiet $verbose "$@"
-	credential "${engineArg[@]}" "${excludeManagersArg[@]}" $fallback $force $quiet $verbose "$@" 
+{	
+	LogRun credential "${engineArg[@]}" "${excludeManagersArg[@]}" $fallback $force $quiet $verbose "$@" 
 }
 
 keyNotFound()
 { 
 	canFallbackRemote && return 1
-	EchoErr "key '$1 $2' does not exist in the '$type' credential store"; return 1
+	ScriptErr "key '$1 $2' does not exist in the '$type' credential store"; return 1
 }
  
 resolveTypeAlias()
