script conversion

diff --git a/cygwin b/cygwin
--- a/cygwin
+++ b/cygwin
@@ -3,16 +3,22 @@
 
 # arguments: setup.exe --help, -q|--quiet-mode, -P|--packages <command separated package list>
 #   -M|--package-manager package manager
-# example: cygwin close || return; cygwin setup --quiet-mode --packages attr || return
+# example: 
+#   cygwin download 			# view and download the latest updates, or download new packages
+#   cygwin install 				# install latest updates
+# 	cygwin download -q 		# get latest updates with no prompting
+# 	cygwin install -q 		# install latest updates with no prompting
+#   cygwin download -q -P attr,cron	# download the attr and cron packages silently
+#   cygwin install -q -P attr,cron	# download the attr and cron packages silently
+#		cygwin close || return; cygwin install || return # install packages which require Cygwin programs closed
 
 usage() {	
 echot "\
-usage: cygwin [close|download|setup|start] (setup)
+usage: cygwin [command] (install)
   close - close Cygwin programs
-  download - download new or updated Cygwin binaries to the local store
-  setup [-P|--packages <package,...>] [-C|--categories <categories,...>] 
-  	Install packages from local store"
-	-q|--quiet  		run in quiet mode without prompting
+  start|download|install|help [-P|--packages <package,...>] [-C|--categories <categories,...>] 
+  	download (to local store), install (from local store), or start setup
+	-q|--quiet  		run in quiet mode without prompting"
 	exit $1
 }
 
@@ -26,31 +32,29 @@ init()
 
 args()
 {
-	unset setup packageDir
+	unset packageDir 
+	quiet="--package-manager"
 	while [[ "$1" != "" ]]; do
 		case "$1" in
+			-q|--quiet) quiet="--quiet-mode";;
 			-h|--help) usage 0;;
 			*)
 				[[ ! $command ]] && IsFunction "${1,,}Command" && { command="${1,,}"; shift; continue; }
-				[[ "$command" == @(download|setup) ]] && break
+				[[ "$command" == @(download|install|start) ]] && break
 				UnknownOption "$1"
 		esac
 		shift
 	done
-	[[ ! $command ]] && command='setup'
+	[[ ! $command ]] && command='install'
 	args=( "$@" )
 }
 
 run() {	init; args "$@"; ${command}Command "${args[@]}"; }
 RunSetup() {	FindSetup || return; cygstart -d "$tmp" "$setup" "${setupArgs[@]}" "$@"; }
-downloadCommand() { RunSetup --package-manager --download "$@"; }
 startCommand() { RunSetup "$@"; }
-
-setupCommand()
-{
-	FindSetup || return
-	RunSetup --package-manager --local-install "$@"
-}
+helpCommand() { FindSetup || return; "$setup" --help; }
+installCommand() { RunSetup $quiet --local-install "$@"; }
+downloadCommand() { RunSetup $quiet --download "$@"; }
 
 closeCommand()
 {
@@ -70,9 +74,11 @@ FindSetup()
 	[[ $setup ]] && return
 
 	# FindPublicDoc data/install/Cygwin/setup/setup-x64.exe
-	
-	setup="/cygdrive/e/data/install/Cygwin/setup/setup-x64.exe"
-	packageDir="/cygdrive/e/data/install/Cygwin/package-x64"
+	#local base="/cygdrive/e"
+	local base="$PUB/Documents"
+
+	setup="$base/data/install/Cygwin/setup/setup-x64.exe"
+	packageDir="$base/cygdrive/e/data/install/Cygwin/package-x64"
 
 	setupArgs+=( --local-package-dir "\"$(utw "$packageDir")\"" )
 }
