Script conversion

diff --git a/cygwin b/cygwin
--- a/cygwin
+++ b/cygwin
@@ -14,6 +14,7 @@
 usage() {	
 echot "\
 usage: cygwin [command] (install)
+	cleanup - cleanup directories
   close - close Cygwin programs
   setup|(re)download|install|help [-P|--packages <package,...>] [-C|--categories <categories,...>] 
   	download (to local store), install (from local store), or start setup
@@ -26,13 +27,13 @@ init()
 	installDir="$P/Cygwin"
 	bin="$InstallDir/bin"
 	downloadSite="http://mirrors.kernel.org/sourceware/cygwin/"
-	defaultPackages="util-linux,openssh,dialog,git,git-gui,gitk,git-completion"
+	defaultPackages="dialog,git,git-gui,gitk,git-completion,openssh,util-linux,vim"
 	setupArgs=( --no-shortcuts --site "$downloadSite" --root "$installDir" )
 }
 
 args()
 {
-	unset packageDir 
+	unset setup packageDir 
 	quiet="--package-manager"
 	while [[ "$1" != "" ]]; do
 		case "$1" in
@@ -79,16 +80,20 @@ closeCommand()
 FindSetup()
 {
 	[[ $setup ]] && return
-
-	# FindPublicDoc data/install/Cygwin/setup/setup-x64.exe
-	#local base="/cygdrive/e"
-	local base="$PUB/Documents"
-	local base="//oversoul/public/Documents"
-
-	setup="$base/data/install/Cygwin/setup/setup-x64.exe"
-	packageDir="$base/data/install/Cygwin/package-x64"
-
+	local base
+	base="$(FindPublicDoc data/install/Cygwin)" || return
+	setup="$base/setup/setup-x64.exe"
+	packageDir="$base/package-x64"
 	setupArgs+=( --local-package-dir "$packageDir" )
+}
+
+cleanupCommand()
+{
+	# cleanup files in /
+	local files=( "/Cygwin.bat" "/Cygwin-Terminal.ico" "/Cygwin.ico" )
+	for file in "${files[@]}"; do 
+		rm -f "$file" || return
+	done
 }
 
 run "$@"
