drive: running windows programs on CryFS drives
- function.sh: add DirSave/DirRestore

diff --git a/drive b/drive
--- a/drive
+++ b/drive
@@ -609,7 +609,9 @@ getAllDevices()
 
 	# Windows drive letters
 	if IsPlatform win; then
+		DirSave || return # windows programs fail on some drives (i.e. CryFS drives)
 		devices+=( $(fsutil.exe fsinfo drives | sed 's/:\\//g' | sed 's/Drives: //g' | tr '[:upper:]' '[:lower:]' | RemoveCarriageReturn ) )
+		DirRestore || return
 	fi
 
 	# regular disks
@@ -744,10 +746,12 @@ getType()
 getUnc() 
 {
 	! isDriveLetter "$device" && return
+	DirSave || return # windows programs fail on some drives (i.e. CryFS drives)
 	echo "$(net.exe use | RemoveCarriageReturn | grep "${device^}": | \
 		sed 's/Micorosoft Windows Network//' | \
 		sed 's/Parallels Shared Folders//' | \
 		tr -s " " | RemoveSpaceTrim | cut -d" " -f2- | BackToForwardSlash)"
+	local result="$?"; DirRestore && return $result
 }
 
 isEfiDevice()
