drive: better Parallels drive support

diff --git a/drive b/drive
--- a/drive
+++ b/drive
@@ -28,7 +28,9 @@ Manipulate system drives.
 	detail						list detailed information of all drives
 	list [removable]	list device names of all or specified types of drives
 	mounts						list mount directory of all mounted drives
-	win								manipulate windows drives"
+	win								manipulate windows drives
+
+	-no,	 --no-optical		do not mount optical drives"
 }
 
 init()
@@ -40,18 +42,15 @@ init()
 	return 0
 }
 
-argStart() { unset -v all device deviceArg; }
-
 opt()
 {
-	case "$1" in "") : ;;
-		-h|--help) usage 0;;
-		-q|--quiet) quiet="--quiet";;
-		-v|--verbose) verbose="--verbose";;
+	case "$1" in
+		--no-optical|-no) noOptical="--no-optical";;
 		*) return 1;;
 	esac
 }
 
+argStart() { unset -v all device deviceArg noOptical; }
 args() { isQuietCommand && quiet="--quiet"; getDeviceArg "$1"; }
 isQuietCommand() { [[ "$command" == @(isDrive|isWin) ]]; }
 needsDevice() { [[ "$command" == @(desc|device|format|fs|label|isDrive|isMounted|isWin|mount|unmount|remount|resize|root|setLabel|size|type) ]]; }
@@ -65,6 +64,9 @@ getDeviceArg()
 
 	device="${device#/dev/}" 	# remove /dev/
 	device="${device,,}" 			# lower case
+
+	# drive letter - remove :
+	isDriveLetter "$(RemoveEnd "$device" ":")" && device="$(RemoveEnd "$device" ":")"
 
 	# physical device 
 	[[ "$device" == "all" ]] && { all="true"; return; }
@@ -376,7 +378,10 @@ canMount()
 {
 	# check UNC share of device
 	local share; share="$(getUnc)" || return
-	[[ "$share" == '\\Mac\Dropbox' ]] && { reason="Parallels Dropbox"; return 1; }
+	[[ "$share" == '//Mac/Dropbox' ]] && { reason="Parallels Dropbox"; return 1; }
+
+	# check removable
+	[[ $noOptical ]] && isOptical && { reason="optical drive"; return 1; }
 
 	# check types
 	local type="$(getType)"
@@ -417,9 +422,9 @@ doMount()
 	# return if the drive is already mounted
 	mountDir="$(getMountDir)" && return
 
-	# identify the mount point - use the drive label if possible
+	# identify the mount point - use the drive label if possible	
 	mountDir="$mountRoot/$device" label="$(getLabel)"
-	[[ $label && ! -e "$mountRoot/$label" ]] && mountDir="$mountRoot/$label"
+	[[ $label && ! -e "$mountRoot/$label" ]] && { mountDir="$mountRoot/$label"; log1 "label=$label"; }
 
 	# return if we cannot mount the drive
 	! canMount && { ScriptErr "cannot mount $device ($reason)"; return 1; }
@@ -429,6 +434,7 @@ doMount()
 
 	# create the mount directory
 	[[ ! -d "$mountDir" ]] && { sudoc mkdir --parents "$mountDir" || return 1; } # use --parents for LVM
+	log1 "mountDir=$mountDir"
 
 	# mount the drive - supress some errors when mounting all devices
 	local desc result
@@ -450,11 +456,15 @@ doMount()
 
 doMountDriveLetter()
 {
-	[[ ! $all ]] && { sudoc mount -t drvfs "$device:" "$mountDir"; return; }
-
-	local result desc
+	if [[ ! $all ]]; then
+		log1 "sudoc mount -t drvfs $device: $mountDir"
+		sudoc mount -t drvfs "$device:" "$mountDir"; return;
+	fi
 
 	# skip some errors when mounting all drives
+	local result desc
+	
+	log1 "sudoc mount -t drvfs $device: $mountDir"
 	desc="$(sudoc mount -t drvfs "$device:" "$mountDir" 2>&1)"; result="$?"
 	
 	# empty optical media drives
@@ -463,7 +473,7 @@ doMountDriveLetter()
 
 	# mount failed
 	elif [[ "$result" != "0" ]]; then
-		log " (failed)..."
+		log1 "$result"; log " (failed)..."
 
 	# mount succeeded
 	else
@@ -542,8 +552,13 @@ getFs()
 
 getLabel()
 {
+	local label
+
 	# Windows drive letters
-	isDriveLetter "$device" && { cmd.exe /c vol "$device": |& RemoveCarriageReturn | grep -v "has no label" | grep "Volume in" | cut -d" " -f7-; return; }
+	if isDriveLetter "$device"; then		
+		label="$(getUnc)"; [[ $label ]] && { echo "$(GetUncShare "$label")"; return; } # Parallels - drive letters UNC is inm the format \\Mac\<label>		
+		label="$(cmd.exe /c vol "$device": |& RemoveCarriageReturn | grep -v "has no label" | grep "Volume in" | cut -d" " -f7-)" || return
+	fi
 
 	# lsblk, except in Windows where the label is empty
 	! IsPlatform win && { lsblk --nodeps --noheadings --output LABEL "/dev/$device" |& grep -v "not a block device"; return; }
@@ -563,10 +578,10 @@ getLabel()
 getUnc() 
 {
 	! isDriveLetter "$device" && return
-	echo "\\$(net.exe use | RemoveCarriageReturn | grep "${device^}": | \
+	echo "$(net.exe use | RemoveCarriageReturn | grep "${device^}": | \
 		sed 's/Micorosoft Windows Network//' | \
 		sed 's/Parallels Shared Folders//' | \
-		tr -s " " | cut -d\\ -f2- | RemoveSpaceTrim)"
+		tr -s " " | RemoveSpaceTrim | cut -d" " -f2- | BackToForwardSlash)"
 }
 
 getMountDir()
@@ -574,8 +589,8 @@ getMountDir()
 	local dir
 
 	if isDriveLetter "$device"; then
-		if IsPlatform wsl1; then
-			dir="$(findmnt --list --output=TARGET,SOURCE | grep -i "^/mnt/$device " | tr -s " " | cut -d" " -f2)"
+		if IsPlatform wsl1; then			
+			dir="$(findmnt --noheadings "$device:" --output=TARGET)"
 		else
 			dir="$(findmnt --list --output=TARGET,OPTIONS | grep -iE "path=$device"':?\\?' | cut -d" " -f1)"
 		fi
@@ -634,6 +649,12 @@ isRemovable()
 	isDriveLetter "$device" && { fsutil.exe fsinfo driveType "${drive}:\\" |& grep -q "Removable Drive"; return; }
 	[[ "$(lsblk --nodeps --noheadings --output RM "/dev/$device")" == "1" ]] && return
 	udevadm info --query=property --export --name="/dev/$device" | grep "ID_BUS='usb'" >& /dev/null && return
+	return 1
+}
+
+isOptical()
+{
+	isDriveLetter "$device" && { fsutil.exe fsinfo driveType "${device}:\\" |& grep -q "CD-ROM Drive"; return; }
 	return 1
 }
 
