hashi cert: enhancements

diff --git a/hashi b/hashi
--- a/hashi
+++ b/hashi
@@ -459,18 +459,29 @@ appVerify()
 
 certUsage()
 {
-	ScriptUsageEcho "Usage: $(ScriptName) cert copy|make|status
+	ScriptUsageEcho "Usage: $(ScriptName) cert copy|dir|info|make|status
 
 	copy		copy public certificates
 	make		make certificates
 	status	show certificate status
 
-	$certOptUsage"
+	$certOptUsage\n\n$(certInfoText)"
 }
 
 certArgStart() { unset -v forceCert noEncrypt; encrypt="true"; }
 certOpt() { encryptOpt "$@"; }
 certCommand() { usage; }
+
+certInfoCommand() { certInfoText; }
+certInfoText()
+{
+	EchoWrap "\
+Certification locations:
+  local - the local certificate directory for command line clients and services, i.e. /opt/PRODUCT/cert/
+  private - the root private certificate directory from the --encrypt option or certificateDir configuration
+  public - public certificate directory on the installation share"
+}
+
 
 #
 # cert copy commands
@@ -519,6 +530,31 @@ certCopyPublic()
 }
 
 #
+# cert dir commands
+#
+
+certDirUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert dir local|private|public\nReturn certificate directories"; }
+certDirCommand() { usage; }
+
+certDirLocalUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert dir local $productUsage\nReturn local certificate directory for a HashiCorp product"; }
+certDirLocalCommand() { usage; }
+certDirLocalConsulCommand() { certDirLocal "consul"; }
+certDirLocalNomadCommand() { certDirLocal "nomad"; }
+certDirLocalVaultCommand() { certDirLocal "vault"; }
+
+certDirPublicUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert dir public [$productUsage] $productUsage\nReturn public certificate directory"; }
+certDirPublicCommand() { certDirPublicSuffix; }
+certDirPublicConsulCommand() { certDirPublicSuffix "consul"; }
+certDirPublicNomadCommand() { certDirPublicSuffix "nomad"; }
+certDirPublicVaultCommand() { certDirPublicSuffix "vault"; }
+
+certDirPrivateUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert dir private [$productUsage] $productUsage\nReturn private certificate directory"; }
+certDirPrivateCommand() { certDirPrivate; }
+certDirPrivateConsulCommand() { certDirPrivateSuffix "consul"; }
+certDirPrivateNomadCommand() { certDirPrivateSuffix "nomad"; }
+certDirPrivateVaultCommand() { certDirPrivateSuffix "vault"; }
+
+#
 # certificate make commands
 #
 
@@ -540,13 +576,14 @@ certMakeConsulCommand() { certMake "consul"; }
 certMakeConsul() { cliValidate "consul" && certMakeCa && certMakeCli && certMakeConsulCaAuto; }
 
 certMakeConsulCa-autoUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make consul ca-auto\nget the Consul auto ca certificates.\n\n  $certOptUsage"; }
-certMakeConsulCa-autoCommand() { certMakeConsulCaAuto; }
+certMakeConsulCa-autoCommand() { certMake "consul" "CaAuto"; }
 
 certMakeConsulCaUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make consul ca\nCreate Consul ca certificates.\n\n  $certOptUsage"; }
-certMakeConsulCaCommand() { certMakeCa; }
+certMakeConsulCaCommand() { certMake "consul" "ca"; }
 
 certMakeConsulCliUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make consul cli\nCreate Consul CLI certificates.\n\n  $certOptUsage"; }
-certMakeConsulCliCommand() { certMakeCli; }
+certMakeConsulCliCommand() { certMake "consul" "cli"; }
+certMakeConsulCli() { certMakeCli; }
 
 certMakeConsulServerCommand() { forAllHosts certMakeConsulServer; }
 certMakeConsulServer() { certMakeServer "consul" "$@" "$(certMakeDnsArgs "consul")"; }
@@ -579,16 +616,17 @@ certMakeConsulCaAuto()
 certMakeNomadCommand() { certMake "nomad"; }
 
 certMakeNomadUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make nomad [ca|cli|client|server](all)\nCreate certificates required for Nomad.\n\n  $certOptUsage"; }
-certMakeNomadCommand() { certMakeNomadCa && certMakeNomadServer && certMakeNomadClient && certMakeNomadCli; }
+certMakeNomadCommand() { certMake "nomad"; }
+certMakeNomad() { certMakeNomadCa && certMakeNomadServer && certMakeNomadClient && certMakeNomadCli; }
 
 certMakeNomadCaUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make nomad ca\nCreate Nomad ca certificates.\n\n  $certOptUsage"; }
-certMakeNomadCaCommand() { certMakeNomadCa; }
+certMakeNomadCaCommand() { certMake "nomad" "ca"; }
 
 certMakeNomadCliUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make nomad cli\nCreate Nomad CLI certificates.\n\n  $certOptUsage"; }
-certMakeNomadCliCommand() { certMakeNomadCli; }
+certMakeNomadCliCommand() { certMake "nomad" "cli"; }
 
 certMakeNomadClientUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make nomad client\nCreate Nomad client certificates.\n\n  $certOptUsage"; }
-certMakeNomadClientCommand() { certMakeNomadClient; }
+certMakeNomadClientCommand() { certMake "nomad" "client"; }
 
 certMakeNomadServerUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make nomad server\nCreate Nomad server certificates.  Updates nomad-server-key.pem and nomad-server.pem.  Useful if the Nomad server DNS names change.\n\n  $certOptUsage"; }
 certMakeNomadServerCommand() { local hosts; getHosts "${hostArg:-servers}" && hostJoinInit "${hosts[@]}" && certMakeNomadServer; }
@@ -664,10 +702,11 @@ certMakeVaultCommand() { certMake "vault"; }
 certMakeVault() { cliValidate "vault" && certMakeCa && certMakeCli; }
 
 certMakeVaultCaUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make vault ca\nCreate Vault ca certificates.\n\n  $certOptUsage"; }
-certMakeVaultCaCommand() { certMakeCa; }
+certMakeVaultCaCommand() { certMake "vault" "ca"; }
 
 certMakeVaultCliUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make vault cli\nCreate Vault CLI certificates.\n\n  $certOptUsage"; }
-certMakeVaultCliCommand() { certMakeCli; }
+certMakeVaultCliCommand() { certMake "vault" "cli"; }
+certMakeVaultCli() { certMakeCli; }
 
 certMakeVaultServerUsage() { ScriptUsageEcho "Usage: $(ScriptName) cert make vault cli\nCreate Vault server certificates.\n\n  $certOptUsage"; }
 certMakeVaultServerCommand() { forAllHosts certMakeVaultServer; }
@@ -680,8 +719,9 @@ certMakeVaultServer() { certMakeServer "vault" "$@" "$(certMakeDnsArgs "vault,ac
 # certMake PRODUCT - make certificates for the product.  All of the following certMake functions are should only be called from certMake.
 certMake()
 {	
-	local product="$1"; certMakeCd "$product" || return
-	RunFunction "cert" "Make${product^}" || return
+	local product="$1" suffix="${2^}"; [[ $suffix ]] && shift
+	certMakeCd "$product" || return
+	RunFunction "cert" "Make${product^}$suffix" || return
 }
 
 certMakeCa()
@@ -815,46 +855,46 @@ certMakeServer()
 
 certStatusUsage()
 {
-	EchoWrap "Usage: $(ScriptName) cert status
+	EchoWrap "Usage: $(ScriptName) cert status [local|private|public](local) $productUsage
 Show certificate status.
 
-	-P,	--private		show private certificate status by mounting the private certificate directory
-	-p,	--public		show public certificate status by mounting the public certificate directory
+	-d, --detailed 	show detailed certificate information
+			--dump 			dump all certificate information"
+}
 
-Certification locations:
-  local - certificate directory for command line clients (i.e. /opt/hashi/certificate/DOMAIN[/CONFIG_PREFIX]/PRODUCT or /opt/PRODUCT/cert)
-  service - certificate directory for services (i.e. /opt/PRODUCT/cert/)
-  private - the root private certificate directory from the --encrypt option or certificateDir configuration
-  public - public certificate directory on the installation share"; }
-
-certStatusArgStart() { unset private public; }
+certStatusArgStart() { unset -v detail dump; }
 
 certStatusOpt()
 {
 	case "$1" in
-		-P|--private) private="true";;
-		-p|--public) public="true";;
+		--detail|-d) detail="--detail";;
+		--dump) dump="--dump";;
 		*) return 1;;
 	esac
 }
 
-certStatusCommand() { certStatus; }
+certStatusCommand() { usage; }
+certStatusConsulCommand() { certStatusLocal "consul"; }
+certStatusNomadCommand() { certStatusLocal "nomad"; }
+certStatusVaultCommand() { certStatusLocal "vault"; }
 
-certStatus() { certStatusConsul && certStatusNomad && certStatusVault && certStatusPublic && certStatusPrivate; }
-certStatusConsul() { certStatusProduct "consul"; }
-certStatusNomad() { certStatusProduct "nomad"; }
-certStatusVault() { certStatusProduct "vault"; }
 
-certStatusShow()
-{
-	local desc="$1" dir="$2"
-	header "$desc Certificates"
-	hilight "location: $(FileToDesc "$dir")"
-	command cd "$dir" && tree -L 2 --prune --noreport
-	echo
-}
+certStatusLocalCommand() { usage; }
+certStatusLocalConsulCommand() { certStatusLocal "consul"; }
+certStatusLocalNomadCommand() { certStatusLocal "nomad"; }
+certStatusLocalVaultCommand() { certStatusLocal "vault"; }
 
-certStatusProduct()
+certStatusPrivateCommand() { usage; }
+certStatusPrivateConsulCommand() { certStatusPrivate "consul"; }
+certStatusPrivateNomadCommand() { certStatusPrivate "nomad"; }
+certStatusPrivateVaultCommand() { certStatusPrivate "vault"; }
+
+certStatusPublicCommand() { usage; }
+certStatusPublicConsulCommand() { certStatusPublic "consul"; }
+certStatusPublicNomadCommand() { certStatusPublic "nomad"; }
+certStatusPublicVaultCommand() { certStatusPublic "vault"; }
+
+certStatusLocal()
 {
 	local product="$1"
 
@@ -862,29 +902,74 @@ certStatusProduct()
 	initConfig "$product" || return
 	certInit "$product" || return
 
-	# service
-	if [[ -d "$certDirService" ]]; then
-		certStatusShow "$(UpperCaseFirst "$product") Service" "$certDirService" || return
-	fi
+	# validate
+	[[ ! -d "$certDirService" ]] && { ScriptErr "the local $product certificate directory '$certDirService' does not exist"; return; }
 
-	local certDirLocal="$(certDirLocal "$product")" || return
-	if [[ "$certDirLocal" != "$certDirService" && -d "$certDirLocal" ]]; then
-		certStatusShow "$(UpperCaseFirst "$product") CLI" "$certDirLocal" || return
-	fi
+	# show
+	certStatusShow "$(UpperCaseFirst "$product") Local" "$certDirService"
 }
 
-# certStatusPublic - show status for the public certificate directory on the installation file server
-certStatusPublic()
-{
-	[[ ! $public ]] && return
-	local dir; dir="$(certDirPublicSuffix "")" && certStatusShow "Public" "$dir"
-}
-
-# certStatusPrivate - show status for the private certificate directory on the encrypted volume
 certStatusPrivate()
 {
-	[[ ! $private ]] && return
-	local dir; dir="$(certDirPrivate | certDirSuffix "")" && certStatusShow "Private" "$dir"
+	local product="$1" dir
+	dir="$(certDirPrivate | certDirSuffix "$product")" && certStatusShow "$(UpperCaseFirst "$product") Private" "$dir"
+}
+
+certStatusPublic()
+{
+	local product="$1" dir
+	dir="$(certDirPublicSuffix "$product")" && certStatusShow "$(UpperCaseFirst "$product") Public" "$dir"
+}
+
+# certStatusShow DESC DIR - show detailed information for all certificates in dir
+certStatusShow()
+{
+	local desc="$1" dir="$2"
+	header "$desc Certificates"
+	hilight "location: $(FileToDesc "$dir")"
+	( command cd "$dir" && tree -L 2 --prune --noreport; )
+	echo
+
+	# detail
+	if [[ $detail || $dump ]]; then
+		local files=(); IFS=$'\n' ArrayMake files "$(FindFile "$dir" "*" 3 | sort)";
+		for file in "${files[@]}"; do
+			local name="$(GetFileName "$file")"
+			[[ "$name" =~ key || "$(GetFileExtension "$name")" == @(csr|json) ]] && continue
+
+			hilight "$name:"
+
+			# dates
+			local to; to="$(CertGetDates "$file" | ${G}grep  "After" | ${G}cut -d":" -f2- | RemoveSpaceTrim)" || return
+			local toSeconds; toSeconds="$(GetSeconds  --no-ns "$to")"			
+			local seconds; seconds="$(GetSeconds --no-ns)"
+			local expired=""; (( toSeconds <= seconds )) && expired=" (${RED}expired${RESET})"
+			to="$(${G}date -d "$to" +"%m/%d/%Y")" || return
+			echo "	expires: $to$expired"
+			log2 "to=$to seconds=$seconds toSeconds=$toSeconds expired=$expired"
+
+			# key
+			local key="$(CertKeyFind "$file")"
+			printf "	key    : "
+			if [[ -f "$key" ]]; then
+				CertKeyVerify "$file" "$key" && echo "valid" || echo "${RED}invalid${RESET}"
+			else
+				echo "${RED}not present${RESET}"
+			fi
+
+			echo
+		done
+
+	fi
+
+	# dump
+	[[ ! $dump ]] && return
+	for file in "${files[@]}"; do
+		[[ "$file" =~ key ]] && continue
+		hilight "$(GetFileName "$file") dump..."
+		CertView "$file" || return
+	done
+
 }
 
 #
@@ -4219,7 +4304,7 @@ certDirLocal()
 	local dir="$(certDirSuffix "$product" "/opt/hashi")"
 
 	if [[ -d "$dir" ]]; then echo "$dir"
-	elif [[ -d "$(certDirService "$product")" ]]; then echo "$(certDirService "$product")"
+	elif dir="$(certDirService "$product")" && [[ -d "$dir" ]]; then echo "$dir"
 	else ScriptErrQuiet "unable to find the $product local certificate directory '/opt/hashi/certificate' or '/opt/$product/cert'"
 	fi
 }
@@ -4255,13 +4340,21 @@ certDirPrivate()
 }
 
 # certDirPrivateSuffix PRODUCT - add certificate suffix to the private certificate directory
-certDirPrivateSuffix() { local product="$1" dir; dir="$(certDirPrivate)" && certDirSuffix "$product" "$dir"; }
+certDirPrivateSuffix()
+{
+	local product="$1" dir
+	dir="$(certDirPrivate)" && certDirSuffix "$product" "$dir"
+}
 
 # certDirPublic - return the public certificate directory from an installation file server
 certDirPublic() { findInstallFile --quiet "other/HashiCorp"; }
 
 # certDirPublicSuffix PRODUCT - add certificate suffix to the public certificate directory
-certDirPublicSuffix() { local product="$1" dir; dir="$(certDirPublic)" && certDirSuffix "$product" "$dir"; }
+certDirPublicSuffix()
+{
+	local product="$1" dir
+	dir="$(certDirPublic)" && certDirSuffix "$product" "$dir"
+}
 
 # certDirService PRODUCT - return the product service certificate directory
 certDirService() { echo "/opt/$1/cert"; }
@@ -4269,8 +4362,9 @@ certDirService() { echo "/opt/$1/cert"; }
 # certDirSuffix PRODUCT DIR - add certificate suffix to DIR: DIR/certificate/DOMAIN[/CONFIG_PREFIX]/PRODUCT
 certDirSuffix()
 { 
-	local product="$1"; shift; 	GetArgs; [[ ! $1 ]] && { ScriptErrQuiet "certDirSuffix: directory not specified"; return 1; }
-	getDomainBase > /dev/null && echo "$(RemoveTrailingSlash "$1")/certificate/${domainBase}$(RemoveTrailingSlash "/$configPrefix")/$product"
+	local product="$1"; shift; GetArgs
+	local dir="$1"; [[ ! $dir ]] && { ScriptErrQuiet "certDirSuffix: directory not specified"; return 1; }
+	getDomainBase > /dev/null && echo "$(RemoveTrailingSlash "$dir")/certificate/${domainBase}$(RemoveTrailingSlash "/$configPrefix")/$product"
 }
 
 # certDirUnmountPrivate - unmount the private certificate directory if mounted.  Directory is changed in case we are in the private certificate directory.
@@ -4284,10 +4378,10 @@ certDirUnmountPrivate()
 certExists()
 {	
 	[[ $forceCert ]] && return 1
+	local dir="$PWD"; [[ -d "$1" ]] && { dir="$1"; shift; }
 
-	local file dir="$PWD"; [[ -d "$1" ]] && { dir="$1"; shift; }
-
-	for file in "$@"; do
+	local file files="$@"
+	for file in "${files[@]}"; do
 		[[ ! -f "$dir/$file" ]] && return 1
 	done
 
