HashiCertFix: updates

diff --git a/HashiCertFix b/HashiCertFix
--- a/HashiCertFix
+++ b/HashiCertFix
@@ -2,7 +2,8 @@
 . "${BASH_SOURCE[0]%/*}/function.sh" script color || exit
 
 # to do
-# - off hosts
+# /opt/hashi/certificates - what used for? need to update?
+# - off hosts - update certs
 
 # improvement
 # /opt/consul|nomad|vault permissions, especially cert dir
@@ -10,7 +11,10 @@
 product="consul"
 cd "$(encrypt mount "$CLOUD/data/app/CryFS/personal" "$@")/data/hashi/certificate/butare.net/$product" || return
 dir="/opt/$product/cert"
+servers=(pi1 pi2 pi3 pi4 pi5)
+servers=()
 hosts=(pi1 pi2 pi3 pi4 pi5 pi9 rp1 rp2 rp3 rp4 bl3 bl4)
+hosts=(rp2 rp3 rp4)
 
 #
 # ca
@@ -18,39 +22,56 @@ hosts=(pi1 pi2 pi3 pi4 pi5 pi9 rp1 rp2 rp3 rp4 bl3 bl4)
 
 # hashi cert make $product ca || return
 f="$dir/$product-ca.pem"
-hosts=()
 for h in "${hosts[@]}"; do
 	header "$product ca ($h)"
 	scp "$product-ca.pem" "$h:/tmp" || exit
 	SshHelper connect --function -i -t $h -- "	
 		sudoc mv /tmp/$product-ca.pem $f || exit
-		sudoc chown $product $f || exit
-		sudoc chmod -x $dir/* || exit"
+		sudoc chown $product:$product $f || exit
+		sudoc chmod 644 $f || exit # rw-rw-r--" || exit
 done
 
 #
 # server
 #
 
-hosts=(pi1 pi2 pi3 pi4 pi5)
-hosts=()
-for h in "${hosts[@]}"; do
+for h in "${servers[@]}"; do
 	header "$product server ($h)"
 	hashi cert make $product server -H=$h || return
 	scp $product-server-$h.pem $h:/tmp/$product-server.pem || exit
 	scp $product-server-$h-key.pem $h:/tmp/$product-server-key.pem || exit
 	SshHelper connect --function -i -t $h -- "
 		sudoc mv /tmp/$product-server* $dir || exit
-		sudoc chown $product $dir/* || exit
-		sudoc chgrp $product $dir/* || exit
-		sudoc chmod -x $dir/* || exit
-		sudoc chmod o-r $dir/* || exit
-		sudoc chmod ug+wr $dir/* || exit
-	" || exit
+		sudoc chown $product:$product $dir/$product-server* || exit
+		sudoc chmod 660 $dir/$product-server* || exit # rw-rw----" || exit
 done
 
 #
 # cli
 #
 
-hashi cert make $product cli || exit
+# hashi cert make $product cli || exit
+
+for h in "${hosts[@]}"; do
+	header "$product cli ($h)"
+	scp "$product-cli.pem" "$h:/tmp" || exit
+	scp "$product-cli-key.pem" "$h:/tmp" || exit
+	SshHelper connect --function -i -t $h -- "	
+		sudoc mv /tmp/$product-cli* $dir || exit
+		sudoc chown $product:$product $dir || exit
+		sudoc chmod 644 $f || exit # rw-rw-r--" || exit
+done
+
+#
+# cleanup
+#
+
+for h in "${hosts[@]}"; do
+	header "$product cleanup ($h)"
+	SshHelper connect --function -i -t $h -- "	
+		sudoc rm -fr /opt/hashi || exit
+		service restart $product || exit"
+done
+
+# hashi cert copy $product || exit
+# hashi cert status public $product || exit
