hashi: add remove command

diff --git a/hashi b/hashi
--- a/hashi
+++ b/hashi
@@ -1099,7 +1099,7 @@ configStatusCommand()
 # consul command
 #
 
-consulUsage() { ScriptUsageEcho "Usage: $(ScriptName) consul acl|agent|api|backup|environment|reload|restore|service|status\nConsul commands."; }
+consulUsage() { ScriptUsageEcho "Usage: $(ScriptName) consul acl|agent|api|backup|environment|reload|remove|restore|service|status\nConsul commands."; }
 consulArgStart() { product="consul"; }
 consulCommand() { usage; }
 consulEnvironmentCommand() { productEnvironment "$product"; }
@@ -1114,6 +1114,20 @@ consulBackupCommand()
 }
 
 consulReloadDo() { productInit "consul" "$1" && consul reload; }
+
+consulRemoveUsage() { ScriptUsageEcho "Usage: $(ScriptName) consul remove failed\nConsul remove commands."; }
+consulRemoveCommand() { usage; }
+
+consulRemoveFailedUsage() { ScriptUsageEcho "Usage: $(ScriptName) consul remove failed\nRemove failed nodes."; }
+
+consulRemoveFailedCommand()
+{ 
+	local host hosts; IFS=$'\n' ArrayMake hosts "$(consul members -status=failed | tail -n +2 | cut -d" " -f1)" || return
+	for host in "${hosts[@]}"; do
+		echo "Removing failed member '$host'..."
+		consul force-leave "$host" || return
+	done
+}
 
 #
 # consul acl command
