HostUpdate: add cleanup

diff --git a/HostUpdate b/HostUpdate
--- a/HostUpdate
+++ b/HostUpdate
@@ -23,11 +23,11 @@ File synchronization:
 init()
 {	
 	defaultCommand="update"	
-	defaultItems=( adobe choco motd npm node obsidian os python ruby store zsh)
+	defaultItems=( adobe choco motd npm node obsidian os python ruby store zsh )
 	defaultButareItems=( apps pool-controller pool-dash-panel pool-temperature )
 	defaultSandiaItems=( apps )
 	serverItems=( server server-credential server-eligibility server-root-user )
-	otherItems=( apps download file git public-files debian fzf hass intel mac micro opkg pool-controller pool-dash-panel pool-temperature windows wsl ${serverItems[@]} )
+	otherItems=( apps cleanup download file git public-files debian fzf hass intel mac micro opkg pool-controller pool-dash-panel pool-temperature windows wsl ${serverItems[@]} )
 	allItems=( "${defaultItems[@]}" "${otherItems[@]}" )
 	ohMyZsh="$HOME/.oh-my-zsh"
 }
@@ -98,13 +98,19 @@ clientCommand()
 	local networkCurrent="$(NetworkCurrent)"
 
 	# determine what to update
-	[[ ! $what ]] && default="true" what=( "${defaultItems[@]}" )
-	local defaultNetworkItems=()
-	if [[ $default && $networkCurrent ]]; then
-		ArrayCopy "default${networkCurrent^}Items" defaultNetworkItems
-	 	what+=( "${defaultNetworkItems[@]}" )
-	 	[[ "$networkCurrent" != "external" ]] && what=( git "${what[@]}" )
-	 fi
+	if [[ ! $what ]] && default="true"; then
+		what=( "${defaultItems[@]}" )
+
+		local defaultNetworkItems=()
+		if [[ $default && $networkCurrent ]]; then
+			ArrayCopy "default${networkCurrent^}Items" defaultNetworkItems
+		 	what+=( "${defaultNetworkItems[@]}" )
+		 	[[ "$networkCurrent" != "external" ]] && what=( git "${what[@]}" )
+		 fi
+
+		 what+=( "cleanup" )
+
+	fi
 
 	# update
 	for item in "${what[@]}"; do
@@ -226,6 +232,19 @@ chocoUpdate()
 	! UpdateNeeded "update-choco" && return
 	elevate choco.exe upgrade chocolatey
 	UpdateDone "update-choco" || return
+}
+
+#
+# Cleanup Update
+#
+
+cleanupInstalled() { true; }
+
+cleanupUpdate()
+{ 
+	! UpdateNeeded "update-cleanup" && return
+	inst --no-prompt install GameIcon IconCleanup final"${globalArgs}";
+	UpdateDone "update-cleanup" || return
 }
 
 #
