host update -w=node: only update if needed

diff --git a/HostUpdate b/HostUpdate
--- a/HostUpdate
+++ b/HostUpdate
@@ -327,8 +327,24 @@ nodeInstalled() { which node >& /dev/null; }
 nodeUpdate()
 {
 	{ ! nodeInstalled || ! UpdateNeeded "update-node"; } && return
-	sudoc rm -fr "/usr/local/lib/node_modules/.bin" || return # cleanup
-	sudoc npm install --location=global npm@latest && sudo npm update --location=global && UpdateDone "update-node"
+
+	# cleanup
+	sudoc rm -fr "/usr/local/lib/node_modules/.bin" || return
+
+	# update node to latest lts
+	if [[ "$(AppVersion node)" != "$(n --lts)" ]]; then
+		sudoc n lts || return
+		sudoc n prune || return
+	fi
+
+	# update npm
+	local outdated; outdated="$(npm outdated --location=global)" || return
+	echo "$outdated" | grep --quiet '^npm ' && { sudoc npm install --location=global npm@latest || return; }
+
+	# update other packages
+	[[ $(npm outdated --location=global) ]] && { sudoc npm update --location=global || return; }
+	
+	UpdateDone "update-node"
 }
 
 #
