HostCleanup: enhancements - add caching - add additional file cleanup

diff --git a/HostCleanup b/HostCleanup
--- a/HostCleanup
+++ b/HostCleanup
@@ -55,7 +55,9 @@ cleanupCommand()
 
 	for item in "${what[@]}"; do
 		IsInArray "$item" skip && continue
-		"cleanup${item^}" || { log1 "error cleaning $item"; (( ++errors )); }
+		local cache="host-cleanup-$item"; ! UpdateNeeded "$cache" && continue
+		"cleanup${item^}" || { log1 "error cleaning $item"; (( ++errors )); continue; }
+		UpdateDone "$cache" || return
 	done
 
 	return "$errors"
@@ -96,13 +98,21 @@ cleanupDocker()
 
 # files
 cleanupFiles() { hilightp "cleaning files..." && cleanupFilesTmp && RunPlatform cleanupFiles && hilight "done"; }
-cleanupFilesTmp() { ! IsPlatform mac && [[ -d "$TMP" ]] && rm -fr "$TMP/"*; hilightp "."; }
+
+cleanupFilesTmp()
+{
+	local t
+	t="$TMP"; ! IsPlatform mac && [[ -d "$t" ]] && { rm -fr "$t/"* >& /dev/null; hilightp "."; }
+	t="/tmp"; [[ "$TMP" != "$t" && -d "$t" ]] && { rm -fr "$t/bootstrap/"* >& /dev/null; hilightp "."; }
+	t="$(PlatformTmp)"; [[ -d "$t" ]] && { rm -fr "$t/"* >& /dev/null; hilightp "."; }
+	return 0
+}
 
 cleanupFilesWin()
 {
-	[[ -d "$UADATA/Temp" ]] && { log1 "$UADATA/Temp..."; rm -fr "$UADATA/Temp/"* >& /dev/null; echo -n "."; }
-	[[ -d "$WIN_ROOT/temp" ]] && { log1 "$WIN_ROOT/temp..."; rm -fr "$WIN_ROOT/temp/"* >& /dev/null; echo -n "."; }
-	[[ -d "$WINDIR/Temp" ]] && { log1 "$WINDIR/Temp"; rm -fr "$WINDIR/Temp/"* >& /dev/null; echo -n "."; }
+	[[ -d "$UADATA/Temp" ]] && { log1 "$UADATA/Temp..."; rm -fr "$UADATA/Temp/"* >& /dev/null; hilightp "."; }
+	[[ -d "$WIN_ROOT/temp" ]] && { log1 "$WIN_ROOT/temp..."; rm -fr "$WIN_ROOT/temp/"* >& /dev/null; hilightp "."; }
+	[[ -d "$WINDIR/Temp" ]] && { log1 "$WINDIR/Temp"; rm -fr "$WINDIR/Temp/"* >& /dev/null; hilightp "."; }
 	return 0
 }
 
