mac ARM updates

diff --git a/HostUpdate b/HostUpdate
--- a/HostUpdate
+++ b/HostUpdate
@@ -112,11 +112,13 @@ UpdateMac()
 
 brewUpdate()
 {
+	local status
+
 	! UpdateNeeded "brew" && return
-	brew doctor || return
+	brew doctor; status="$?"; ! IsPlatform arm && (( status != 0 )) && return "$status"; # brew doctor on arm always returns failure
 	brew update || return
 	brew upgrade || return
-	brew cask upgrade || return
+	brew upgrade --cask || return
 	UpdateDone "brew" || return
 }
 
@@ -261,7 +263,7 @@ pythonUpdate()
 rubyInstalled() { which gem >& /dev/null; }
 rubyUpdate()
 {	
-	! rubyInstalled && return
+	{ ! rubyInstalled || IsPlatformAll mac,arm; } && return # gem is not functional on mac ARM
 
 	local sudo="sudoc"; InPath rvm && unset sudo
 	local args=( --no-document ) # documents take a while to install
