hyperv: add clone command

diff --git a/hyperv b/hyperv
--- a/hyperv
+++ b/hyperv
@@ -4,18 +4,21 @@
 usage()
 {
 	ScriptUsage "$1" "\
-Usage: $(ScriptName) [OPTION]... hypervisor|ls|start
+Usage: $(ScriptName) [OPTION]... [gui|hypervisor|ls|start|status](gui)
 Hyper-V commands.
 	
-	checkpoint|connect|create|drive|exists|power|rm		VM commands"
+	checkpoint|clone|connect|create|drive|exists|power|rm		VM commands"
 }
 
 init()
 { 
 	defaultCommand="gui"
 	gui="virtmgmt.msc"
-	isoDir="$DATA/appdataw/iso" 
-	disks="$DATA/appdataw/Hyper-V/Virtual Hard Disks"
+
+	root="$DATA/appdataw"
+	isoDir="$root/iso"; [[ ! -d "$isoDir" ]] && { mkdir --parents "$isoDir" || return; }
+	diskDir="$DATA/appdataw/Hyper-V/Virtual Hard Disks"
+
 	controller="2" # assume controller location 2, 0 is usually a DVD drive and 1 is usually the system hard drive
 	allHelp="-a, 	--all				operate on all virtual machines"
 }
@@ -24,9 +27,13 @@ existsUsage() { echot "Usage: $(ScriptName) exists VM\nReturn true if the virtua
 existsArgs() { getVmArg "$@"; }
 existsCommand() { psRaw 'Get-VM | where {\$_.Name -eq \"'$vm'\"}' | grep "$vm" >& /dev/null; }
 
-lsUsage() { echot "Usage: $(ScriptName) ls [plain]\nList all virtual machines."; }
-lsCommand() { RunScript --elevate "${globalArgs[@]}" -- powershell Get-VM; }
-lsPlainCommand() { lsCommand | RemoveCarriageReturn | tail +4 | cut -d" " -f 1 | grep -v '^$'; }
+lsUsage() { echot "Usage: $(ScriptName) ls\nList all virtual machines."; }
+
+lsCommand()
+{
+	[[ $verbose ]] && { powershell 'Get-VM'; return; }
+	powershell 'powershell Get-VM' | RemoveCarriageReturn | tail +4 | cut -d" " -f 1 | grep -v '^$'
+}
 
 checkpointUsage() { echot "Usage: $(ScriptName) checkpoint VM|all \nCheckpoint the virtual machines."; }
 checkpointArgs() { getVmArg "$@"; }
@@ -38,6 +45,13 @@ checkpointCommand()
 	else
 		ps 'Checkpoint-VM -Name \"'$vm'\"'
 	fi
+}
+
+guiCommand()
+{
+	! InPath "$gui" && { EchoErr "The Hyper-V management GUI is not installed"; }
+	WinList | grep "Hyper-V Manager" >& /dev/null && return 0
+	cd "/mnt/c"; start "$gui" "$@"
 }
 
 rmUsage() { echot "Usage: $(ScriptName) delete VM \nDelete the virtual machines."; }
@@ -53,12 +67,29 @@ rmCommand()
 	echo "done"
 }
 
-guiCommand()
+statusCommand()
 {
-	! InPath "$gui" && { EchoErr "The Hyper-V management GUI is not installed"; }
-	WinList | grep "Hyper-V Manager" >& /dev/null && return 0
-	cd "/mnt/c"; start "$gui" "$@"
+	ps "$(cat <<-EOF
+		\\\$v = Get-VMHost
+		\\\$vms = Get-VM
+
+		Write-Host ('name={0}' -f \\\$v.Name)
+		Write-Host ('total={0}' -f \\\$vms.count)
+    Write-Host ('running={0}' -f \\\$vms.where( {\\\$_.state -eq 'running'}).count)
+    Write-Host ('off={0}' -f \\\$vms.where( {\\\$_.state -eq 'off'}).count)
+    Write-Host ('saved={0}' -f \\\$vms.where( {\\\$_.state -eq 'Saved'}).count)
+    Write-Host ('paused={0}' -f \\\$vms.where( {\\\$_.state -eq 'Paused'}).count)
+    Write-Host ('other={0}' -f \\\$vms.where( {\\\$_.state -notmatch \"running|off|saved|Paused\"}).count)
+    Write-Host ''
+    Write-Host ('VirtualMachinePath={0}' -f \\\$v.VirtualMachinePath)
+    Write-Host ('VirtualHardDiskPath={0}' -f \\\$v.VirtualHardDiskPath)
+    Write-Host ('EnhancedSessionMode={0}' -f \\\$v.EnableEnhancedSessionMode)
+
+	EOF
+	)"
 }
+
+#Write-Host ('={0}' -f \\\$)
 
 #
 # config commands
@@ -121,6 +152,74 @@ configSwitch()
 	local vm="$1" switch="${2:-Default Switch}"
 	ps 'Get-VM -VMName \"'$vm'\" | Get-VMNetworkAdapter | Connect-VMNetworkAdapter -SwitchName \""'"$switch"'"\"'
 }
+
+#
+# Clone Command
+#
+
+
+cloneUsage() { echot "Usage: $(ScriptName) CLONE VM\nClone a virtual machine."; }
+cloneArgs() { getVmArg "$@"; }
+
+cloneCommand()
+{
+	local id; id="$(uuidgen)" || return
+	local exportDir="$WIN_ROOT/temp/$id"; mkdir --parents "$exportDir" || return
+	local result; cloneDo "$vm"; result="$?"
+
+	# cleanup
+	rm -fr "$exportDir"
+
+	# return
+	return "$result"
+}
+
+cloneDo()
+{
+	# find new name
+	printf "Finding clone name..."
+	local vmClone="$(cloneNewName "$vm")" || return
+	echo "$vmClone"
+
+	# export	
+	printf "Exporting '$vm'..."
+	powershell "Export-VM -Name "$vm" -Path '$(utw "$exportDir")'" || return
+	echo "done"
+
+	# find the exported vmcx file
+	local importFile; importFile="$(fd '.vmcx$' "$exportDir")" || return
+	[[ ! -f "$importFile" ]] && { ScriptErr "could not find the vmcx import file in '$exportDir'"; return 1; }
+
+	# import
+	local disk; disk="" || pause return
+	printf "Importing '$vm'..."
+	local vmId; vmId="$(powershell "(Import-VM -VhdDestinationPath '$(getDiskDir "$vmClone" "$id")' -Path '$(utw "$importFile")' -GenerateNewId -Copy).VMId.Guid")" || return
+	echo "done"
+	vmId="$(printf "$vmId" | RemoveCarriageReturn)"
+
+	# rename
+	powershell 'Get-VM | where {$_.VMId.Guid -eq "'$vmId'"} | Set-VM -NewVMName "'$vmClone'"' || return
+}
+
+# cloneNewName NAME - assume original name is <name><number> and increment new number until find a free name. 	
+cloneNewName()
+{
+	local vm="$1"
+
+	# prefix - the existing name without numeric suffix
+	local prefix; prefix="$(echo "$vm" | sed 's/[0-9]*$//')" || return 	
+
+	# suffix - the existing virtual machine number (the numeric suffix, or 1 if not present)
+	local n; n="$(echo "$vm" | sed "s/^$prefix//")" || return
+	[[ ! $n ]] && n="1"
+
+	# find a new name - start search 1 past the existing virtual machine numbner
+	(( n++ )) 
+	while true; do vm="$prefix$n"; log1 "checking name $vm"; ! existsCommand && break; (( ++n )); done
+	log1 "cloneNewName: vm=$vm"
+	echo "$vm"
+}
+
 
 #
 # Connect Commands
@@ -188,7 +287,8 @@ createCommand()
 	deleteVmDiskFiles || return
 
 	# variables
-	local disk="$(utw "$disks/$vm.vhdx")"
+	local id; id="$(uuidgen)" || return
+	local disk; disk="$(getDiskDir "$vm" "$id")\\$vm.vhdx"
 	local f="$(mktemp --suffix=.ps1 -p "$WINDIR/Temp")"
 	local hdGb="50" memoryGb="2" processors="2" secureBoot="Off" tpm="true" switch="Default Switch"
 	local nestedVirtualization="False"
@@ -424,10 +524,11 @@ driveUnmountCommand()
 #
 
 checkInstalled () { ! isInstalled && { EchoErr "Hyper-V is not installed"; exit 1; } }
-deleteVmDiskFiles() { rm -f "$disks/${vm}.vhdx" "$disks/${vm}_"*".avhdx"; }
+deleteVmDiskFiles() { rm -f "$diskDir/${vm}.vhdx" "$disks/${vm}_"*".avhdx"; }
+getDiskDir() { echo -E "$(utw "$diskDir")\\$1-$2"; } # getDiskDir VM ID
 listSwitch() { ps 'Get-VMSwitch' | tail +3 | cut -d" " -f 1; }
-ps() { RunScript --elevate "${globalArgs[@]}" -- powershell "$@"; }
-psRaw() { RunScript --elevate -- powershell "$@"; }
+ps() { RunScript --elevate "${globalArgs[@]}" -- powershell.exe "$@"; }
+psRaw() { RunScript --elevate -- powershell.exe "$@"; }
 
 getVmArg()
 {
