inst: new install fixes

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -101,6 +101,7 @@ installInit()
 		[brew]="HomeBrew"
 		[btt]="BetterTouchTool"
 		[bc]="BeyondCompare"
+		[bcc]="BeyondCompareConfig"
 		[cc]="CreativeCloud"
 		[cctray]="CruiseControlTray"
 		[ddm]="DellDisplayManager"
@@ -158,7 +159,7 @@ installInit()
 	mac=( amphetamine AppleConfigurator apptivate bartender bear BetterTouchTool btt CanaryMail CarrotWeather DayOne DiskInventortyX gitx HomeAssistant homie iTerm karabiner LiveDesktop Magnet MakrdownView MicrosoftRemoteDesktop pcalc rectagle RemoteDesktop spark speedtest SystemToolkit VmwareFusion WallpaperWizard xcode XcodeCli XQuartz yoink )
 	macDebian=( 1Password 1PasswordCli 7Zip asdf BalenaEtcher bat bc certbot chrony colorls DotNet Dropbox docker etcher exa fuse fzf ghq GitKraken gnupg gpg homebrew homebridge JetBrains JumpCloud MozillaVpn mysql NetbootxyzDocker pass passh PiDiskImager RpiBoot ruby RubyAsdf RubyPackage RubyRvm skype StandardNotes steam sublime SublimeMerge tmux thunderbird UnifiController unison VisualStudioCode vscode WireGuard xClient xServer xpra )
 	macWin=( BlueSherpa BrotherPrinter calibre CanonCamera CleanMy CrealitySlicer CreativeCloud cricut deezer DellDisplayManager domotz DreamAquarium DuetDisplay dymo fork garmin GreenShot iExplorer JumpDesktop keybase lazygit logitech LogitechGhub LogitechOptions notion nVidia office origin PdfElement plex PowerShell qvr sonos spotify SurveillanceStation VisualStudio VisualStudioCode WireShark xpra xServer zoom )
-	win=( ahk AjaSystemTest AutoHotKey AltTabTerminator AquaSnap backupper bonjourSdk chocolatey CloseAllWindows CoreTemp cpuz DiskImager EdgeDeflector FileLocatorPro game GitExtensions HiddenStart HiddenStartConfigure iCloud IntelDrivers IntelDriverUpdate kindle KindleDrm MaxTo NordVPN Ninite Notepadpp npp RightClickEnhancer TidyTabs UltraMon vcxsrv WinScp xMing AjaSystemTest BlueStacks CPUZ DiskImager hyperv HiddenStart intel IntelExtremeTuning IntelStorageManagement IntelThunderboltControlCenter java LgMonitor MarkdownView MicrosoftTeams MsiMotherboard NitroPdf nVidiaDriver nVidiaGeForceExperience OneDrive oculus pa PartitionAssistant pGina PowerPanel PowerrToys QuickBooks stamps SystemInternals TaskLayout TemperatureLogger Todoist UupDump VisualStudio vs Wallpaper4k WindowsAssessmentAndDeploymentKit wsl x410 xMing )
+	win=( ahk AjaSystemTest AutoHotKey AltTabTerminator AquaSnap backupper bonjourSdk chocolatey CloseAllWindows CoreTemp cpuz DiskImager EdgeDeflector FileLocatorPro game GitExtensions HiddenStart HiddenStartConfigure iCloud IntelDrivers IntelDriverUpdate kindle KindleDrm MaxTo NordVPN Ninite Notepadpp npp RightClickEnhancer TidyTabs UltraMon vcxsrv WinScp xMing AjaSystemTest BlueStacks CPUZ DiskImager hyperv HiddenStart intel IntelExtremeTuning IntelStorageManagement IntelThunderboltControlCenter java LgMonitor MarkdownView MicrosoftTeams MsiMotherboard NitroPdf nVidiaDriver nVidiaGeForceExperience OneDrive oculus pa PartitionAssistant pGina PowerPanel PowerrToys QuickBooks stamps SystemInternals TaskLayout TemperatureLogger Todoist UupDump VisualStudio vs Wallpaper4k WindowsAssessmentAndDeploymentKit wsl WslConfig x410 xMing )
 
 	# Apache
 	all+=( ApacheNomad )
@@ -168,7 +169,7 @@ installInit()
 	macDebian+=( chrome firefox tor )
 	
 	# File Comparison
-	macDebian+=( BeyondCompare delta )
+	macDebian+=( BeyondCompare BeyondCompareConfig delta )
 
 	# Go
 	macDebian+=( go cheat curlie )
@@ -404,8 +405,8 @@ i()
 
 		# run the app install
 		elif [[ ! $prompt ]] || ask "\nInstall $appFunction"; then
-			noHeader="$noHeaderArg" noPrompt="$noPromptArg" RunLog "${appFunction}Install" || return
-			noHeader="$noHeaderArg" noPrompt="$noPromptArg" RunLog RunPlatform "${appFunction}Final" || return
+			noHeader="$noHeaderArg" noPrompt="$noPromptArg" "${appFunction}Install" || return
+			noHeader="$noHeaderArg" noPrompt="$noPromptArg" RunPlatform "${appFunction}Final" || return
 
 		fi
 
@@ -490,7 +491,7 @@ run()
 		local shift=1
 		case "$1" in 
 			"") : ;;
-			--) shift; otherArgs+=( "$@" ); shift "$#"; break;;
+			--) shift; args+=( "$@" ); shift "$#"; break;;
 
 			--docker) type="docker"; [[ ! "$dest" ]] && dest="$SRV";;
 			--executable) type="executable";;
@@ -518,8 +519,7 @@ run()
 			--rename) rename="--rename" copyLocal="--copy-local";; # must copy for rename so we do not impact the original file
 
 			*)
-				if [[ "$1" == "--" ]]; then shift; args+=( "$@" ); shift "$#"; break
-				elif ! IsOption "$1" && [[ ! $p ]]; then p="$1"
+				if ! IsOption "$1" && [[ ! $p ]]; then p="$1"
 				else UnknownOption "$1"
 				fi
 		esac
@@ -699,7 +699,7 @@ runTypeExtension()
 	if ! IsElevated && [[ $elevate && ! $copyLocal ]] && IsPlatform wsl2; then
 		local installUnc="$(unc get unc --root "$INSTALL_DIR")"
 		log1 "installUnc=$installUnc"
-		local newInstallDir="$(RunScript --elevate $verbose -- unc mount "$installUnc")/documents/data/install" || return
+		local newInstallDir="$(RunScript --elevate "${globalArgs[@]}" -- unc mount "$installUnc")/documents/data/install" || return
 		p="${p/$INSTALL_DIR/$newInstallDir}"
 		log1 "newInstallDir=$installUnc p=${p}"
 	fi
@@ -1682,11 +1682,11 @@ BeyondCompareInstall()
 {
 	header "BeyondCompare"; local v=4.4.2.26348 # http://www.scootersoftware.com/download.php
 	BeyondCompare IsInstalled && [[ ! $force ]] && return
+	run "other/Scooter Software/Beyond Compare/setup/BCompare-${v}_x64.msi|BCompareOSX-${v}.zip|bcompare-${v}_amd64.deb" --elevate || return
+}
 
-	# install
-	run "other/Scooter Software/Beyond Compare/setup/BCompare-${v}_x64.msi|BCompareOSX-${v}.zip|bcompare-${v}_amd64.deb" || return
-
-	# configure
+BeyondCompareConfigInstall()
+{
 	echo "- Help|Preferences, Enter Key..."
 	IsPlatform mac && echo "- Beyond Compare, Install Command Line Tools…"
 	BeyondCompare $noPrompt profile restore default || return
@@ -1721,7 +1721,7 @@ DeltaInstall()
 DebianSetupInstall()
 {
 	header "Debian Setup"
-	i apt DebianDns DebianFileSharing DebianFonts DebianLocale DebianPolicies DebianProxyServer DebianSudoSecurePath homebrew || return
+	i apt DebianDns DebianFileSharing DebianFonts DebianLocale DebianPolicies DebianProxyServer DebianSudoSecurePath || return
 	DbusSetup || return
 }
 
@@ -4333,7 +4333,7 @@ GpingInstall()
 
 	if IsPlatform mac && [[ ! $force ]]; then package gping
 	elif IsPlatform arm && [[ ! $force ]]; then run --executable "shareware/gping" # https://github.com/orf/gping/releases
-	elif IsPlatformAll debian,brew && [[ ! $force ]]; then brew install "orf/brew/gping"
+	elif IsPlatformAll debian,brew && [[ ! $force ]]; then run --homebrew "orf/brew/gping"
 	else run --rust "gping"
 	fi
 }
@@ -5092,7 +5092,7 @@ WslConfigInstall()
 	$makeShortcut "wsl.exe" "$pp/Operating System/bash" || return
 
 	# startup script
-	registry set "run/startup" REG_SZ "$(utw "$UADATA//Microsoft/WindowsApps/bash.exe")"' -c \"/usr/local/data/bin/RunScript startup\"'
+	registry set "run/startup" REG_SZ "$(utw "$UADATA//Microsoft/WindowsApps/bash.exe")"' -c "/usr/local/data/bin/RunScript startup"'
 }
 
 wslSetUser() { wsl dist user set --user="$(ConfigGet "user")"; }
@@ -5229,7 +5229,7 @@ ProcsInstall()
 	InPath procs && [[ "$(procs --version | head -1 | cut -d" " -f 2)" == "$v" && ! $force ]] && return
 
 	# install
-	if IsPlatform mac && [[ "$installType" == @(|package) ]]; then brew install procs
+	if IsPlatform mac && [[ "$installType" == @(|package) ]]; then pkg procs
 	elif IsPlatform debian && [[ "$installType" == @(|local) ]]; then run --executable "shareware/procs" # built from source
 	elif [[ "$installType" == @(|compile) ]]; then run --rust "procs"
 	else couldNotLocate
@@ -6666,7 +6666,7 @@ WindowsTerminalInstall()
 
 	# install
 	if [[ "$installType" == @(|local) ]]; then
-		run "other/Microsoft/Windows/terminal/Microsoft.WindowsTerminalPreview_Win11_$v_$suffix.msixbundle" || return
+		run "other/Microsoft/Windows/terminal/Microsoft.WindowsTerminalPreview_Win11_${v}_${suffix}.msixbundle" || return
 	else
 		run --store "9N8G5RFZ9XK3" || return
 	fi
@@ -6749,6 +6749,7 @@ SublimeInstall()
 	local versionBeta="4131" 	# https://www.sublimetext.com/dev
 	local architecture="amd64"; IsPlatform arm && architecture="arm64" 
 	local alternate; [[ "$installType" == "alternate" ]] && alternate="--alternate"
+	local args=(); IsPlatform win && args+=('/VERYSILENT' '/TASKS="contextentry"')
 
 	# return if installed
 	[[ "$installType" == "beta" ]] && v="$versionBeta"
@@ -6756,7 +6757,7 @@ SublimeInstall()
 
 	# install
 	IsPlatform linux && [[ ! $installType ]] && installType="package" # Linux defaults to package
-	if [[ "$installType" == @(|beta|local) ]]; then run "other/Sublime/setup/sublime_text_build_${v}_x64_setup.exe|sublime_text_build_${v}_mac.zip|sublime-text_build-${v}_${architecture}.deb" || return
+	if [[ "$installType" == @(|beta|local) ]]; then run "other/Sublime/setup/sublime_text_build_${v}_x64_setup.exe|sublime_text_build_${v}_mac.zip|sublime-text_build-${v}_${architecture}.deb" --elevate -- "${args[@]}" || return
 	elif IsPlatform debian && [[ "$installType" == @(|alternate|package) ]]; then sublimePackage || return
 	else couldNotLocate
 	fi
@@ -6786,7 +6787,7 @@ SublimeFinalMac()
 SublimeFinalWin()
 {
 	registry delete "HKEY_CLASSES_ROOT/Applications/sublime_text.exe/" # enable Windows Open With
-	$mv "$pp/Sublime Text.lnk" "$pp/Applications/Sublime Text.lnk"
+	$mv "$pp/Sublime Text.lnk" "$pp/Applications" || return
 }
 
 VisualStudioCodeInstall()
@@ -7737,10 +7738,40 @@ WinInstall()
 {	
 	header "Windows Setup"
 	i WinPath SystemInternals || return # run first to minimize prompts
-	i WinPermissions WinDirectories WinFonts WinConsole WinConfiguration WslConfig OneDrive || return
+	i WinApps WinPermissions WinDirectories WinFonts WinConsole WinConfiguration WslConfig OneDrive || return
 }
 
 WinFinalWin() { WinIconsInstall; }
+
+WinAppsInstall()
+{
+	header "Windows Applications"
+	[[ ! $force ]] && ! UpdateNeeded "WinApps" && return
+
+	# find the applications for the current build
+	findFile "other/Microsoft/Windows/setup" || return
+	local build; build="$(os build)" || return
+	local dir="$file/$build/apps"
+	[[ ! -d "$dir" ]] && return
+
+	# copy applications
+	local dest="/mnt/c/temp"
+	mkdir --parents "$dest" || return
+	CopyDir  "$dir" "$dest/apps" --no-metadata --rsync || return # metadata is not needed and errors out on initial install
+
+	# install the applications
+	cd "$dest/apps" || return
+	local file
+	for file in *; do
+		[[ "$(GetFileExtension "$file")" == @(bat) ]] && continue
+		RunLog RunScript --elevate --no-hide -- cmd.exe /c dism.exe /Online /add-provisionedappxpackage /packagepath:$file /SkipLicense # some packages error out on re-install
+	done
+
+	# cleanup
+	cd ~; rm -fr "$dest/apps"
+
+	UpdateDone "WinApps"
+}
 
 WinConfigurationInstall()
 {
