UltraMon: add helper, enhance install

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -10500,15 +10500,16 @@ rectangleVersion() { curl --silent --location "https://rectangleapp.com" | ${G}g
 
 UltraMonInstall()
 {
-	local prefix="platform/win/UltraMon"
-	run --name "UltraMon" "$prefix/setup/UltraMon_3.4.1_en_x64.msi" || return # https://www.realtimesoft.com/ultramon/download.asp
+	local prefix="platform/win/UltraMon" v="3.4.1"
+	run --name "UltraMon" "$prefix/setup/UltraMon_$v_en_x64.msi" --version="$v" || return # https://www.realtimesoft.com/ultramon/download.asp
 	
-	# icons	
+	# return if icons copied
 	local dest="$P/UltraMon/icons" stage="$WIN_ROOT/temp/icons" result=1
 	[[ ! $force && -d "$dest/Leapo Windows 7" ]] && return	
-	echo "Copying icons..."
+
+	# copy icons
 	findFile "$prefix/icons" || return # https://www.realtimesoft.com/ultramon/addons.asp#Icons
-	CopyDir --recursive "$file" "$stage" && RunScript --elevate --wait --verbose -- CopyDir --recursive "$stage" "$dest" && result=0
+	CopyDir --recursive --rsync "$file" "$stage" && RunScript --elevate --wait --verbose -- CopyDir --recursive "$stage" "$dest" && result=0
 	rm -fr "$stage"; return $result
 }
 
@@ -10743,10 +10744,10 @@ windowsFont()
 {
 	local dir="$WIN_ROOT/temp/fonts"
 
-	# copy font
+	# copy font locally - fontreg.exe fails on network share in wsl 2
 	for file in "$@" "${otherArgs[@]}"; do
 		findFile "fonts/$file" || return
-		CopyDir "$file/" "$dir" || return # fontreg.exe fails on network share in wsl 2
+		CopyDir "$file/" "$dir" --rsync || return # use rsync - RoboCopy fails on fresh install
 	done
 
 	# install font
