inst: updates

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -168,8 +168,8 @@ installInit()
 	debian=(audacity bind cfssl chroot ChronyServer cron CronLog cups dbus DnsServer DhcpServer geany HypervLinuxTools kea KeaService LastPass mDns NodeRed pass SaltMinion GnomeKeyring SnapStore SystemUser terminator VmwareLinuxTools)
 	debian64=()
 	mac=(amphetamine AppleConfigurator AppleRemoteDesktop apptivate bartender bear BetterTouchTool btt CanaryMail CarrotWeather DayOne DiskInventortyX HomeAssistant iTerm KarabinerElements LiveDesktop Magnet MakrdownView MicrosoftRemoteDesktop pcalc rectagle spark speedtest SystemToolkit VmwareFusion WallpaperWizard xcode XcodeCli XQuartz yoink)
-	macDebian=(1Password 1PasswordCli 7Zip BalenaEtcher bat bc btop certbot chrony colorls DotNet Dropbox DropboxDownload docker etcher exa fuse fzf ghq gnupg gpg JetBrains mysql NetbootxyzDocker pass passh PiDiskImager RpiBoot ruby RubyAsdf RubyPackage RubyRvm StandardNotes steam sublime SublimeMerge tmux thunderbird unison VeraCrypt VisualStudioCode vscode xClient xServer xpra)
-	macWin=(BlueSherpa BrotherPrinter calibre CleanMyMac CreativeCloud cricut deezer  DreamAquarium DuetDisplay fork garmin GreenShot iExplorer keybase notion nVidia origin PdfElement plex quicken qvr slack sonos spotify SurveillanceStation VisualStudio VisualStudioExtensions VisualStudioCode xpra xServer zoom)
+	macDebian=(1Password 1PasswordCli 7Zip BalenaEtcher bat bc btop certbot chrony colorls DotNet Dropbox DropboxDownload docker etcher exa fuse fzf gcc ghq gnupg gpg JetBrains mysql NetbootxyzDocker pass passh PiDiskImager RpiBoot ruby RubyAsdf RubyPackage RubyRvm StandardNotes steam sublime SublimeMerge tmux thunderbird unison VeraCrypt VisualStudioCode vscode xClient xServer xpra)
+	macWin=(BlueSherpa BrotherPrinter calibre CleanMyMac CreativeCloud cricut deezer DreamAquarium DuetDisplay fork garmin GreenShot iExplorer keybase miro notion nVidia origin PdfElement plex quicken qvr slack sonos spotify SurveillanceStation VisualStudio VisualStudioExtensions VisualStudioCode xpra xServer zoom)
 	win=(ahk AjaSystemTest AutoHotKey AltTabTerminator backupper bonjourSdk CloseAllWindows CoreTemp cpuz DiskImager EdgeDeflector FileLocatorPro game GigabyteMotherboard HardwareMonitor HiddenStart HiddenStartConfigure Hp9020 iCloud kindle KindleDrm Notepadpp npp RightClickEnhancer TidyTabs vcxsrv WinScp xMing AjaSystemTest BlueStacks CPUZ DiskImager hyperv HiddenStart java LgMonitor MarkdownView NitroPdf nVidiaDriver nVidiaGeForceExperience OneDrive oculus pa PartitionAssistant pGina PowerPanel PowerrToys QuickBooks RealtekCardReader stamps SystemInternals TaskLayout TemperatureLogger Todoist UupDump Wallpaper4k wsl WslConfig x410 xMing)
 
 	# Apache
@@ -1992,7 +1992,7 @@ DevCoreAllInstall() { i DotNetCore GitCore JavaCore SqlCore WebCore; }
 DevLanguageAllInstall() { i gcc go haskell python ruby rust; }
 
 gccCheck() { InPath gcc make && return; i --no-header gcc; }
-GccInstall() {	run --package --header "gcc" gcc make; }
+GccInstall() { run --package --header "gcc" gcc && pkg make; }
 
 DevCoreInstall()
 {
@@ -2017,7 +2017,7 @@ GoInstall()
 	gccCheck || return
 
 	# platform
-	local version="1.18.3" dest="/usr/local" platform 
+	local version="1.19" dest="/usr/local" platform 
 	case "$(uname -m)" in "") : ;;
 		armv7l) platform="linux-armv6l";;
 		aarch64) platform="linux-arm64";;
@@ -4257,6 +4257,11 @@ NodeInstall()
 	hilight "Rebuilding packages..."
 	cd "$(sudo npm -g prefix)/lib/node_modules" || return
 	sudo npm rebuild --unsafe-perm || return
+
+	# cleanup
+	IsPlatform mac && brew list node &> /dev/null && { packageu node || return; }
+
+	return 0
 }
 
 # Node-RED - from https://nodered.org/docs/getting-started/raspberrypi - not used because it changes node
@@ -8448,7 +8453,7 @@ xWslInstall()
 # other
 #################################################
 
-OtherAllInstall() { i discord slack stamps; }
+OtherAllInstall() { i discord miro slack stamps; }
 
 DiscordInstall()
 {
@@ -8486,6 +8491,13 @@ HostnameInstall()
 		*) return 1;;
 
 	esac
+}
+
+MiroInstall()
+{
+	header "Miro" # https://miro.com/apps/
+	local suffix; IsPlatformAll mac,x86 && suffix="_x86"
+	run "other/Miro/Miro.exe|Miro$suffix.dmg" || return
 }
 
 SlackInstall()
