update SQL Server and VisualStudio version

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1371,7 +1371,9 @@ VsIcons()
 {
 	echo "Updating Visual Studio icons..."
 	ScriptEval VisualStudio init || return
-	local base="$pp/Development/DotNet"; local other="$base/Other"; local vs="$other/Visual Studio $vsName"
+	local base="$pp/Development/DotNet"
+	local other="$base/Other"
+	local vs="$other/Visual Studio $vsName"
 	local java="$pp/Development/Java/Other"
 
 	$makeDir "$java" || return
@@ -1379,32 +1381,31 @@ VsIcons()
 	$makeShortcut "$_windows/assembly" "$base/GAC.lnk" || return
 
 	$mergeDir --rename "$pp/Visual Studio $vsName" "$other/Visual Studio $vsName" || return
-	$mergeDir --rename "$pp/Microsoft Visual Studio $vsName" "$other/Visual Studio $vsName" || return
-	$mergeDir --rename "$pp/Python Tools for Visual Studio 2015" "$vs/Python Tools" || return
-	$mergeDir "$pp/Windows Kits" "$vs" || return
-	$mergeDir "$pp/Windows Phone SDK 8.0" "$vs" || return
-	$mergeDir "$pp/Windows Phone SDK 8.1" "$vs" || return
+	$mergeDir --rename "$pp/Visual Studio $vsName RC" "$other/Visual Studio $vsName RC" || return
 
-	$mv "$pp/Microsoft Test Manager $vsName.lnk" "$vs" || return
-	$mv "$pp/Visual Studio Emulator for Android.lnk" "$vs" || return
-	$mv "$pp/Visual Studio $vsName.lnk" "$vs" || return
-	$mv "$pp/Blend for Visual Studio $vsName.lnk" "$vs" || return
+	$mv "$pp/Visual Studio $vsName.lnk" "$base" || return
+	$mv "$pp/Visual Studio $vsName RC.lnk" "$base" || return
+	$mv "$pp/Visual Studio Installer.lnk" "$base" || return
 
-	$ren "$pp/Microsoft Web Platform Installer.lnk" "$pp/Development/DotNet/Web Platform Installer.lnk" || return
-	$ren "$pp/SQL Server Data Tools 2012.lnk" "$base/SQL Server Data Tools.lnk" || return
+	#$mergeDir --rename "$pp/Python Tools for Visual Studio 2015" "$vs/Python Tools" || return
+	#$mergeDir "$pp/Windows Kits" "$vs" || return
+	#$mergeDir "$pp/Windows Phone SDK 8.0" "$vs" || return
+	#$mergeDir "$pp/Windows Phone SDK 8.1" "$vs" || return
 
-	$mergeDir "$pp/Hyper-V Management Tools" "$pp/Operating System/other" || return
-	$mergeDir "$pp/Java" "$pp/Operating System/other" || return
-	$mergeDir "$up/Node.js" "$pp/Development/Other" || return
+	#$mv "$pp/Microsoft Test Manager $vsName.lnk" "$vs" || return
+	#$mv "$pp/Visual Studio Emulator for Android.lnk" "$vs" || return
+	#$mv "$pp/Blend for Visual Studio $vsName.lnk" "$vs" || return
+	#$ren "$pp/Microsoft Web Platform Installer.lnk" "$pp/Development/DotNet/Web Platform Installer.lnk" || return
+	#$ren "$pp/SQL Server Data Tools 2012.lnk" "$base/SQL Server Data Tools.lnk" || return
+	#$mergeDir "$pp/Hyper-V Management Tools" "$pp/Operating System/other" || return
+	#$mergeDir "$pp/Java" "$pp/Operating System/other" || return
+	#$mergeDir "$up/Node.js" "$pp/Development/Other" || return
 
-	$mergeDir "$pp/Android SDK Tools" "$java" || return
-	$mergeDir "$pp/Java Development Kit" "$java" || return
+	#$mergeDir "$pp/Android SDK Tools" "$java" || return
+	#$mergeDir "$pp/Java Development Kit" "$java" || return
 
-	for f in "$vs/Microsoft"*.lnk; do $ren "$f" "${f/\/Microsoft //}" || return; done
-	$cp "$vs/Visual Studio $vsName.lnk" "$base" || return
-
-	SilverlightIcons || return
-	ExpressionIcons || return
+	#SilverlightIcons || return
+	#ExpressionIcons || return
 }
 
 ExpressionIcons()
@@ -1710,20 +1711,51 @@ IisCheck()
 	return 0
 }
 
-ss() { SqlServerInstall; }; ss14() { SqlServerInstall; }
+ssms() { SqlServerManagementStudioInstall; }
+SqlServerManagementStudioInstall()
+{
+	local base="Microsoft/SQL Server"
+
+	run "$base/setup/SSMS-Setup-ENU.exe" || return # https://msdn.microsoft.com/en-us/library/mt238290.aspx
+	run "$base/plugins/SSMSBoostInstaller2016_3.0.6164.32768.msi" || return # http://www.ssmsboost.com
+
+	ScriptEval SqlServer init || return
+
+	ask 'Restore profile' && { SqlServer profile restore default || return; }
+
+	echot "\
+	- View, Registered Servers
+	- Tools, Options
+	  - Environment
+	    - General, 20 items shown
+	    - Startup, At startup Open empty environment
+	  - Text Editor
+	    - All Languages, check Line numbers
+	    - Editor Tab and Status Bar, Tab Text, all but Include File Name to False
+	   - Query Execution, SQL Server, ANSI, uncheck SET QUOTED IDENTIFIER
+	- Tools, Customize, Keyboard...
+		- View.ZoomIn=Ctrl+Num +
+		- View.ZoomOut=Ctrl+Num -"
+	SqlServer studio || return
+	pause
+
+}
+
+ss() { SqlServerInstall; }
 SqlServerInstall()
 {
 	local base="Microsoft/SQL Server"
-	printf "**************************************************\n* SQL Server 2014\n**************************************************\n"
+	printf "**************************************************\n* SQL Server \n**************************************************\n"
 	
-	echo; echo "Checking for IIS (required for reporting services)..."; IisCheck || return
+	if 	ask -dr n "Install Reporting Services"; then
+		echo; echo "Checking for IIS (required for reporting services)..."; IisCheck || return
+	fi
 
 	echot "\
-Setup logs are in \"$P/Microsoft SQL Server/120/Setup Bootstrap/Log\"
-- run <virtual clone drive>\setup.exe
+Setup logs are in \"$P/Microsoft SQL Server/130/Setup Bootstrap/Log\"
+- run <drive>\setup.exe
 - Installation, New SQL installation or add features to an existing installation
-- Setup Roles, SQL Server Feature Installation
-- Feature Selection, Select All (2.5GB)
+- Feature Selection, Select Database Engine Services
 - (optional) Instance Configuration
   - Named instance=MSSQLSERVER<version>
 	- Instance root directory=d:\Program Files\Microsoft SQL Server\
@@ -1744,31 +1776,18 @@ Setup logs are in \"$P/Microsoft SQL Server/120/Setup Bootstrap/Log\"
 	#   c:/Program Files (x86)/Microsoft Visual Studio 9.0/Common7/IDE/PrivateAssemblies
 	#   c:/Program Files (x86)/Microsoft SQL Server/110/DTS/Binn/
   if [[ $client ]]; then
-  	run "$base/setup/en_sql_server_2014_developer_edition_x64_dvd_3940406.iso" || return
+  	run "$base/setup/en_sql_server_2016_developer_x64_dvd_8777069.iso" || return
 	else
-		run "$base/setup/en_sql_server_2014_enterprise_edition_x64_dvd_3932700.iso" || return
+		run "$base/setup/en_sql_server_2016_enterprise_edition_x64_dvd_3932700.iso" || return
 	fi
 
 	# updates
 	#run "$base/update/SQLServer2012SP2-KB2958429-${architecture}-ENU.exe" || return
 
-	# determine components were installed
-	local clientTools; [[ -f "$P32/Microsoft SQL Server/120/Tools/Binn/ManagementStudio/Ssms.exe" ]] && clientTools="true"
-	local database; [[ -f "$P/Microsoft SQL Server/MSSQL12.MSSQLSERVER/MSSQL/Binn/sqlservr.exe" ]] && database="true"
-
-	if [[ $clientTools ]]; then
-		run "$base/plugins/SSMSBoostInstaller2014_2.17.5717.28174.msi" || return # http://www.ssmsboost.com
-	fi
-
-	[[ $database ]] && ask "Update server configuration" && { SsServerConfig || return; }
-
+	ask "Update server configuration" && { SsServerConfig || return; }
 	ask "Cleanup log" && { SsLogCleanup || return; }
 	ask "Update services" && { SsUpdateServices || return; }
-
-	if [[ $clientTools ]]; then
-		ask "Configure SQL Server Management Studio" && { SsManagementStudioConfig || return; }
-	fi
-
+		
 	SsFinal || return
 }
 
@@ -1817,30 +1836,6 @@ SsUpdateServices()
 	fi
 }
 
-SsManagementStudioConfig()
-{
-	ScriptEval SqlServer init || return
-
-	ask 'Restore profile' && { SqlServer profile restore default || return; }
-	SsManagementStudioConfigInstructions || return
-	SqlServer studio || return
-	pause
-}
-
-SsManagementStudioConfigInstructions()
-{
-	echot "\
-	- View: Registered Servers at top left
-	- Tools, Options
-	  - Environment
-	    - General, 20 items shown
-	    - Startup, At startup Open empty environment
-	  - Text Editor
-	    - All Languages, check Line numbers
-	    - Editor Tab and Status Bar, Tab Text, all but Include File Name to False
-	   - Query Execution, SQL Server, ANSI, uncheck SET QUOTED IDENTIFIER"
-}
-
 SsFinal()
 {
 	ScriptEval SqlServer init || return
@@ -1877,7 +1872,6 @@ SsIntel()
 	local adToolDir="$adPrefix/AppData/Roaming/$toolSuffix"
 
 	if [[ ! -d "$adToolDir" ]]; then
-		SsManagementStudioConfigInstructions || return
 		start runas "/user:amr\ad_$USERNAME" /savecred "$p"
 		pause
 	fi
@@ -1946,16 +1940,16 @@ SsRegistry()
 SsIcons()
 {
 	echo "Updating icons..."	
+	$mergeDir --rename "$pp/Microsoft SQL Server 2016" "$serverPrograms/Other/SQL Server 2016"
 	$mergeDir --rename "$pp/Microsoft SQL Server 2014" "$serverPrograms/Other/SQL Server 2014"
 	$mergeDir --rename "$pp/Microsoft SQL Server 2012" "$serverPrograms/Other/SQL Server 2012"
-	$mergeDir --rename "$pp/Microsoft Visual Studio 2010" "$pp/Development/DotNet/Other/Visual Studio 2010"
 	$mergeDir --rename "$pp/Microsoft SQL Server 2008" "$serverPrograms/Other/SQL Server 2008"
 }
 
 SqlPromptInstall()
 {
 	printf "**************************************************\n* SQL Prompt\n**************************************************\n"
-	run "RedGate/SQLPrompt_6.5.0.330.exe" || return # http://www.red-gate.com/products/sql-development/sql-prompt , downloads to $tmp/Red Gate
+	run "RedGate/SQLPromptDownload.exe" || return # http://www.red-gate.com/products/sql-development/sql-prompt , downloads to $tmp/Red Gate
 
 	echo "Updating icons..."
 	$mergeDir "$pp/Red Gate" "$pp/Development/Other"
@@ -1964,8 +1958,10 @@ SqlPromptInstall()
 - SQL Prompt
 	- Help, Enter Serial Number...
 	- Options...
-	  - Tabs & wraping, Characters per line=120
-	  - Tab history, uncheck all"
+	  - Format, Tabs & wraping
+	  	- Number of spaces equivalent to a tab stop=2
+	  	- Characters per line=120
+	  - Tabs, History, check all but Restore open tabs when SQL Server Management Studio"
 	 SqlServer studio || return
 	 pause
 }
