inst: add qgrep to prevent errors

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1713,7 +1713,7 @@ runXip()
 urlCheck()
 {
 	local url="$1" check="${2:-^HTTP/2 200\|HTTP/1.1 200 OK}"
-	curl --silent --head --location "$url" | ${G}grep --quiet "$check"
+	curl --silent --head --location "$url" | qgrep "$check"
 }
 
 versionAllowAlpha() { IsInArray --case-insensitive "$1" alphaVersions; }
@@ -2476,7 +2476,7 @@ bootstrapPi()
 
 	# locale
 	local locale="$(ConfigGet "locale")"
-	! cat /etc/default/locale | ${G}grep -q "$locale" && { sudo raspi-config nonint do_change_locale $locale || return; export LOCALE="$locale"; }
+	! cat /etc/default/locale | qgrep "$locale" && { sudo raspi-config nonint do_change_locale $locale || return; export LOCALE="$locale"; }
 
 	# other setup
 	i PiSwap || return
@@ -2877,7 +2877,7 @@ DebianFileSharingInstall()
 
 	! InPath smbd && { pkg samba || return; } # service
 	! InPath smbclient && { pkg smbclient || return; }
-	! PackageListInstalled | ${G}grep --quiet "^samba-vfs-modules:" && { pkg samba-vfs-modules || return; }
+	! PackageListInstalled | qgrep "^samba-vfs-modules:" && { pkg samba-vfs-modules || return; }
 
 	local workgroup; workgroup="$(ConfigGet "workgroup")"
 	if [[ "$(network workgroup name)" != "$workgroup" ]]; then
@@ -3028,7 +3028,7 @@ DebianProxyServerInstall()
 	header "Debian Proxy Server"
 
 	local file="/etc/sudoers"
-	sudo ${G}grep -q "HTTP_PROXY" "$file" && return
+	sudo ${G}grep --quiet "HTTP_PROXY" "$file" && return
 	echo 'Defaults env_keep += "ftp_proxy http_proxy https_proxy no_proxy FTP_PROXY HTTP_PROXY HTTPS_PROXY NO_PROXY"' | sudo ${G}tee -a "$file" || return
 }
 
@@ -3201,7 +3201,7 @@ PlaywrightInstall()
 	[[ ! $force && -d "$dir" ]] && return
 
 	# install from Git repository if possible
-	if IsAvailable git && GitHelper remote ls git | ${G}grep --quiet "^playwright$"; then
+	if IsAvailable git && GitHelper remote ls git | qgrep "^playwright$"; then
 		GitHelper clone git playwright && cd "$dir" && yarn install
 	else
 		run --yarn --header "Playwright" playwright
@@ -3756,10 +3756,10 @@ DbusInstall()
 
 	# WSL error message
 	local file="/usr/share/dbus-1/system.d/org.freedesktop.NetworkManager.conf"
-	IsPlatform wsl && [[ -f "$file" ]] && ${G}grep -q "whoopsie" "$file" && { echo "Remove whoopsie policy..."; sudoe "$file"; }
+	IsPlatform wsl && [[ -f "$file" ]] && ${G}grep --quiet "whoopsie" "$file" && { echo "Remove whoopsie policy..."; sudoe "$file"; }
 
 	# mac
-	IsPlatform mac && brew services list | ${G}grep '^dbus ' | ${G}grep --quiet none && { brew services start dbus || return; }
+	IsPlatform mac && brew services list | ${G}grep '^dbus ' | qgrep none && { brew services start dbus || return; }
 
 	# start
 	app dbus "${globalArgs[@]}" && DbusConf
@@ -5254,7 +5254,7 @@ MacDockCleanupInstall()
 	echo -n "cleaning dock..."
 	local args=() apps=("App Store" Contacts Calendar FaceTime Freeform Launchpad Mail Maps Messages Music News Notes Photos Podcasts Reminders Safari "System Preferences" TV )
 	for app in "${apps[@]}"; do		
-		dockutil --list | ${G}grep --quiet "^$app" && { echo -n "$app..."; dockutil --remove "$app" || return; }
+		dockutil --list | qgrep "^$app" && { echo -n "$app..."; dockutil --remove "$app" || return; }
 	done
 	echo "done"
 }
@@ -5967,7 +5967,7 @@ DomotzAgentInstall()
 	
 	# install
 	local name="domotzpro-agent-publicstore"
-	if ! snap list | ${G}grep --quiet '^domotzpro-agent-publicstore'; then
+	if ! snap list | qgrep '^domotzpro-agent-publicstore'; then
 		sudoc snap install "$name" || return
 	  sudo snap connect $name:firewall-control || return
 	  sudo snap connect $name:network-observe || return
@@ -5977,12 +5977,12 @@ DomotzAgentInstall()
 	fi
 
 	# configure firewall
-	InPath ufw && sudo ufw status | ${G}grep --quiet " active" && { sudo ufw allow 3000 || return; }
+	InPath ufw && sudo ufw status | qgrep " active" && { sudo ufw allow 3000 || return; }
 
 	# configured allowed interface
 	local interface; interface="$(GetInterface)" || return
 	echo "Checking if '$interface' is the allowed interface..."
-	if ! DomotzHelper api network/interfaces-policy | ${G}grep --quiet "\"$interface\""; then
+	if ! DomotzHelper api network/interfaces-policy | qgrep "\"$interface\""; then
 		echo "Setting '$interface' to the allowed interface..."
 		DomotzHelper api put network/interfaces-policy '{ "policy": "allow", "rules": [ "'$interface'" ] }' || return
 	fi
@@ -6449,12 +6449,12 @@ wifiUbuntu()
 	iwconfig $interface >& /dev/null && { sudo ifconfig $interface up || return; }
 		
 	# connect to a wireless network
-	if iwconfig |& ${G}grep --quiet Not-Associated; then
+	if iwconfig |& qgrep "Not-Associated"; then
 
 		# get SSID
 		local networks; networks="$(WifiNetworks)" || return
 		local defaultNetwork="$(ConfigGet "wifi")"
-		! echo "$networks" | ${G}grep --quiet "^$defaultNetwork$" && defaultNetwork="" # default network not found
+		! echo "$networks" | qgrep "^$defaultNetwork$" && defaultNetwork="" # default network not found
 		[[ ! $defaultNetwork ]] && defaultNetwork="$(WiFiNetworks | shead -1)"
 		local network; network="$(ask text "What Wi-Fi network would you like to connect to ($defaultNetwork)")" || return
 		[[ ! $network ]] && network="$defaultNetwork"
@@ -7474,7 +7474,7 @@ PythonAsdfInstall()
 	esac
 
 	# install plugin
-	! asdf plugin list | ${G}grep -q python && { asdf plugin add python || return; }
+	! asdf plugin list | qgrep "python" && { asdf plugin add python || return; }
 
 	# install latest python
 	asdf install python latest || return
@@ -7777,7 +7777,7 @@ PiOverclockInstall()
 	! IsPlatform ubuntu && return
 
 	# return if overclocked already	
-	grep -q "# overclocking" "$file" && return
+	grep --quiet "# overclocking" "$file" && return
 
 	# backup
 	sudoc bak "$file" || return
@@ -7850,7 +7850,7 @@ PiSugarUpsInstall()
 PiSwapInstall()
 {
 	header "Raspberry Pi Swap Space"
-	grep -q "CONF_SWAPSIZE=4096" "/etc/dphys-swapfile" && return
+	grep --quiet "CONF_SWAPSIZE=4096" "/etc/dphys-swapfile" && return
 
 	local clip; clip="CONF_SWAPSIZE=4096"
 	echo -e "- paste:\n$clip"; clipw "$clip" || pause
@@ -7998,7 +7998,7 @@ RubyAsdfInstall()
 	i --no-header asdf || return
 
 	# install Ruby plugin
-	! asdf plugin list | ${G}grep -q ruby && { asdf plugin add ruby || return; }
+	! asdf plugin list | qgrep ruby && { asdf plugin add ruby || return; }
 
 	# install latest Ruby
 	asdf install ruby latest || return
@@ -8033,7 +8033,7 @@ RubyRvmInstall()
 
 	# ruby
 	local version="3.0"
-	if ! InPath ruby || ! ruby --version | ${G}grep "$version" >& /dev/null; then
+	if ! InPath ruby || ! ruby --version | qgrep "$version"; then
 		rvm install "$version" || return
 		. "$HOME/.rvm/scripts/rvm" || return # add ruby and gem to the path in current shell
 		rvm use --default "$version" || return
@@ -8279,7 +8279,7 @@ BashProfile()
 
 ZshInstall()
 {
-	IsPlatform mac && ! which zsh | ${G}grep --quiet "homebrew" && force="--force" # force if the Homebrew Zsh is not installed
+	IsPlatform mac && ! which zsh | qgrep "homebrew" && force="--force" # force if the Homebrew Zsh is not installed
 	run --name="Z shell" --package zsh && forceAllParts="true"
 }
 
@@ -8607,7 +8607,7 @@ sshServerEntware()
 
 sshServerMac()
 {
-	sudoc systemsetup -getremotelogin | ${G}grep --quiet "Remote Login: On" && return
+	sudoc systemsetup -getremotelogin | qgrep "Remote Login: On" && return
 	sudo systemsetup -setremotelogin on
 }
 
@@ -8631,7 +8631,7 @@ sshServerWsl()
 
 	# service permission
 	local file="/etc/sudoers"
-	if ! sudo ${G}grep "$USER" "$file" >& /dev/null; then
+	if ! sudo ${G}grep --quiet "$USER" "$file"; then
 		echo "$USER ALL = (root) NOPASSWD: /usr/sbin/sshd -D" | sudo ${G}tee -a "$file" || return
 	fi
 
@@ -8663,7 +8663,7 @@ sshClientMac()
 	ssh-add --apple-use-keychain || return
 
 	# configure X
-	if ! ${G}grep "XAuthLocation /opt/X11/bin/xauth" /etc/ssh/ssh_config  >& /dev/null; then
+	if ! ${G}grep --quiet "XAuthLocation /opt/X11/bin/xauth" "/etc/ssh/ssh_config"; then
 		echo "Configuring SSH authentication..."
 		echo "XAuthLocation /opt/X11/bin/xauth" | sudo ${G}tee -a /etc/ssh/ssh_config
 	fi
@@ -8744,7 +8744,7 @@ isStoreId() { ! IsPlatform mac && return 1; RunPlatform isStoreId "$1"; }
 isStoreIdMac() { IsInteger "$1"; }
 
 # storeIsInstalled ID - return true if the application with store ID is installed
-storeIsInstalled() { storeCheck && mas list | ${G}grep --quiet "^$1 "; }
+storeIsInstalled() { storeCheck && mas list | qgrep  "^$1 "; }
 
 # storeCurrentVersion ID - return the current version of the application with the store ID
 storeCurrentVersion() { RunPlatform storeCurrentVersion "$1"; }
@@ -8752,7 +8752,7 @@ storeCurrentVersionMac() { storeCheck && mas search "$1" | rev | cut -d" " -f 1 
 
 # storeIsInstalled ID - return true if the application with store ID is installed
 storeIsInstalled() { RunPlatform storeIsInstalled "$1"; }
-storeIsInstalledMac() { storeCheck && mas list | ${G}grep --quiet "^$1 "; }
+storeIsInstalledMac() { storeCheck && mas list | qgrep "^$1 "; }
 
 #################################################
 # Surveillance
@@ -8901,7 +8901,7 @@ warpFindUrl()
 
 	for (( i = 5; i >= 0; i-- )); do
 		tryUrl="$(eval echo $url)"
-		curl --silent "$tryUrl" --head | ${G}grep --quiet "404" && { logp1 "."; continue; }
+		curl --silent "$tryUrl" --head | qgrep "404" && { logp1 "."; continue; }
 		logp1 "found\n"; echo "$tryUrl"; return
 	done
 
@@ -9197,10 +9197,10 @@ rtcPiKernel()
 {
 	# dependencies
 	piI2cCheck || return
-	! PackageListInstalled | ${G}grep --quiet "^python3-smbus:" &&  { package python3-smbus || return; }
+	pkg python3-smbus || return
 
 	# check for RTC chip
-	! sudoc i2cdetect -y 1 | ${G}grep --quiet -E "( 68|UU )" && { ScriptErr 'RTC chip not detected, try rebooting'; return 1; }
+	! sudoc i2cdetect -y 1 | qgrep -E "( 68|UU )" && { pause ScriptErr 'RTC chip not detected, try rebooting'; return 1; }
 
 	# update config.txt if needed
 	local file="/boot/firmware/config.txt"
@@ -9210,14 +9210,14 @@ rtcPiKernel()
 	# add kernel module
 	local file="/boot/firmware/usercfg.txt"; IsPlatform pi && file="/boot/config.txt"
 	local line="dtoverlay=i2c-rtc,ds3231"
-	if ! ${G}grep --quiet "^$line$" "$file"; then
+	if [[ ! -f "$file" ]] || ! ${G}grep --quiet "^$line$" "$file"; then
 		echo "$line" | sudo ${G}tee -a "$file" || return
 		rebootDo || return
 		return 1
 	fi
 
 	# check for RTC
-	! sudo i2cdetect -y 1 | ${G}grep --quiet -E "UU " && { ScriptErr 'RTC chip not detected'; return 1; }		
+	! sudo i2cdetect -y 1 | qgrep ---E "UU " && { ScriptErr 'RTC chip not detected'; return 1; }		
 
 	# configure hwclock-set
 	local file="/lib/udev/hwclock-set"
@@ -9235,7 +9235,7 @@ timezoneMessage() { hilight "Setting the timezone to '$timezone'..."; }
 timezoneDebian()
 {
 	{ [[ ! $timezone ]] || IsPlatform win; } && return
-	[[ ! $force ]] && cat "/etc/timezone" |& ${G}grep "$timezone" > /dev/null && return
+	[[ ! $force ]] && cat "/etc/timezone" |& qgrep "$timezone" && return
 
 	timezoneMessage
 	DEBIAN_FRONTEND=noninteractive sudoc apt install -y tzdata || return
@@ -9248,7 +9248,7 @@ timezoneDebian()
 timezonePi()
 {
 	[[ ! $timezone ]] && return
-	[[ ! $force ]] && cat /etc/timezone | ${G}grep -q "$timezone" && return
+	[[ ! $force ]] && cat /etc/timezone | qgrep "$timezone" && return
 
 	timezoneMessage; sudo raspi-config nonint do_change_timezone "$timezone"
 }
@@ -9722,7 +9722,7 @@ HiddenStartFinalWin()
 	i HiddenStartConfigure || return
 }
 
-isHiddenStartConfigued() { schtasks.exe | ${G}grep HstartUAC-x64 >& /dev/null; }
+isHiddenStartConfigued() { schtasks.exe | qgrep "HstartUAC-x64"; }
 
 HiddenStartConfigureInstall()
 {
@@ -9974,7 +9974,7 @@ DockerInstall()
 	docker run "hello-world"
 
 	# create the user-network
-	! docker network ls | ${G}grep --quiet user-network && { sudoc docker network create "user-network" || return; }
+	! docker network ls | qgrep user-network && { sudoc docker network create "user-network" || return; }
 
 	return 0
 }
@@ -10724,7 +10724,7 @@ xpraInstall() # 332MB (Linux)
 
 		# disable sound forwarding -  https://www.xpra.org/trac/wiki/Sound
 		local file="$UADATA/../Roaming/Xpra/xpra.conf" line="speaker = off"
-		[[ -f "$file" ]] && ! ${G}grep -q "$line" "$file" && { echo "$line" >> "$file" || return; }
+		[[ -f "$file" ]] && ! ${G}grep --quiet "$line" "$file" && { echo "$line" >> "$file" || return; }
 
 		# icons
 		mergeDir "$pp/Xpra" "$oo" || return
@@ -10739,7 +10739,7 @@ xpraInstall() # 332MB (Linux)
 	if IsPlatform mac; then
 		local file="$HOME/Library/Application Support/Xpra/xpra.conf"
 		local line="ssh = ssh -Y"
-		! ${G}grep -q "^${line}$" "$file" && { echo "$line" >> "$file" || return; }
+		! ${G}grep --quiet "^${line}$" "$file" && { echo "$line" >> "$file" || return; }
 
 		return 0
 	fi
