inst: add preinstall packages for DockerCompose and BorgBackup

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1484,7 +1484,7 @@ runTypePython()
 {
 	local p="$1" name="$2" dest="$3"; shift 3
 	pythonCheckLocal || return
-	RunLog python3 -m pipx install $force --pip-args="$pipArgs" "$p" "$@" || return
+	RunLog python3 -m pipx install $force $preinstall --pip-args="$pipArgs" "$p" "$@" || return
 }
 
 # runTypePythonGlobal - Python package install for all users
@@ -1492,7 +1492,7 @@ runTypePythonGlobal()
 {
 	local p="$1" name="$2" dest="$3"; shift 3
 	pythonCheckGlobal || return
-	RunLog pipxg install $force --pip-args="$pipArgs" "$p" "$@" || return
+	RunLog pipxg install $force $preinstall --pip-args="$pipArgs" "$p" "$@" || return
 }
 
 runTypeRuby()
@@ -3349,7 +3349,8 @@ BorgBackupInstall()
 	fi
 
 	# install
-	local pipArgs='--no-build-isolation' # otherwise high CPU building wheels on ARM
+	local pipArgs='--no-build-isolation' 													# prevent high CPU building wheels on ARM
+	local preinstall='--preinstall=wheel --preinstall=pkgconfig' 	# required in Ubuntu 22.04 
 	{ ! InPath borg || [[ $force ]]; } && { run --no-header --python-global borgbackup || return; }
 	pipxg inject borgbackup llfuse || return	
 
@@ -9954,7 +9955,8 @@ DockerHelpWin()
 DockerComposeInstall() 
 {
 	IsPlatformAll PiKernel,ubuntu && { pkg make; }
-	local pipArgs='--no-build-isolation' # otherwise install fails
+	local pipArgs='--no-build-isolation' 	# otherwise install fails
+	local preinstall='--preinstall=wheel' # required in Ubuntu 22.04 
 	run --python-global "docker-compose"
 }
 
