os: add dns prefer command

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -8614,11 +8614,8 @@ WslFinalWin()
 	$mv "$pp/WSL.lnk" "$d" || return
 	$mv "$pp/WSL Settings.lnk" "$d" || return
 
-	# prefer IPv4 DNS name resolution, IPv6 name resolution tried last, IPv6 resolution fails in restricted domains (like Sandia)
-	local file="/etc/gai.conf" line="#precedence ::ffff:0:0/96  100"
-	if IsDomainRestricted && qgrep "^${line}$" "$file"; then
-		sudo sed -i 's/^'"$(QuoteForwardslashes "$line")"'$/precedence ::ffff:0:0\/96  100/' "$file" || return
-	fi
+	# prefer IPv4 DNS name server over IPv6, IPv6 resolution fails in restricted domains (like Sandia)
+	IsDomainRestricted && { os dns prefer IPv4 || return; }
 
 	# startup
 	local prefix; ! CanElevate && prefix="u"
