inst: add MacFileSharing

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -454,8 +454,9 @@ installInit()
 	elevateInstall=(GitForWindows WinConfig WinPermissions)
 
 	# isInstallable	
-	all=(download final help register update)
-	all+=(AppDir DriveTime envoy fileServer hostname PartitionManagement store)	
+	all=(download final help register update)		# install
+	all+=(FileSharing fonts IconCleanup setup) 	# platform
+	all+=(AppDir DriveTime envoy FileServer hostname PartitionManagement store)	
 	debian=()	debian64=() debianWin=() mac=() macDebian=() winElevated=() win=()
 	
 	# Android
@@ -2507,10 +2508,7 @@ BootstrapInstall()
 	i BootstrapFiles SshClientPermission dbus CredentialStore timezone || return 
 
 	# bootstrap
-	RunPlatform bootstrapStart || return
-	RunPlatform bootstrap || return
-	bootstrapCommon || return
-	bootstrapFinal || return
+	RunPlatform bootstrapStart && RunPlatform bootstrap && bootstrapCommon && bootstrapFinal
 }
 
 #
@@ -2747,20 +2745,16 @@ bootstrapWin()
 bootstrapCommon()
 {
 	header "Bootstrap Common"
-	i bash zsh || return				# shells
-	i AppDir SshCore || return	# other
+	i bash zsh || return								# shells
+	i AppDir SshCore || return					# other
+	i setup FileSharing fonts || return # platform
 }
 
 #
 # bootstrap final
 #
 
-bootstrapFinal() { RunPlatform bootstrapFinal && RunPlatform bootstrapIcons && UpdateDone "install-bootstrap"; }
-bootstrapFinalDebian() { i DebianSetup; }
-bootstrapFinalMac() { i MacSetup; }
-bootstrapFinalWin() { i WinSetup; }
-bootstrapIcons() { RunPlatform BootstrapIcons; }
-bootstrapIconsWin() { i WinIcons; }
+bootstrapFinal() { i icons && UpdateDone "install-bootstrap"; }
 
 #
 # bootstral installs
@@ -2807,6 +2801,31 @@ BootstrapFilesInstall()
 	echo "done"
 }
 
+#################################################
+# Platform Installs
+#################################################
+
+# File Sharing - install file sharing and standard shares
+FileSharingInstall() { RunPlatform fileSharing; }
+fileSharingDebian() { i DebianFileSharing; }
+fileSharingMac() { i MacFileSharing; }
+fileSharingWin() { i WinFileSharing; }
+
+# Fonts - install standard fonts
+FontsInstall() { RunPlatform fonts; }
+fontsDebian() { i DebianFonts; }
+fontsMac() { i MacFonts; }
+fontsWin() { i WinFonts; }
+
+# Icon Cleanup - cleanup platform unused icons
+IconCleanupInstall() { RunPlatform iconCleanup; }
+iconCleanupWin() { i WinIconCleanup; }
+
+# setup - run platform setup
+SetupInstall() { RunPlatform setup; }
+setupDebian() { i DebianSetup; }
+setupMac() { i MacSetup; }
+setupWin() { i WinSetup; }
 
 #################################################
 # Browser
@@ -3164,7 +3183,7 @@ DebianAllInstall() { i DebianSetup DebianDns DebianFileSharing DebianFonts Debia
 DebianSetupInstall()
 {
 	header "Debian Setup"
-	i apt DebianDns DebianFileSharing DebianFonts DebianLocale DebianPolicies DebianProxyServer DebianSudoSecurePath || return
+	i apt DebianDns DebianFileSharing DebianLocale DebianPolicies DebianProxyServer DebianSudoSecurePath || return
 }
 
 DebianDnsInstall()
@@ -5849,7 +5868,7 @@ MacAppAllInstall() { i CarrotWeather DayOne flighty LiveDesktop SpeedTest ValetC
 MacSetupInstall()
 {
 	header "Mac Setup"
-	i MacAppCleanup MacConfigure MacDirectories MacDockCleanup MacDockOrder MacFonts MacNetwork MacPower MacShortcuts || return
+	i MacAppCleanup MacConfigure MacDirectories MacDockCleanup MacDockOrder MacNetwork MacPower MacShortcuts || return
 }
 
 MacAppCleanupInstall()
@@ -5900,6 +5919,14 @@ MacDockCleanupInstall()
 }
 
 MacDockOrderInstall() { macDockOrder Finder Obsidioan iTerm Warp Firefox Slack Teams; }
+
+MacFileSharingInstall()
+{
+	unc share exists "Macintosh HD" && { sudoc sharing -r "Macintosh HD" || return; } # cleanup "Macintosh HD"
+	! unc share exists "root" && { sudoc sharing -a "/" -n "root" -g 000 || return; } # root
+	! unc share exists "$USER" && { sudoc sharing -a "$HOME" -g 000 || return; }			# user
+	return 0
+}
 
 MacFontsInstall()
 {
@@ -11404,7 +11431,7 @@ WinSetupInstall()
 {
 	header "Windows Setup"
 	i SystemInternals WinPath WinPermissions || return # run first
-	i WinApps WinConfig WinConfigUser WinConsole WinDirs WinDirsUser WinFonts WslConfig OneDrive || return
+	i WinApps WinConfig WinConfigUser WinConsole WinDirs WinDirsUser WslConfig OneDrive || return
 }
 
 # WinAppsInstall - install additional applications for the current Windows build
@@ -11610,6 +11637,11 @@ WinDirsUserInstall()
 	makeLink --symbolic "$WIN_ROOT/Users/Public" "$PUB" || return
 }
 
+WinFileSharingInstall()
+{
+	:
+}
+
 WinFontsInstall()
 {
 	header "Windows Fonts"
@@ -11656,11 +11688,11 @@ windowsFont()
 	return 0
 }
 
-WinIconsInstall()
+WinIconCleanupInstall()
 {
 	! IsPlatform win && return
 
-	header "Windows Icons"
+	header "Windows Icon Cleanup"
 
 	local dest="$pp"; ! CanElevate && dest="$up"
 	mergeDir "$up/Accessibility" "$dest/Applications/Accessories" || return
@@ -11676,10 +11708,10 @@ WinIconsInstall()
 	$rmd "$up/Maintenance" || return
 	$rmd "$up/Windows PowerShell" || return
 
-	winIconsElevated || return
+	winIconCleanupElevated || return
 }
 
-winIconsElevated()
+winIconCleanupElevated()
 {
 	! CanElevate && return
 
