inst register: enhance logging

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -388,7 +388,7 @@ checkInstallable()
 	local app="$1"
 
 	isInstallable "$app" && return
-	[[ ! $quiet ]] && echo "$(ScriptName): '$app' is not installable on $(PlatformSummary)"
+	[[ ! $quiet && ! $isRegistering ]] && echo "$(ScriptName): '$app' is not installable on $(PlatformSummary)"
 	return 1
 }
 
@@ -581,9 +581,10 @@ i()
 iPortion()
 {
 	local portion="$1"
-	local -n no="no${portion^}"; [[ $no ]] && return # return if the --no-PORTION option was used
+	local -n no="no${portion^}"; [[ $no ]] && return 			# return if the --no-PORTION option was used
 	local noHeader="$noHeaderArg" noPrompt="$noPromptArg" # don't run as prefix, interferes with local variables later
-	RunFunction "${appFunction}${portion}" && noHeader="$noHeaderArg" noPrompt="$noPromptArg" RunPlatform "${appFunction}${portion}"; 
+	RunFunction "${appFunction}${portion}" || return 			# run the portion
+	noHeader="$noHeaderArg" noPrompt="$noPromptArg" RunPlatform "${appFunction}${portion}"; # run the platform specific portion
 }
 
 iPortionRegister() { [[ $noRegister ]] && return; iPortion "Register";  }
@@ -675,8 +676,8 @@ makeLink()
 # register APP - enter the registration information for an application
 register()
 {
-	local app="$1"; { ! appIsInstalled "$app" || ! isInstallable "$app" || [[ $noPrompt ]]; } && return
-	
+	local app="$1"; { ! appIsInstalled "$app" || [[ $noPrompt ]]; } && return
+
 	# skip registration if a remote credential manager is not installed
 	credential manager status --manager=remote --quiet || { [[ ! $quiet ]] && ScriptErr "register: remote credential manager is not available"; return; }
 
@@ -1366,7 +1367,8 @@ FinalInstall()
 RegisterInstall()
 {
 	local app apps=(1Password alfred BeyondCompare firefox GitHub MaxTo sublime SublimeMerge TidyTabs)
-	unset noRegister # force registration
+	local isRegistering="true"
+	noRegister="" # force registration
 	for app in "${apps[@]}"; do i --no-header "${app}Register" || return; done
 }
 
@@ -1862,7 +1864,6 @@ FirefoxInstall()
 FirefoxProfile() { firefox $noPrompt profile restore default; }
 FirefoxFinalMac() { dockutil --find "Firefox" >& /dev/null && return; dockutil --add "/Applications/Firefox.app"; }
 FirefoxFinalWin() { $mv "$pp/Firefox.lnk" "$pp/Applications" && $mv "$up/Firefox Private Browsing.lnk" "$pp/Firefox Private Browsing.lnk" "$pp/Applications" && $rm "$pd/Firefox.lnk"; }
-FirefoxRegister() { FirefoxHelp && register "firefox"; }
 
 FirefoxDownload()
 {
@@ -2431,13 +2432,14 @@ BorgBackupInstall()
 	# check if installed
 	InPath borg && [[ "$(borg --version)" == "borg $v" && ! $force ]] && return
 
-	# QNAP
+	# other platforms
 	IsPlatform qnap && { run --store "BorgBackup"; return; }
+	IsPlatform casaos && { pkg borgbackup; return; }
 
 	# prerequisites
+	
 	if IsPlatform debian; then
-		pkg g++ gcc || return
-		! IsPlatform casaos && { libfuse-dev || return; }
+		pkg g++ gcc libfuse-dev || return
 		pkg python3 python3-dev python3-virtualenv build-essential libacl1-dev libacl1 libssl-dev liblz4-dev libzstd-dev libxxhash-dev pkg-config || return		
 		pkg-config python3-pkgconfig # returns an error, but borg installs successfully
 	elif IsPlatform mac; then
@@ -8807,12 +8809,16 @@ DiscordFinalWin()
 }
 
 HostnameInstall()
-{
-	IsDocker && return # Docker hostname must be set in the containers config.vs.json
-
+{	
+	# Docker hostname must be set in the containers config.vs.json
+	IsDocker && return
+	
+	# return if needed
 	[[ ! $force ]] && ! UpdateNeeded "HostnameChanged" && return
 
-	os name set || return
+	header "Hostname"
+
+	os name set # use return values
 	case $? in
 
 		# name changed
