inst: fix XCode version

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -205,14 +205,17 @@ checkApp()
 	# get current version
 	if [[ ${storeIds[$app]} ]] || IsFunction "${app,}Version"; then
 		log1 "Getting ${appName}${type} current version..."
-		current="$(force="$forceLess" getVersionCurrent "$app" | ReplaceString "-" "_")"  || ScriptErr "unable to get '$app' current version"
+		if ! current="$(force="$forceLess" getVersionCurrent "$app" | ReplaceString "-" "_")"; then
+			local error="unable to get '$app${type}' current version"
+			[[ "$installType" != "beta" ]] && ScriptErr "$error" || log1 "$error"
+		fi
 		[[ ! $verbose && ! $quiet ]] && PrintErr "."
 	fi
 
 	# hide installed version if needed
 	[[ ! $current && "$installType" == "beta" ]] && installed=""
 
-	if [[ $current && "$installed" != "$current" ]]; then
+	if [[ $current && "$installed" != "$current" && "$(echo "$installed != $current" | bc)" == "1" ]]; then
 
 		# regular version is installed and showing beta version
 		if [[ "$installType" == "beta" ]]; then
@@ -220,7 +223,7 @@ checkApp()
 			{ [[ "$installed" == "$regularVersion" ]] || versionIsOlder "$installed" "$regularVersion"; } && installed=""
 
 		# has a beta version and it is installed and showing regular version
-		else 
+		else
 			versionIsNewer "$installed" "$current" && IsFunction "${app,}VersionBeta" && installed=""
 		fi
 	fi
