inst NoMachine: add download

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -2950,7 +2950,7 @@ LinuxUtilitiesInstall()
 	pkg shellcheck || return													# script
 	pkg sox || return																	# sound (play)
 	pkg direnv timewarrior util-linux || return				# other
-	i bat cheat choose dog duf dust exa httpie mcfly procs ripgrep || return
+	i bat cheat choose dog duf dust exa mcfly procs ripgrep || return
 }
 
 LinuxNetworkUtilitiesInstall()
@@ -6728,8 +6728,50 @@ AppleRemoteDesktopInstall() { run --name "Remote Desktop" "409907375" || return;
 JumpDesktopInstall() { run --name "Jump Desktop"  "network/JumpDesktop/JumpDesktop.exe|JumpDesktopMac.zip"; } # https://app.jumpdesktop.com/dashboard
 JumpDesktopFinalWin() {	makeDir "$oo/Jump Desktop" && $mv "$pp/Jump Desktop.lnk" "$oo/Jump Desktop" && $mv "$pp/Jump Desktop Connect.lnk" "$oo/Jump Desktop"; }
 MicrosoftRemoteDesktopInstall() { run --name "Microsoft Remote Desktop" "1295203466"; }
-NoMachineInstall() { local v="8.4.2"; run --header "NoMachine" "shareware/NoMachine/nomachine_${v}_10_x64.exe|nomachine_${v}_5.dmg|nomachine_${v}_4_amd64.deb"; } # https://www.nomachine.com/download
+
+NoMachineInstall()
+{
+	local dir="shareware/NoMachine" v; v="$(getVersion "NoMachine" "$dir")"
+	run --name="NoMachine" "$dir/shareware/NoMachine/NoMachine $v.exe|NoMachine $v.dmg|NoMachine $v.deb" --version="$v"
+}
+
 NoMachineFinalWin() { $rm "$pd/NoMachine.lnk" && mergeDir "$pp/NoMachine" "$oo" && moveAppData "NoMachine" || return; }
+NoMachineProfile() { NoMachine profile restore default && NoMachine startup; }
+
+NoMachineDownload()
+{
+	header "NoMachine Download"
+	local dir="shareware/NoMachine"
+	local v; v="$(getVersion "NoMachine" "$dir")" || return
+	local vShort="$(GetWord "$v" 1 .).$(GetWord "$v" 2 .)"
+	local item items=("Linux-_amd64-deb" "MacOSX--dmg" "Windows-_x64-exe")
+
+	for item in "${items[@]}"; do
+		local plat="$(GetWord "$item" 1 -)" suffix="$(GetWord "$item" 2 -)" ext="$(GetWord "$item" 3 -)"
+		local url="https://download.nomachine.com/download/$vShort/$plat/nomachine_${v}_"'${i}'"${suffix}.${ext}"
+		noMachineFindUrl || return
+		download "$url" "$dir" "NoMachine $v.$ext" || return
+	done
+}
+
+# noMachineFindUrl - find the version to download, NoMachine does not make this easily accessible
+# - the url includes ${i} as a substitution for the version, i.e. nomachine_8.4.2_${i}_x64.exe
+noMachineFindUrl()
+{
+	local i result tryUrl
+
+	printf "Finding $plat..."
+	for (( i = 1; i <= 20; i++ )); do
+		tryUrl="$(eval echo $url)"
+		result="$(curl --silent "$tryUrl" --head | head -1)" || return
+		[[ ! "$result" =~ 200 ]] && { printf "."; continue; }
+		echo "found"; url="$tryUrl"; return 0
+	done
+
+	echo "not found"; return 1
+}
+
+noMachineVersion() { curl --silent "https://www.nomachine.com/all-news-software-updates" | grep "now available" | grep "href" | head -1 | sed 's/.*NoMachine //' | cut -d" " -f1; }
 
 TigerVncInstall()
 {
@@ -8023,6 +8065,7 @@ AlfredInstall()
 	run --name="Alfred" "$dir/Alfred-$v.zip" --version="$(GetWord "$v" 1 _)" && alfred startup
 }
 
+AlfredProfile() { alfred profile restore default; }
 AlfredRegister() { register "alfred"; }
 
 AlfredDownload()
