inst PodmanDesktop: add comment on why not doing silent install

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -14250,7 +14250,7 @@ PodmanDesktopInstall()
 	local v; v="$(versionGetCurrent "PodmanDesktop")" || return
 	local airgap="-airgap"; IsPlatform linux && airgap=""
 	local arch="$(getArch "x64" "arm64")"; IsPlatform linux && arch="$(getArch "" "-arm64")"	
-	run --name "PodmanDesktop" "$(podmanDesktopDir)/podman-desktop${airgap}-$v$(getPlatform "-setup-$arch.exe" "-$arch.dmg" "$arch.tar.gz")" --version=$v --elevate --no-header -- || return
+	run --name "PodmanDesktop" "$(podmanDesktopDir)/podman-desktop${airgap}-$v$(getPlatform "-setup-$arch.exe" "-$arch.dmg" "$arch.tar.gz")" --version=$v --elevate --no-header || return # /S may cause install to fail, need to try again
 	
 	# configure
 	iq PodmanConfigure && PodmanDesktopHelper startup 
