inst TftpServer: use systemd

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -5938,7 +5938,6 @@ GlobalProtectVpnInstall() { run --name "Global Protect" "other/Palo Alto Network
 HttpieInstall() { run --python-global "httpie"; }
 MtrInstall() { run --package "mtr"; }
 TftpclientInstall() { run --name "TFTP Client" --package "tftp-hpa"; }
-TftpserverInstall() { run --name "TFTP Server" --package "tftpd-hpa" && nomadRegisterApp "tftp" "tftpd-hpa"; }
 WiFiExplorerInstall() { run --name "WiFi Explorer Pro 3"; }
 WtfisInstall() { run --python-global wtfis; } # # https://github.com/pirxthepilot/wtfis
 WtfisProfile() { profile restore default --app "wtfis" --method "$HOME" --files '.env.wtfis' $noPrompt && chmod 400 "$HOME/.env.wtfis"; }
@@ -6505,6 +6504,42 @@ staticIpUbuntu()
 
 	sudo netplan apply || return
 	[[ $reboot ]] || IsStaticIp
+}
+
+TftpserverInstall()
+{
+	run --name "TFTP Server" --package "tftpd-hpa" || return
+
+	# cleanup
+	local file="/etc/init.d/tftpd-hpa"
+	if [[ -f "$file" ]]; then
+		service stop tftpd-hpa || return
+		sudoc $rm "$file" || return
+	fi
+
+	# service
+	local file="/etc/systemd/system/tftpd-hpa.service"
+	if [[ ! -f "$file" || $force ]]; then
+		cat <<-EOF | sudo ${G}tee "$file" > /dev/null || return
+			[Unit]
+			Description=TFTP daemon by H. Peter Anvin
+			Documentation=https://mirrors.edge.kernel.org/pub/software/network/tftp/tftp-hpa/
+			Wants=network-online.target
+			After=network-online.target
+
+			[Service]
+			EnvironmentFile=/etc/default/tftpd-hpa
+			ExecStart=/bin/bash -c '/usr/sbin/in.tftpd --foreground --listen --user \$TFTP_USERNAME --address \$TFTP_ADDRESS \$TFTP_OPTIONS \$TFTP_DIRECTORY'
+
+			[Install]
+			WantedBy=multi-user.target
+		EOF
+
+		service refresh || return
+		service restart tftpd-hpa || return
+	fi
+
+	nomadRegisterApp "tftp" "tftpd-hpa"
 }
 
 TriblerInstall() { run --name "Tribler" "shareware/tribler/Tribler_7.2.2_x64.exe"; } # https://www.tribler.org/
