inst: updates

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1,4 +1,4 @@
-consulServiceCheck#!/usr/bin/env bash
+#!/usr/bin/env bash
 . AppControl.sh || exit
 . script.sh || exit
 . color.sh || exit
@@ -1912,9 +1912,8 @@ AppHostHardwareInstall()
 	local commonHw="LogitechOptions"
 
 	case "$hostname" in
-		bc) i IntelChipset IntelThunderboltDriver $commonHw;;
+		bc) i $commonHw;; # IntelChipset IntelThunderboltDriver
 		flo|fun|jane|pants) i $commonHw;;
-		oversoul) i IntelChipset IntelThunderboltDriver $commonHw;;
 		rosie) i nVidiaDriver IntelThunderboltDriver IntelDriverUpdate RealtekCardReader $commonHw;;
 	esac
 }
@@ -1922,13 +1921,18 @@ AppHostHardwareInstall()
 AppHostSoftwareInstall()
 {
 	# base client software
-	local clientCommon="1Password 1PasswordCli CryFS dropbox obsidian office typora writage GitCore"
+	local clientCommon="1Password 1PasswordCli CryFS dropbox loom obsidian office typora writage GitCore"
 	local clientMac="$clientCommon alfred bartender BetterDisplay CleanMyMac moom MouseBoost numi PopClip rectangle shottr SoundSource spark"
 	local clientWin="$clientCommon"
 
 	local clientLaptop="$clientCommon WireGuard"
 	local clientLaptopMac="$clientLaptop batteries"
 	local clientLaptopWin="$clientLaptop"
+
+	local clientPersonalHardware="BalenaEtcher BrotherBrinter DellDisplayManager dymo Epson4760"
+	local clientPersonalCommon="DevCore GameCore CreativeCloud spotify $clientPersonalHardware"
+	local clientPersonalMac="$clientPersonalCommon flighty ValetCarControl"
+	local clientPersonalWin="$clientPersonalCommon hyperv Quicken thunderbird"
 
 	# base server software
 	local hostArg="$HOSTNAME" # for Consul and Nomad
@@ -1957,17 +1961,16 @@ AppHostSoftwareInstall()
 
 		# server
 		pi2) i HomebridgeWiggin || return;;
-		pi7) i PiSugarUps PoolTemperature PoolController PiSugarUps;; # pool pad
-		pi9) i HomebridgeWiggin unifi || return;;
-		pi11) i DomotzAgent || return;; 															# Domotz Agent cannot be on load balancer (conflicts with keepalived)
+		pi7) i GeekPiUps PoolTemperature PoolController;; # pool pad
+		pi9) i DomotzAgent HomebridgeWiggin unifi || return;; # Domotz Agent cannot be on load balancer (conflicts with keepalived)
 
 		# Mac
-		ender) i 1Password 1PasswordCli amphetamine apache dymo FreeFileSync;;
-		flo|fun) i DriveTime flighty ValetCarControl;;
+		ender) i amphetamine dymo;;
+		flo|fun) i  $clientPersonalMac DriveTime;;
 		jane|pants) i BetterTouchTool;;
 
 		# Windows
-		bc|rosie) i Quicken thunderbird;;
+		bc|rosie) i $clientPersonalWin;;
 	esac
 }
 
@@ -3076,15 +3079,11 @@ DebianSudoSecurePathInstall() # add /usr/local/data/bin to the sudo secure path
 # development
 #################################################
 
-DevAllInstall() { i DevCore CruiseControlTray fiddler insomnia LinqPad MarkdownView postman snyk just; }
+DevAllInstall() { i DevCore DevMore CruiseControlTray fiddler insomnia LinqPad MarkdownView postman snyk just; }
 DevIdeAllInstall() { i JetBrains VisualStudioCode; }
 
-DevCoreInstall()
-{
-	header "Development Core"
-	i GitCore JetBrains VisualStudioCode || return
-	i fiddler postman MarkdownView RichCli || return
-}
+DevCoreInstall() { header "Development Core" && i docker JetBrains VisualStudioCode; }
+DevCoreMoreInstall() { header "Development Core More"; i fiddler postman RichCli; }
 
 MarkdownViewInstall() { run --name "Markdown View" --store "9PJ021LR0M3G"; }
 FiddlerInstall() { run --header "Fiddler" "other/Telerik/Fiddler/Fiddler Everywhere 0.10.2.exe|fiddler-mac.zip|fiddler-linux.zip"; } # http://www.telerik.com/fiddler
@@ -3833,6 +3832,7 @@ RsyslogInstall()
 #################################################
 
 GameAllInstall() { i GameIcon EpicGames Oculus Origin Steam thunderstore Uplay; }
+GameCoreInstall() { i steam; }
 GameIconInstall() { runCheck="true"; }
 GameIconFinalWin() { gameIconsWin && i OculusFinal OriginFinal SteamFinal ThunderstoreFinal UplayFinal; }
 
@@ -4385,22 +4385,22 @@ BrotherPrinterInstall()
 	local setup="$dir/Setup.exe"
 
 	# decrompress setup - the compressed executable does not run properly from WSL
-	# if [[ ! -f "$setup" ]]; then
-	# 	findFile "hardware/Brother/MFC-L2740DW/setup/install.zip" || return # removed driver/ps|pcfaxtx
-	# 	unzip "$file" -d "$(PlatformTmp)"
-	# fi
+	if [[ ! -f "$setup" ]]; then
+		findFile "hardware/Brother/MFC-L2740DW/setup/install.zip" || return # removed driver/ps|pcfaxtx
+		unzip "$file" -d "$(PlatformTmp)"
+	fi
 
-	# # copy custom setup options
-	# findFile "hardware/Brother/MFC-L2740DW/setup/Brinst_Common.ini" || return
-	# cp "$file" "$dir" || return
+	# copy custom setup options
+	findFile "hardware/Brother/MFC-L2740DW/setup/Brinst_Common.ini" || return
+	cp "$file" "$dir" || return
 
-	# # run setup
-	# elevate "$setup" || return
+	# run setup
+	elevate "$setup" || return
 	pause
+
+	# cleanup
 	rm -fr "$base" || return
 	runCheck="true"
-
-	return 0
 }
 
 BrotherPrinterFinalWin()
@@ -4431,7 +4431,7 @@ CanonCameraFinalWin()
 CorsairUtilityEngineInstall()
 {
 	header "Corsair Utility Engine (CUE)" # https://www.corsair.com/us/en/downloads
-	run "hardware/Corsair/Utility Engine/iCUESetup_4.28.174_release.msi" || return
+	run "hardware/Corsair/Utility Engine/Install iCUE.exe" || return
 }
 
 CorsairUtilityEngineProfile() { profile restore default --app "CorsairUtilityEngine" --method "$UADATA/../Roaming/Corsair/CUE4"; }
@@ -4484,7 +4484,7 @@ DasKeyboardFinalWin()
 	registry 32 delete "run/Das Keyboard Q" || return # C:\Users\jjbutare\AppData\Local\das-keyboard-q\das-keyboard-q.exe
 }
 
-DellDisplayManagerInstall() { run --header "Dell Display Manager" "hardware/Dell Display Manager/setup/ddmsetup.exe|DDPM_Installer.pkg" --elevate; } # https://www.dell.com/support/home/en-us/product-support/product/dell-u4021qw-monitor/drivers
+DellDisplayManagerInstall() { run --header "Dell Display Manager" "hardware/Dell/Display Manager/setup/ddmsetup.exe|DDPM_Installer.pkg" --elevate; } # https://www.dell.com/support/home/en-us/product-support/product/dell-u4021qw-monitor/drivers
 DellDisplayManagerProfile() { DellDisplayManager $noPrompt profile restore default; }	
 
 DellDisplayManagerFinalWin()
@@ -5844,8 +5844,8 @@ iTunesFinalWin()
 PlexInstall()
 {
 	header "PLEX" # https://www.plex.tv/media-server-downloads/
-	run "other/PLEX/PlexMediaServer-1.32.5.7349-8f4248874-x86_64.exe|PlexMediaServer-1.32.5.7349-8f4248874-universal.zip" || return
-	run "other/PLEX/Plex-1.78.2.3975-c5bd0cbb-x86_64.exe|Plex-1.78.2.3975-c5bd0cbb-universal.zip" || return
+	local v="PlexMediaServer-1.32.8.7639-fb6452ebf"; run "other/PLEX/$v-x86_64.exe|$v-universal.zip" || return
+	local v="Plex-1.85.0.4071-21128b56" run "other/PLEX/$v-x86_64.exe|$v-universal.zip" || return
 }
 
 PlexFinalWin() { mergeDir "$pp/Plex" "$pp/Media/Other"; }
@@ -7002,13 +7002,13 @@ TfsCliInstall()
 OfficeInstall()
 {
 	header "Office 365"
-	local v="16.0.15028.20204"; IsPlatform mac && v="16.47" # https://stores.office.com/myaccount/advancedinstalls.aspx
+	local v="16.0.15028.20204"; IsPlatform mac && v="16.47" # https://account.microsoft.com/services/microsoft365/details?OCID=cmmly2nfa36&openInstall=true&refd=www.office.com
 
 	# check if installed
 	word IsInstalled && [[ ! $force && "$(word version)" == "$v" ]] && return
 
 	# install	
-	run "other/Microsoft/office/OfficeSetup.exe|Microsoft_365_and_Office_16.72.23040900_Installer.pkg" || return
+	run "other/Microsoft/office/O365HomePremRetail.img|Microsoft_365_and_Office_16.72.23040900_Installer.pkg" || return
 	waitForInstallWin "$pp/Word.lnk"
 }
 
@@ -9808,7 +9808,7 @@ FortuneInstall() { InPath fortune && return; run --python-global "fortune-lite";
 FxInstall() {	run --node-system fx; }
 JqInstall() { run --header "jq" --package "jq"; }
 LolcatInstall() {  InPath lolcat && return; run --python-global "lolcat"; }
-RichCliInstall() { InPath rich && return; run --python-gloval "rich-cli"; }
+RichCliInstall() { InPath rich && return; run --python-global "rich-cli"; }
 
 #################################################
 # utility - GUI
@@ -10771,11 +10771,6 @@ WinConfigInstall()
 	# taskbar	 
  	powershell "$(utw "$DATA/setup/TaskbarClean.ps1")" || return
 
-	# host specific
-	case "$HOSTNAME" in
-		oversoul) service demand sysmain;; # superfetch (sysmain) causes slugishness on oversoul
-	esac
-
 	return 0
 }
 
@@ -11147,7 +11142,6 @@ DriveTimeInstall()
 {
 	i GlobalProtectVpn PortableApps || return
 	i AzureCli slack teams TfsCli || return
-	i docker VisualStudioCode || return
 }
 
 DriveTimeFinalWin()
