inst AppEnd: re-organize

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -685,7 +685,7 @@ installInit()
 	# isInstallable	
 	all=(bin download final help register update) # install
 	all+=(certificates FileSharing FileSharingClient FileSharingServer firewall fonts IconCleanup PackageManagement setup) # platform
-	all+=(AppDir DriveTime envoy FileServer hostname PartitionManagement printers software store)	
+	all+=(AppDir DriveTime envoy FileServer hostname HostUpdate PartitionManagement printers software store)	
 	deb=() deb64=() debRh=() mac=() macDeb=() macDebRh=() rhel=() ubuntu=() winElevated=() win=()
 	
 	# Artifical Intelligence
@@ -2593,9 +2593,8 @@ AppEndInstall()
 {
 	header "Application End"
 	noExclude="--no-exclude" i --cache final || return
-	i --cache help IconCleanup || return
-	RunCache "install-app-common-end-host-update" HostUpdate || return
-	RunCache "install-app-common-end-platform" RunPlatform appEnd || return
+	i --cache help IconCleanup HostUpdate || return
+	RunPlatform appEnd || return
 }
 
 appEndWin() { header "Application End Windows"; $rm "$ud/bootstrap.cmd" && $rm "$up/Startup/bootstrap.cmd"; }
@@ -8881,7 +8880,7 @@ WiresharkFinalWin() { $mv "$pp/Wireshark.lnk" "$pp/Operating System"; }
 # Network System
 #################################################
 
-NetworkAllSystemInstall() { i hosts IpDynamic IpStatic netplan NetworkManager NicUsb wifi; }
+NetworkAllSystemInstall() { i hosts HostName HostUpdate IpDynamic IpStatic netplan NetworkManager NicUsb wifi; }
 
 HostsInstall()
 {
@@ -8935,6 +8934,40 @@ hostsLine()
 	line+="$hostname"
 
 	echo "$line"
+}
+
+HostUpdateInstall() {	header "Host Update"; HostUpdate; }
+
+HostnameInstall()
+{	
+	# Docker hostname must be set in the containers config.vs.json
+	IsDocker && return
+	
+	# return if needed
+	if ! UpdateNeeded "install-hostname"; then
+		hostname="$(UpdateGetForce "hostname")" || return
+		return
+	fi
+
+	header "Hostname"
+
+	os name set # use return values
+	case $? in
+
+		# name changed
+		0) 
+			UpdateDone "install-hostname" || return
+			rebootNeeded="true"; UpdateSet "reboot-needed"
+			hostname="$(UpdateGetForce "hostname")" || return
+			;;
+
+		# name unchanged
+		1) UpdateDone "install-hostname"; return;;
+
+		# error
+		*) return 1;;
+
+	esac
 }
 
 IpDynamicInstall()
@@ -14924,7 +14957,7 @@ xWslInstall()
 # other
 #################################################
 
-OtherAllInstall() { i hostname RsiGuard solumina stamps VirginPulse; }
+OtherAllInstall() { i RsiGuard solumina stamps VirginPulse; }
 BlackBerryInstall() { header "BlackBerry"; }
 BlackBerryFinalWin() { $mv "$up/BlackBerry AtHoc Desktop Notifier.lnk" "$up/Applications" && $mv "$pp/BlackBerry AtHoc Desktop Notifier.lnk" "$pp/Applications"; }
 CamoStudioInstall() { run --header "Camo Stusio" "other/Reincubate/Camo/camo-macos-latest.zip"; } # https://reincubate.com/camo/#downloads
@@ -14932,38 +14965,6 @@ RsiGuardInstall() { header "RSI Guard"; }
 RsiGuardFinalWin() { mergeDir "$pp/RSIGuard" "$ao"; }
 VirginPulseInstall() { header "Virgin Pulse"; }
 VirginPulseFinalWin() { $mv "$up/iSync.lnk" "$up/Applications" && $rm "$ud/iSync.lnk"; }
-
-HostnameInstall()
-{	
-	# Docker hostname must be set in the containers config.vs.json
-	IsDocker && return
-	
-	# return if needed
-	if ! UpdateNeeded "install-hostname"; then
-		hostname="$(UpdateGetForce "hostname")" || return
-		return
-	fi
-
-	header "Hostname"
-
-	os name set # use return values
-	case $? in
-
-		# name changed
-		0) 
-			UpdateDone "install-hostname" || return
-			rebootNeeded="true"; UpdateSet "reboot-needed"
-			hostname="$(UpdateGetForce "hostname")" || return
-			;;
-
-		# name unchanged
-		1) UpdateDone "install-hostname"; return;;
-
-		# error
-		*) return 1;;
-
-	esac
-}
 
 PortableAppsInstall()
 {
