inst bootstrapStartWin: run win permissions early

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -3117,6 +3117,9 @@ bootstrapStartWin()
  	# Hidden Start - install early if possible to prevent excessive UAC dialogs
 	canElevate && ! IsDomainRestricted && { winPathFix && i HiddenStartConfigure || return; }
 
+	# Windows permissions - set early so icon updates do not fail
+	i --no-header WinPermissions || return
+
 	# finalize WSL installation now to enable Systemd and mirrored networking on next restart
 	{ WslFinalWin && WslProfile; } || return
 
@@ -13438,14 +13441,11 @@ HiddenStartInstall() { run --header "Hidden Start" "platform/win/NTwind/Hstart_5
 HiddenStartFinalWin()
 {
 	# copy programs
-	local d="$P/Hidden Start/"
-	cp "$d/HstartUI.exe" "$d/hstart"* "$PLATFORM_PATH" || return
+	local dir="$P/Hidden Start/"
+	[[ -d "$dir" ]] && { cp "$dir/HstartUI.exe" "$dir/hstart"* "$PLATFORM_PATH" || return; }
 
 	# configure
 	i HiddenStartConfigure || return
-
-	# ensure Windows permissions are set so icon update does not fails
-	i --no-header WinPermissions || return
 
 	# update icons
 	mergeDir "$pp/Hidden Start" "$oo" || return
