function.sh qgrep: rename to sqgrep

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1716,7 +1716,7 @@ runXip()
 urlCheck()
 {
 	local url="$1" check="${2:-^HTTP/2 200\|HTTP/1.1 200 OK}"
-	curl --silent --head --location "$url" | qgrep "$check"
+	curl --silent --head --location "$url" | sqgrep "$check"
 }
 
 versionAllowAlpha() { IsInArray --case-insensitive "$1" alphaVersions; }
@@ -2481,7 +2481,7 @@ bootstrapPi()
 
 	# locale
 	local locale="$(ConfigGet "locale")"
-	! cat /etc/default/locale | qgrep "$locale" && { sudo raspi-config nonint do_change_locale $locale || return; export LOCALE="$locale"; }
+	! cat /etc/default/locale | sqgrep "$locale" && { sudo raspi-config nonint do_change_locale $locale || return; export LOCALE="$locale"; }
 
 	# other setup
 	i PiSwap || return
@@ -2883,7 +2883,7 @@ DebianFileSharingInstall()
 
 	! InPath smbd && { pkg samba || return; } # service
 	! InPath smbclient && { pkg smbclient || return; }
-	! PackageListInstalled | qgrep "^samba-vfs-modules:" && { pkg samba-vfs-modules || return; }
+	! PackageListInstalled | sqgrep "^samba-vfs-modules:" && { pkg samba-vfs-modules || return; }
 
 	local workgroup; workgroup="$(ConfigGet "workgroup")"
 	if [[ "$(network workgroup name)" != "$workgroup" ]]; then
@@ -3207,7 +3207,7 @@ PlaywrightInstall()
 	[[ ! $force && -d "$dir" ]] && return
 
 	# install from Git repository if possible
-	if IsAvailable git && GitHelper remote ls git | qgrep "^playwright$"; then
+	if IsAvailable git && GitHelper remote ls git | sqgrep "^playwright$"; then
 		GitHelper clone git playwright && cd "$dir" && yarn install
 	else
 		run --yarn --header "Playwright" playwright
@@ -3770,7 +3770,7 @@ DbusInstall()
 	IsPlatform wsl && [[ -f "$file" ]] && ${G}grep --quiet "whoopsie" "$file" && { echo "Remove whoopsie policy..."; sudoe "$file"; }
 
 	# mac
-	IsPlatform mac && brew services list | ${G}grep '^dbus ' | qgrep none && { brew services start dbus || return; }
+	IsPlatform mac && brew services list | ${G}grep '^dbus ' | sqgrep none && { brew services start dbus || return; }
 
 	# start
 	app dbus "${globalArgs[@]}" && DbusConf
@@ -5268,7 +5268,7 @@ MacDockCleanupInstall()
 	echo -n "cleaning dock..."
 	local args=() apps=("App Store" Contacts Calendar FaceTime Freeform Launchpad Mail Maps Messages Music News Notes Photos Podcasts Reminders Safari "System Preferences" TV )
 	for app in "${apps[@]}"; do		
-		dockutil --list | qgrep "^$app" && { echo -n "$app..."; dockutil --remove "$app" || return; }
+		dockutil --list | sqgrep "^$app" && { echo -n "$app..."; dockutil --remove "$app" || return; }
 	done
 	echo "done"
 }
@@ -6016,7 +6016,7 @@ DomotzAgentInstall()
 	
 	# install
 	local name="domotzpro-agent-publicstore"
-	if ! snap list | qgrep '^domotzpro-agent-publicstore'; then
+	if ! snap list | sqgrep '^domotzpro-agent-publicstore'; then
 		sudoc snap install "$name" || return
 	  sudo snap connect $name:firewall-control || return
 	  sudo snap connect $name:network-observe || return
@@ -6026,12 +6026,12 @@ DomotzAgentInstall()
 	fi
 
 	# configure firewall
-	InPath ufw && sudo ufw status | qgrep " active" && { sudo ufw allow 3000 || return; }
+	InPath ufw && sudo ufw status | sqgrep " active" && { sudo ufw allow 3000 || return; }
 
 	# configured allowed interface
 	local interface; interface="$(GetInterface)" || return
 	echo "Checking if '$interface' is the allowed interface..."
-	if ! DomotzHelper api network/interfaces-policy | qgrep "\"$interface\""; then
+	if ! DomotzHelper api network/interfaces-policy | sqgrep "\"$interface\""; then
 		echo "Setting '$interface' to the allowed interface..."
 		DomotzHelper api put network/interfaces-policy '{ "policy": "allow", "rules": [ "'$interface'" ] }' || return
 	fi
@@ -6258,13 +6258,14 @@ NetbootxyzDockerInstall()
 
 netbootxyzDockerDebian()
 {
+	# installers
 	local dir="$ADATA/netbootxyz/installers"
 	local file="/etc/samba/smb.conf" restart
 
 	sudoc chown "$USER" "$dir" && return
 	sudoc chgrp "$USER" "$dir" && return
 
-	if ! ${G}grep --quiet "\[installers\]" "$file"; then
+	if ! qgrep "\[installers\]" "$file"; then
 		cat <<-EOF | sudo ${G}tee -a "$file" > /dev/null || return
 
 			[installers]
@@ -6548,12 +6549,12 @@ wifiUbuntu()
 	iwconfig $interface >& /dev/null && { sudo ifconfig $interface up || return; }
 		
 	# connect to a wireless network
-	if iwconfig |& qgrep "Not-Associated"; then
+	if iwconfig |& sqgrep "Not-Associated"; then
 
 		# get SSID
 		local networks; networks="$(WifiNetworks)" || return
 		local defaultNetwork="$(ConfigGet "wifi")"
-		! echo "$networks" | qgrep "^$defaultNetwork$" && defaultNetwork="" # default network not found
+		! echo "$networks" | sqgrep "^$defaultNetwork$" && defaultNetwork="" # default network not found
 		[[ ! $defaultNetwork ]] && defaultNetwork="$(WiFiNetworks | shead -1)"
 		local network; network="$(ask text "What Wi-Fi network would you like to connect to ($defaultNetwork)")" || return
 		[[ ! $network ]] && network="$defaultNetwork"
@@ -7573,7 +7574,7 @@ PythonAsdfInstall()
 	esac
 
 	# install plugin
-	! asdf plugin list | qgrep "python" && { asdf plugin add python || return; }
+	! asdf plugin list | sqgrep "python" && { asdf plugin add python || return; }
 
 	# install latest python
 	asdf install python latest || return
@@ -8097,7 +8098,7 @@ RubyAsdfInstall()
 	i --no-header asdf || return
 
 	# install Ruby plugin
-	! asdf plugin list | qgrep ruby && { asdf plugin add ruby || return; }
+	! asdf plugin list | sqgrep ruby && { asdf plugin add ruby || return; }
 
 	# install latest Ruby
 	asdf install ruby latest || return
@@ -8132,7 +8133,7 @@ RubyRvmInstall()
 
 	# ruby
 	local version="3.0"
-	if ! InPath ruby || ! ruby --version | qgrep "$version"; then
+	if ! InPath ruby || ! ruby --version | sqgrep "$version"; then
 		rvm install "$version" || return
 		. "$HOME/.rvm/scripts/rvm" || return # add ruby and gem to the path in current shell
 		rvm use --default "$version" || return
@@ -8377,7 +8378,7 @@ BashProfile()
 
 ZshInstall()
 {
-	IsPlatform mac && ! which zsh | qgrep "homebrew" && force="--force" # force if the Homebrew Zsh is not installed
+	IsPlatform mac && ! which zsh | sqgrep "homebrew" && force="--force" # force if the Homebrew Zsh is not installed
 	run --name="Z shell" --package zsh && forceAllParts="true"
 }
 
@@ -8705,7 +8706,7 @@ sshServerEntware()
 
 sshServerMac()
 {
-	sudoc systemsetup -getremotelogin | qgrep "Remote Login: On" && return
+	sudoc systemsetup -getremotelogin | sqgrep "Remote Login: On" && return
 	sudo systemsetup -setremotelogin on
 }
 
@@ -8852,7 +8853,7 @@ storeCurrentVersionMac() { storeCheck && mas search "$1" | rev | cut -d" " -f 1 
 
 # storeIsInstalled ID - return true if the application with store ID is installed
 storeIsInstalled() { RunPlatform storeIsInstalled "$1"; }
-storeIsInstalledMac() { storeCheck && mas list | qgrep "^$1 "; }
+storeIsInstalledMac() { storeCheck && mas list | sqgrep "^$1 "; }
 storeIsInstalledWin() { return 1; }
 
 #################################################
@@ -9003,7 +9004,7 @@ warpFindUrl()
 
 	for (( i = 5; i >= 0; i-- )); do
 		tryUrl="$(eval echo $url)"
-		curl --silent "$tryUrl" --head | qgrep "404" && { logp1 "."; continue; }
+		curl --silent "$tryUrl" --head | sqgrep "404" && { logp1 "."; continue; }
 		logp1 "found\n"; echo "$tryUrl"; return
 	done
 
@@ -9348,7 +9349,7 @@ rtcPiKernel()
 	pkg python3-smbus || return
 
 	# check for RTC chip
-	! sudoc i2cdetect -y 1 | qgrep -E "( 68|UU )" && { pause ScriptErr 'RTC chip not detected, try rebooting'; return 1; }
+	! sudoc i2cdetect -y 1 | sqgrep -E "( 68|UU )" && { pause ScriptErr 'RTC chip not detected, try rebooting'; return 1; }
 
 	# update config.txt if needed
 	local file="/boot/firmware/config.txt"
@@ -9365,7 +9366,7 @@ rtcPiKernel()
 	fi
 
 	# check for RTC
-	! sudo i2cdetect -y 1 | qgrep -E "UU " && { ScriptErr 'RTC chip not detected'; return 1; }		
+	! sudo i2cdetect -y 1 | sqgrep -E "UU " && { ScriptErr 'RTC chip not detected'; return 1; }		
 
 	# configure hwclock-set - comment out return
 	local file="/lib/udev/hwclock-set"
@@ -9383,7 +9384,7 @@ timezoneMessage() { hilight "Setting the timezone to '$timezone'..."; }
 timezoneDebian()
 {
 	{ [[ ! $timezone ]] || IsPlatform win; } && return
-	[[ ! $force ]] && cat "/etc/timezone" |& qgrep "$timezone" && return
+	[[ ! $force ]] && cat "/etc/timezone" |& sqgrep "$timezone" && return
 
 	timezoneMessage
 	DEBIAN_FRONTEND=noninteractive sudoc apt install -y tzdata || return
@@ -9396,7 +9397,7 @@ timezoneDebian()
 timezonePi()
 {
 	[[ ! $timezone ]] && return
-	[[ ! $force ]] && cat /etc/timezone | qgrep "$timezone" && return
+	[[ ! $force ]] && cat /etc/timezone | sqgrep "$timezone" && return
 
 	timezoneMessage; sudo raspi-config nonint do_change_timezone "$timezone"
 }
@@ -9871,7 +9872,7 @@ HiddenStartFinalWin()
 	i HiddenStartConfigure || return
 }
 
-isHiddenStartConfigued() { schtasks.exe | qgrep "HstartUAC-x64"; }
+isHiddenStartConfigued() { schtasks.exe | sqgrep "HstartUAC-x64"; }
 
 HiddenStartConfigureInstall()
 {
@@ -10123,7 +10124,7 @@ DockerInstall()
 	docker run "hello-world"
 
 	# create the user-network
-	! docker network ls | qgrep user-network && { sudoc docker network create "user-network" || return; }
+	! docker network ls | sqgrep user-network && { sudoc docker network create "user-network" || return; }
 
 	return 0
 }
