inst: fix compressed file install issues

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -263,12 +263,15 @@ run() # run PROGRAM [OPTIONS...]
 		shift; shift; shift;
 	fi
 
-	# destination argument
-	local dest
-	if [[ "$1" == @(-d|--dest) ]]; then
-		dest="$2"
-		shift 2
-	fi
+	# arguments
+	while (( $# != 0 )); do
+		local shift=1
+		case "$1" in "") : ;;
+			-d|--dest|-d=*|--dest=*) ScriptOptGet "dest" "$@";;
+			*) break;;
+		esac
+		shift $shift
+	done
 
 	# return if not running
 	[[ $noRun ]] && return;
@@ -1052,7 +1055,7 @@ firefoxInstall()
 	IsPlatform debian && firefox IsInstalled && ! firefox program | grep -q "$P" && isInstalled="true"
 
 	# https://www.mozilla.org/en-US/firefox/all/
-	local v="83.0"
+	local v="85.0.2"
 	if IsPlatform pixel,pi; then
 		pkg firefox-esr || return
 	elif IsPlatform PiKernel; then
@@ -1060,7 +1063,7 @@ firefoxInstall()
 	elif IsPlatform mac,arm; then
 		run "other/Mozilla/Firefox/Firefox 84.0b8.dmg" || return # beta build 84 has support for Apple M1 ARM based silicon
 	elif [[ ! $isInstalled ]]; then
-		run "other/Mozilla/Firefox/" -p "Firefox Setup $v.msi" "Firefox $v.dmg" "firefox-$v.tar.bz2" || return # setup fails with names in spaces
+		run "other/Mozilla/Firefox/" -p "Firefox Setup $v.msi" "Firefox $v.dmg" "firefox-$v.tar.bz2" --dest="firefox" || return # setup fails with names in spaces
 	fi
 
 	echo; firefox $noPrompt profile restore default || return
@@ -2324,7 +2327,7 @@ BalenaEtcher() # disc image burner
 	run "$dir/" -p "balenaEtcher-Setup-$v.exe" "balenaEtcher-$v.dmg" "balena-etcher-electron-$v-linux-x64.zip" || return
 
 	v="v12.25.1" #
-	run "$dir/balena-cli-$v-" -p "windows-x64-standalone.zip" "macOS-x64-standalone.zip" "linux-x64-standalone.zip" --dest "$P/balena-cli" --elevate || return
+	run "$dir/balena-cli-$v-" -p "windows-x64-standalone.zip" "macOS-x64-standalone.zip" "linux-x64-standalone.zip" --dest "balena-cli" --elevate || return
 
 	if IsPlatform win; then
 		$mv "$up/balenaEtcher.lnk" "$up/Applications" || return
@@ -3571,9 +3574,9 @@ openJdkInstall()
 	package default-jdk
 }
 
-tomcat10Install() { local version=10.0.2 tomcatInstall; }
-tomcat9Install() { local version=9.0.43 tomcatInstall; }
-tomcat7Install() { local version=7.0.108 tomcatInstall; }
+tomcat10Install() { version=10.0.2 tomcatInstall; }
+tomcat9Install() { version=9.0.43 tomcatInstall; }
+tomcat7Install() { version=7.0.108 tomcatInstall; }
 
 tomcatInstall()
 {
@@ -5033,7 +5036,7 @@ SublimeInstall()
 	local linux="sublime_text_3_build_${v}_x64.tar.bz2"
 	(( v == vBeta )) && linux="sublime-text_build-${v}_${architecture}.deb"
 
-	run "other/Sublime/setup/" -p "Sublime Text Build $v x64 Setup.exe" "Sublime Text Build $v.dmg" "$linux" "${args[@]}" || return
+	run "other/Sublime/setup/" -p "Sublime Text Build $v x64 Setup.exe" "Sublime Text Build $v.dmg" "$linux" "${args[@]}" --dest="sublime_text" || return
 
 	if IsPlatform win; then
 		makeLink --merge --hide "$winAppData/Dash" "$winDoc/Dash" || return
@@ -5102,7 +5105,7 @@ AutoHotKeyInstall()
 	AutoHotKey close || return
 
 	# https://www.autohotkey.com/ https://autohotkey.com/download/2.0/
-	run "shareware/AutoHotKey/image/AutoHotkey_2.0-a122-f595abc2.zip" --dest "$P/AutoHotKey" --elevate || return
+	run "shareware/AutoHotKey/image/AutoHotkey_2.0-a122-f595abc2.zip" --dest "AutoHotKey" --elevate || return
 
 	printf "${GREEN}Starting AutoHotKey...${RESET}"
 	AutoHotKey startup || return
