inst AMD Chipset: handle installer always fails

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -6357,7 +6357,9 @@ AmdHardwareAllInstall() { i AmdChipset AmdGpu; }
 AmdChipsetInstall()
 {
 	local v="7.11.26.2142" vName="AMD Chipset Software" # https://www.amd.com/en/support/downloads/drivers.html/chipsets/laptop-chipsets/amd-ryzen-and-athlon-mobile-chipset.html
-	run --name "AMD Chipset" "hardware/AMD/chipset/AMD_Chipset_Software_$v.exe" --version-name="$vName" --version="$v" --elevate || return # fails with --nsis (silent install)
+	local result; run --name "AMD Chipset" "hardware/AMD/chipset/AMD_Chipset_Software_$v.exe" --version-name="$vName" --version="$v" --elevate --nsis; result="$?"
+	log1 "the installation failed with error $result (expected), checking if the installation was successful..."
+	PackageIsInstalledWin "$versionName"
 }
 
 # AmdGpu - auto-detects GPU and installs
@@ -14414,7 +14416,7 @@ WinAuthInstall()
 		echot "\
 - Facial recognition (Windows Hello)
 - PIN (Windows Hello)
-- Dynamic lock, check Allow Windows to automatically lock your device when your'e away
+- Dynamic lock, check Allow Windows to automatically lock your device when you're away
 - check Shows account details such as my email address on the sign-in screen"
 		pause
 	fi
