script changes

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -1004,7 +1004,7 @@ vs13()
 	run "$vs/setup/other/en_visual_studio_2013_sdk_x86_3009047.exe" || return
 
 	# extensions
-	run "$vs/extension/NuGet.Tools.2013.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca
+	#run "$vs/extension/NuGet.Tools.2013.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/4ec1526c-4a8c-4a84-b702-b21a8f5293ca
 	run "$vs/extension/NUnitVisualStudioTestAdapter-1.0.vsix" || return # requires ReSharper disabled, https://launchpad.net/nunit-vs-adapter/+download, http://visualstudiogallery.msdn.microsoft.com/6ab922d0-21c0-4f06-ab5f-4ecd1fe7175d?SRC=VSIDE
 	run "$vs/extension/WebEssentials2013.vsix" || return # http://visualstudiogallery.msdn.microsoft.com/56633663-6799-41d7-9df7-0f2a504ca361
 
@@ -1040,10 +1040,9 @@ VsFinal()
 	$makeDir "$_Code/test/vs$vsName"
 	
 	if ask "Initialize Visual Studio"; then
+		echo "- (optional) Sign In, <Microsoft Live account>"
 		echo "- Choose your default environment settings=Visual C# Development Settings"
-		echo "- Sign In, <Microsoft Live account>"
 		echo "- Development Settings=Visual C#"
-		echo "- Choose your color theme=Blue or Light"
 		echo "- Close Visual Studio"
 		VisualStudio start; pause
 	fi
@@ -1345,12 +1344,12 @@ iisInstall()
 	fi
 
 	echo "Updating services..."
-	service manual FTPSVC || return
+	service exist FTPSVC && { service manual FTPSVC || return; }
 
 	if [[ $client ]] && ask "Set IIS services to run manually"; then
-	  service manual IISADMIN || return
-	  service manual w3svc || return
-	  service manual AppHostSvc || return
+	  service exist IISADMIN && { service manual IISADMIN || return; }
+	  service exist w3svc && { service manual w3svc || return; }
+	  service exist AppHostSvc && { service manual AppHostSvc || return; }
 	fi
 
 	echo "Updating icons..."
@@ -1383,7 +1382,7 @@ SqlServerInstall()
 	local base="Microsoft/SQL Server"
 	printf "**************************************************\n* SQL Server 2012\n**************************************************\n"
 	
-	echo; echo "Checking IIS (required for reporting services)..."; IisCheck || return
+	echo; echo "Checking for IIS (required for reporting services)..."; IisCheck || return
 
 	echot "\
 Note: Logs are in \"$P/Microsoft SQL Server/110/Setup Bootstrap/Log\"
@@ -1439,7 +1438,6 @@ Note: Logs are in \"$P/Microsoft SQL Server/110/Setup Bootstrap/Log\"
 
 	if [[ $database ]]; then 
 		ask "Update server configuration" && { SsServerConfig || return; }
-		ask "Update firewall" && { SsFirewall || return; }
 		#ask "Update mail configuration" && { SsMailConfig || return; }
 		#ask "Update reporting server configuration" && { SsReportServerConfig || return; }
 	fi
@@ -1462,10 +1460,7 @@ SsServerConfig()
 	echo "- Object Explorer, Server, Properties, Memory, Maximum server memory=256"
 	SqlServer studio || return
 	pause
-}
 
-SsFirewall()
-{
 	echo "Updating firewall..."
 	$firewall rule add "SQL Server" dir=in action=allow protocol=TCP localport=1433 profile=private \
 		program="$(utw "$P/Microsoft SQL Server/MSSQL10.MSSQLSERVER/MSSQL/Binn/sqlservr.exe")" || return
@@ -1500,13 +1495,12 @@ SsManagementStudioConfig()
 	- View: Registered Servers at top left, Solution Explorer at bottom right
 	- Tools, Options
 	  - Environment
-	    - 20 items shown
+	    - General, 20 items shown
 	    - Startup, At startup Open empty environment
 	  - Text Editor
 	    - All Languages, check Line numbers
 	    - (if using SQL Prompt) Transact-SQL, uncheck Auto list members
 	    - Editor Tab and Status Bar, Tab Text, all but Include File Name to False
-	  - (optional) Source Control, Current source control plug-in=Team Foundation Server MSCCI Provider
 	- Help, Yes"
 	SqlServer studio || return; pause
 }
@@ -1515,7 +1509,7 @@ SsFinal()
 {
 	echo "Creating sql directory..."
 	local dir="$udata/sql"; $makeDir "$dir"
-	$makeShortcut "$_CloudData/sql" "$dir/cloud.lnk" || return
+	[[ -d "$_CloudData/sql" ]] && { $makeShortcut "$_CloudData/sql" "$dir/cloud.lnk" || return; }
 
 	echo "Moving data folders..."
 	local dir="$udata/SQL Server Management Studio"
