bootstrap updates
- CopyDir: fix rsync exclude defaults
- function.sh: if readlink is used do not resolve links if the full path does not exist
- inst bootstrapQnap: cleanup autorun script
- unc
  - mount: add support for QNAP
  - cleanupMountDir: handle invalid mount directories

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -330,7 +330,7 @@ isInstallable()
 	# app name checks
 	[[ "$check" =~ ^(.*all|bootstrap|.*core|ssh.*)$ ]] && return
 	[[ "$check" =~ ^(debian.*)$ ]] && IsPlatform debian && return
-	[[ "$check" =~ ^(linux.*)$ ]] && IsPlatform debian,linux|mac && return
+	[[ "$check" =~ ^(linux.*)$ ]] && IsPlatform debian,linux,mac && return
 	[[ "$check" =~ ^(mac.*)$ ]] && IsPlatform mac && return
 	[[ "$check" =~ ^(win.*)$ ]] && IsPlatform win && return
 
@@ -1160,25 +1160,12 @@ bootstrapQnap()
 	header "Bootstrap QNAP"
 
 	# autorun
-	if $force || UpdateNeeded "QnapAutorun"; then
+	if [[ $force ]] || UpdateNeeded "QnapAutorun"; then
 
 		local clip; clip="$(cat <<-EOF
-			mkdir /usr/etc/sudoers.d
-			echo "$USER ALL=(ALL) ALL" > "/usr/etc/sudoers.d/$USER"
-			echo "wsystem ALL=(ALL) ALL" > "/usr/etc/sudoers.d/wsystem"
-			echo "wsystem-local ALL=(ALL) ALL" > "/usr/etc/sudoers.d/wsystem-local"
-
 			sudo ln -s "/share/Public/documents/data" "/usr/local/data"
 			sudo ln -s "/share/homes/$USER" "$USERS/$USER" || return
-
-			grep -q "wiggin.conf" "/etc/config/apache/apache.conf" &&
-				echo "Include /etc/config/apache/extra/wiggin.conf" >> "/etc/config/apache/apache.conf"
-
-			grep -q "apache-http-compress.conf" "/etc/config/apache/apache.conf" &&
-				echo "Include /etc/config/apache/extra/apache-http-compress.conf" >> "/etc/config/apache/apache.conf"
-
 			true
-
 			EOF
 		)"
 
@@ -1188,12 +1175,8 @@ bootstrapQnap()
 		UpdateDone "QnapAutorun"
 	fi
 
-	# share root directory from admin uses to allow access $DATA from root share, this should be shared out as root
+	# share root directory from admin uses to allow access to $DATA from root share, this should be shared out as root
 	sudo MakeLink --symbolic "/" "/share/homes/admin/root" || return
-
-	# Apache
-	local dir="/etc/config/apache/extra"
-	[[ ! -f "$dir/wiggin.conf" ]] && { cp "$setupFiles/nas3.apache.wiggin.conf" "$dir/wiggin.conf" || return; }
 
 	return 0
 }
@@ -2185,6 +2168,7 @@ LinuxUtilitiesInstall()
 	pkg atop iotop iperf3 nethogs pv || return																# monitoring
 	pkg iproute2 fping mosh ncat nmap traceroute whois || return							# network, iproute2=ip
 	pkg daemonize || return																										# process
+	pkg shellcheck || return																									# script
 	pkg sox || return																													# sound (play)
 	pkg bat colordiff cowsay figlet fortune fortune-mod lolcat jq || return		# text, 44MB
 
@@ -5278,7 +5262,6 @@ BashInstall()
 	header "Bourne Again Shell"
 
 	i BashProfile || return
-	pkg shellcheck || return
 
 	# login shell
 	IsPlatform entware && { AddLoginShell "/opt/bin/bash" || return; }
@@ -5350,7 +5333,7 @@ ZshProfileInstall()
 
 ZplugInstall()
 {
-	IsPlatform pi && return # fails updating packages
+	IsPlatform pi,qnap && return # pi fails updating packages
 	pkg zsh zplug || return
 
 	# plugins
