inst iTermShellIntegration: cleanup ~/.bash_profile

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -853,6 +853,7 @@ platformUserAppData() { local d; d="$(GetPlatformVar "UDATA")/app" && makeDir "$
 rebootIfNeeded() { [[ ! $rebootNeeded ]] && return; rebootDo; }
 rebootDo() { SleepStatus "Rebooting in 10 seconds" 10 && power reboot; }
 registryDo() { ! CanElevate && return; registry "$@"; }
+removeLastEmptyLine() { sed -i '${/^$/d;}' "$1"; }
 rmSudo() { [[ ! -f "$1" ]] && return; sudoc ${G}rm -f "$1"; }
 serviceAutoStart() { service auto "$1" && service start "$1"; }
 serviceDemandStop() { service demand "$1" && service stop "$1"; }
@@ -10647,7 +10648,17 @@ iTermShellIntegrationInstall()
 {
 	header "iTerm Shell Integration"
 	[[ ! $force && -f "$HOME/.iterm2_shell_integration.zsh" ]] && return
-	curl -L "https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh" | bash
+	curl -L "https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh" | bash || return
+
+	# cleanup ~/.bash_profile
+	if IsBash; then
+		local file="$HOME/.bash_profile"
+		sed -i '/iterm2_shell_integration.bash/d' "$file" || return
+		removeLastEmptyLine "$file" || return
+		removeLastEmptyLine "$file" || return
+	fi
+
+	return 0
 }
 
 TerminatorInstall() { run --package terminator; }
