mac bootstrap fixes

diff --git a/inst b/inst
--- a/inst
+++ b/inst
@@ -15,7 +15,7 @@ init()
 	win=( ahk AutoHotKey AltTabTerminator AquaSnap CloseAllWindows CoreTemp DiskImager EdgeDeflector FileLocatorPro IntelDrivers IntelDriverUpdate Ninite npp Notepadpp RightClickEnhancer TidyTabs UltraMon vcxsrv WinScp xMing AjaSystemTest BlueStacks CPUZ DiskImager IntelExtremeTuning LgMonitor MarkdownView MozillaVpn NitroPdf nVidiaGeForceExperience PartitionAssistant pGina PowerPanel PowerrToys QuickBooks stamps TaskLayout TemperatureLogger Todoist Wallpaper4k WindowsAssessmentAndDeploymentKit )
 	macWin=( BlueSherpa CanonCamera CleanMy Cricut deezer Domotz DuetDisplay GreenShot JumpDesktop keybase LastPass LogitechOptions notion office origin PdfElement QnapExternalRaidManager qvr sonos xServer zoom )
 	macUbuntuWin=( BalenaEtcher bc BeyondCompare Dropbox JumpCloud StandardNotes steam sublime SublimeMerge TeamViewer )
-	macDebianWin=( colorls CredentialStore docker firefox fzf GitKraken LinuxNetworkUtilities PackageManagement SevenZip skype tmux UnifiControllerpkg )
+	macDebianWin=( colorls CredentialStore docker firefox fzf GitKraken LinuxNetworkUtilities PackageManagement SevenZip skype tmux UnifiControllerPackage )
 
 	# commands
 	cp="FileCommand cp"
@@ -84,7 +84,7 @@ args()
 	return 0
 }
 
-FinalInstall() { inst --no-prompt ccFinal dropboxFinal firefoxFinal thunderbirdFinal zoomFinal; }
+FinalInstall() { inst --no-prompt BeyondCompareFinal ccFinal dropboxFinal firefoxFinal thunderbirdFinal zoomFinal; }
 
 #################################################
 # Aliases
@@ -461,7 +461,7 @@ storeInstall()
 	fi
 
 	case "$PLATFORM" in
-		mac) InPath mas && mas open $id;;
+		mac) InPath mas && mas install $id;;
 		win) start RunProcess.exe ms-windows-store://pdp/?ProductId=$id;;
 	esac
 
@@ -537,9 +537,10 @@ appHost()
 	local hw="GigabyteThunderboltDriver"
 
 	case "$HOSTNAME" in
-		jane|pants) i $commonMac Dropbox notion office || return;;
+		ender|jane) i $commonMac bear CanaryMail Dropbox notion office || return;;
 		micro) i $commonPc Dropbox notion office || return;;
 		oversoul) i $commonPc $hw Dropbox dymo hp9020 iCloud notion office Quicken thunderbird UltraMon || return;;
+		pants) i $commonMac Dropbox notion office || return;;
 		pi1) i $homeServer || return;;
 		pi2) i $homeServer DomotzAgent || return; pkg salt-master || return;;
 		rosie) i $commonPc MsiMotherboard Dropbox office thunderbird || return;;
@@ -762,7 +763,7 @@ bootstrap()
 bootstrapStart()
 {
 	# permissions
-	sudoc chown "$USER" "$HOME/.bash_history" || return
+	[[ -f "$HOME/.bash_history" ]] && { sudoc chown "$USER" "$HOME/.bash_history" || return; }
 
 	# files
 	printf "files..."
@@ -874,10 +875,6 @@ bootstrapMac()
 	pkg dockutil duti fontconfig pidof wakeonlan wget xz || return
 
 	! InPath gfind && { pkg findutils || return; }
-	! IsPlatform arm && { pkg cask; }
-
-	InPath xcodebuild && { sudoc xcodebuild -license accept || return; }
-	! IsPlatform arm && [[ -d "/Applications/Xcode.app" ]] && { pkg mas || return; }
 
 	if [[ ! -f "/etc/paths.d/wiggin" ]]; then
 		sudo bash -c 'echo "/usr/local/data/bin
@@ -1078,22 +1075,23 @@ CompareProgramCore() { i BeyondCompare; }
 
 BeyondCompareInstall()
 {
-	header "BeyondCompare"
-
-	# http://www.scootersoftware.com/download.php
-	local v=4.3.7.25118
+	header "BeyondCompare"; local v=4.3.7.25118 # http://www.scootersoftware.com/download.php
 	run "other/Scooter Software/Beyond Compare/setup/" -p "BCompare-${v}_x64.msi" "BCompareOSX-${v}.zip" "bcompare-${v}_amd64.deb" || return
+	BeyondCompareFinal || return
 
+	echo "- Help|Preferences, Enter Key..."
+	[[ "$PLATFORM" == "mac" ]] && echo "- Beyond Compare, Install Command Line Tools…"
+	BeyondCompare $noPrompt profile restore default || return
+}
+
+BeyondCompareFinal()
+{
 	if IsPlatform win; then
 		mergeDir --rename "$pp/Beyond Compare 4" "$ao/Beyond Compare" || return
 		$rm "$pd/Beyond Compare 4.lnk" || return
 		$rm "$ud/Beyond Compare 4.lnk" || return
 		registry delete "urun/BCClipboard" # C:\Program Files\Beyond Compare 4\BCClipboard.exe
 	fi
-
-	echo "- Help|Preferences, Enter Key..."
-	[[ "$PLATFORM" == "mac" ]] && echo "- Beyond Compare, Install Command Line Tools…"
-	BeyondCompare $noPrompt profile restore default || return
 }
 
 #################################################
@@ -2763,7 +2761,7 @@ homebridgeWiggin()
 MacSetup()
 {
 	header "Mac Setup"
-	i MacConfigure MacFonts MacDock MacDockCleanup MacAppCleanup || return
+	i MacConfigure MacFonts MacDock MacDockCleanup MacAppStore MacAppCleanup || return
 }
 
 MacConfigure()
@@ -2815,10 +2813,26 @@ MacFonts()
 
 MacAppCleanup()
 {
-	! InPath mas && return
+	macUninstall "Keynote" || return
+	macUninstall "iMovie" || return
+	macUninstall "Pages" || return
+	macUninstall "GarageBand" || return
+	macUninstall "Numbers" || return
+}
 
-	echo "Removing applications..."
-	mas uninstall N || return
+macUninstall()
+{
+	local app="/Applications/$1.app"
+
+	[[ ! -d "$app" ]] && return
+	echo "Removing $1..."
+	sudoc rm -fr "$app"
+}
+
+MacAppStore()
+{
+	header "mas" # https://github.com/mas-cli/mas/releases
+	run "platform/mac/mas/mas.pkg" || return # brew mas fails on ARM
 }
 
 #################################################
@@ -2881,9 +2895,10 @@ VaultInstall()
 # mail
 #################################################
 
-MailCore() { i spart thunderbird; }
+MailCore() { i CanaryMail spark thunderbird; }
 
 SparkInstall() { storeInstall Spark 1176895641; }
+CanaryMailInstall() { storeInstall "Canary Mail" 1236045954; }
 
 ThunderbirdInstall()
 {
@@ -3865,11 +3880,13 @@ NotesCore() { i notion StandardNotes Todoist; }
 
 notionInstall()
 {
-	header "Notion"
-
-	# https://www.notion.so/desktop
+	header "Notion"	# https://www.notion.so/desktop
 	run "other/notion/" -p "Notion Setup 2.0.9.exe" "Notion-2.0.8.dmg" || return
+	notionFinal || return
+}
 
+notionFinal()
+{
 	if IsPlatform win; then
 		$mv "$up/Notion.lnk" "$up/Applications" || return
 		$rm "$ud/Notion.lnk" || return
@@ -3878,8 +3895,6 @@ notionInstall()
 		MakeDirOwner "$P/Notion.app" || return # must be writable otherwise prompted for invalid install
 		! dockutil --find "Notion" >& /dev/null && { dockutil --add "/Applications/Notion.app" || return; }
 	fi
-
-	return 0
 }
 
 StandardNotesInstall()
@@ -4690,7 +4705,9 @@ windowsTerminalInstall()
 # Text Editor
 #################################################
 
-TextEditorCore() { i geany micro notepadpp sublime SublimeMerge; }
+TextEditorCore() { i bear geany micro notepadpp sublime SublimeMerge; }
+
+BearInstall() { storeInstall "Bear" 1091189122; }
 
 GeanyInstall()
 {
