netbootxyz: move verbose usage to info command

diff --git a/netbootxyz b/netbootxyz
--- a/netbootxyz
+++ b/netbootxyz
@@ -10,57 +10,6 @@ $(ScriptName) commands.
 	update|deploy|both			update and deploy netbootxyz"
 }
 
-usageVerbose()
-{
-	local webDirTarget="$(getwebDirTarget)"
-
-	local applicationUrl="$(GetServer "netbootxyz" --quiet)"
-	[[ $applicationUrl ]] && applicationUrl="http://$applicationUrl:3000" || applicationUrl="${RED}no netbootxyz application servers${RESET}"
-
-	local assetUrl="$(GetServer "apache-web" --quiet)"
-	[[ $assetUrl ]] && assetUrl="https://$assetUrl:1443/boot-assets http://$assetUrl:180/boot-assets" || menunUrl="${RED}no web asset servers${RESET}"
-
-	local menuUrl="$(GetServer "apache-web" --quiet)"
-	[[ $menuUrl ]] && menuUrl="https://$menuUrl:1443/netbootxyz http://$menuUrl:180/netbootxyz" || menuUrl="${RED}no web menu servers${RESET}"
-
-	local tftpServers="$(GetServers "tftp" --quiet | NewlineToSpace | RemoveSpaceTrim)"
-	[[ ! $tftpServers ]] && tftpServers="${RED}no tftp servers${RESET}"
-
-	local tftpServer="$(GetServer "tftp" --quiet)"
-	[[ ! $tftpServer ]] && tftpServer="${RED}no tftp servers${RESET}"
-
-	local webAssetServers="$(GetServers "apache-web" --quiet | NewlineToSpace | RemoveSpaceTrim)"
-	[[ ! $webAssetServers ]] && webAssetServers="${RED}no web asset servers${RESET}"
-
-	local webMenuServers="$(GetServers "apache-web" --quiet | NewlineToSpace | RemoveSpaceTrim)"
-	[[ ! $webMenuServers ]] && webMenuServers="${RED}no web menu servers${RESET}"
-
-	ScriptUsageEcho "\
-Locations:
-- application: netboot.xyz Git repository  : $appDir ($(checkDir "$appDir"))
-- configuration: custom configuration      : $confDir ($(checkDir "$confDir"))
-- web app: netboot.xyz website             : $webDirApp ($(checkDir "$webDirApp"))
-- web target: local website source         : $webDirTarget ($(checkDir "$webDirTarget"))
-
-Sites:
-- application: https://netboot.butare.net
-	- direct: $applicationUrl
-- bootloaders/menus: https://boot.butare.net http://boot.butare.net/menu.ipxe
-	- direct: $menuUrl
-- assets: http://boot-assets.butare.net
-  - direct: $assetUrl
-Servers:
-- web-asset: $webAssetServers
-  - directory: 'cd \$(apache dir cd)/boot-assets'
-- web-menu: $webMenuServers
-  - directory: 'cd \$(apache dir cd)/netbootxyz
-- tftp: $tftpServers
-  - configuration: /etc/default/tftpd-hpa
-	- example: 'tftp $tftpServer -c get menu.ipxe'	"
-}
-
-checkDir() {  [[ -d "$1" ]] && echo "present" || echo "${RED}missing${RESET}";  }
-
 init() 
 {
 	# netboot.xyz application
@@ -229,16 +178,84 @@ editWinCommand() { TextEdit "$winScriptDir"; }
 # info commands
 #
 
-infoUsage() { ScriptUsageEcho "Usage: $(ScriptName) info [win]\nShow information."; }
-infoCommand() { infoWinCommand; }
+infoUsage() { ScriptUsageEcho "Usage: $(ScriptName) info [locations|sites|servers|win](all)\nShow information."; }
+infoCommand() { infoAllCommand; }
+infoAllCommand() { infoLocationsCommand && echo && infoSitesCommand && echo && infoServersCommand && echo && infoWinCommand; }
+
+infoLocationsCommand()
+{
+	local webDirTarget="$(getwebDirTarget)"
+
+	echot "\
+Locations:
+- application: netboot.xyz Git repository  : $appDir ($(checkDir "$appDir"))
+- configuration: custom configuration      : $confDir ($(checkDir "$confDir"))
+- web app: netboot.xyz website             : $webDirApp ($(checkDir "$webDirApp"))
+- web target: local website source         : $webDirTarget ($(checkDir "$webDirTarget"))"
+}
+
+infoSitesCommand()
+{
+	local applicationUrl="$(GetServer "netbootxyz" --quiet)"
+	[[ $applicationUrl ]] && applicationUrl="http://$applicationUrl:3000" || applicationUrl="${RED}no netbootxyz application servers${RESET}"
+
+	local menuUrl="$(GetServer "apache-web" --quiet)"
+	[[ $menuUrl ]] && menuUrl="https://$menuUrl:1443/netbootxyz http://$menuUrl:180/netbootxyz" || menuUrl="${RED}no web menu servers${RESET}"
+
+	local assetUrl="$(GetServer "apache-web" --quiet)"
+	[[ $assetUrl ]] && assetUrl="https://$assetUrl:1443/boot-assets http://$assetUrl:180/boot-assets" || menunUrl="${RED}no web asset servers${RESET}"
+
+	echot "\
+Sites:
+- application: https://netboot.butare.net
+	- direct: $applicationUrl
+- bootloaders/menus: https://boot.butare.net http://boot.butare.net/menu.ipxe
+	- direct: $menuUrl
+- assets: http://boot-assets.butare.net
+  - direct: $assetUrl"
+}
+
+infoServersCommand()
+{
+	echo "Servers:"
+
+	# web asset
+	local webAssetServers="$(GetServers "apache-web" --quiet | NewlineToSpace | RemoveSpaceTrim)"
+	[[ ! $webAssetServers ]] && webAssetServers="${RED}no web asset servers${RESET}"
+
+	echot "\
+- web-asset: $webAssetServers
+  - directory: 'cd \$(apache dir cd)/boot-assets'"
+
+  # web menu
+	local webMenuServers="$(GetServers "apache-web" --quiet | NewlineToSpace | RemoveSpaceTrim)"
+	[[ ! $webMenuServers ]] && webMenuServers="${RED}no web menu servers${RESET}"
+
+	echot "\
+- web-menu: $webMenuServers
+  - directory: 'cd \$(apache dir cd)/netbootxyz"
+
+  # TFTP
+	local tftpServers="$(GetServers "tftp" --quiet | NewlineToSpace | RemoveSpaceTrim)"
+	[[ ! $tftpServers ]] && tftpServers="${RED}no tftp servers${RESET}"
+
+	local tftpServer="$(GetServer "tftp" --quiet)"
+	[[ ! $tftpServer ]] && tftpServer="${RED}no tftp servers${RESET}"
+
+	echot "\
+- tftp: $tftpServers
+  - configuration: /etc/default/tftpd-hpa
+	- example: 'tftp $tftpServer -c get menu.ipxe'	"
+}
 
 infoWinUsage() { ScriptUsageEcho "Usage: $(ScriptName) info win [detail]\Show Windows release information."; }
 
 infoWinCommand()
 {
+	echot "Windows:"
 	local release
 	for release in "${winReleases[@]}"; do
-		echo "$release: $(infoWinBuild "$release")"
+		echo "  $release: $(infoWinBuild "$release")"
 	done
 }
 
@@ -664,6 +681,7 @@ versionLocal() { isInstalledCommand && cat "$appDir/version.txt"; }
 #
 
 appCd() { AppInstallCheck && cd "$appDir"; }
+checkDir() {  [[ -d "$1" ]] && echo "present" || echo "${RED}missing${RESET}";  }
 getContainerId() { docker ps --all | grep "$dockerImageName" | cut -d" " -f1; }
 getHosts() { GetHostsService "netbootxyz"; }
 getUupFileCount() { command ls -1 "$downloadDir/"*.*".zip" 2> /dev/null | wc -l; }
