netbootxyz: updates
Update netboot.xyz install to new deployment architecture.

diff --git a/netbootxyz b/netbootxyz
--- a/netbootxyz
+++ b/netbootxyz
@@ -5,7 +5,7 @@ usage()
 {
 	ScriptUsage "$1" "\
 usage: netbootxyz backup|docker|IsInstalled|profile|test|web
-	docker 		control the docker image
+	docker 		control the docker dockerImageName
 	web				update the netboot.xyz web site
   profile 	netboot.xyz configuration
   test			test the configuration"
@@ -13,8 +13,7 @@ usage: netbootxyz backup|docker|IsInstalled|profile|test|web
 
 init() 
 { 
-	image="netbootxyz"
-	profileDir="${ACONFIG}/netboot.xyz"
+	dockerImageName="netbootxyz"
 	config="/opt/netboot.xyz/user_overrides.yml"
 }
 
@@ -33,22 +32,23 @@ backupCommand()
 
 testCommand()
 {
-	printf "UI: "; curl -s https://netboot.butare.net | grep -q "Web Application for customizing netboot.xyz" && echo "OK" || EchoErr "FAIL"
-	printf "TFTP: " && IsAvailablePortUdp nas3 69 && echo "OK" || EchoErr "FAIL"
-	printf "assets: " && curl -s http://boot.butare.net:10181/ | grep -q "Index of /" && echo "OK" || EchoErr "FAIL"
+	printf "TFTP: " && IsAvailablePortUdp "web.service.butare.net" 69 && echo "OK" || EchoErr "FAIL"
+	printf "menus: "; curl --silent "https://boot.butare.net" | grep -q "Legacy and EFI Combined iPXE Bootloaders" && echo "OK" || EchoErr "FAIL"
+	printf "UI: "; curl --silent "https://netboot.butare.net" | grep -q "Web Application for customizing netboot.xyz" && echo "OK" || EchoErr "FAIL"
+	printf "assets: " && curl -s "http://netboot.butare.net:10181/" | grep -q "Index of /" && echo "OK" || EchoErr "FAIL"
 }
 
 #
-# Docker Image Commands
+# Docker dockerImageName Commands
 #
 
 dockerUsage() { echot "Usage: $(ScriptName) docker IsInstalled|IsRunning|shell|start|stop
-Control the docker image."; }
+Control the docker dockerImageName."; }
 
 dockerCommand() { usage; }
-dockerIsInstalledCommand() { ! InPath docker && return 1; docker image list |& grep "$image" >& /dev/null; }
-dockerIsRunningCommand() { docker ps | grep --quiet "$image"; }
-dockerShellCommand() { docker exec -it "$image" /bin/bash; } 
+dockerIsInstalledCommand() { ! InPath docker && return 1; docker dockerImageName list |& grep "$dockerImageName" >& /dev/null; }
+dockerIsRunningCommand() { docker ps | grep --quiet "$dockerImageName"; }
+dockerShellCommand() { docker exec -it "$dockerImageName" /bin/bash; } 
 dockertStartCommand() { docker start "$(getContainerId)"; } 
 dockerStopCommand() { docker stop "$(getContainerId)"; } 
 
@@ -62,9 +62,14 @@ profileArgs() { profileArgs=( "$@" ); (( shift+=$# )); }
 
 profileCommand()
 {
-	[[ ! -d "$profileDir" ]] && { ${G}mkdir --parents "$profileDir" || return; }
-	profile $noPrompt --app "$image" --method "$profileDir" --files "nginx menus" "${profileArgs[@]}" || return
-	profile $noPrompt --sudo --app "$image-config" --method "$(GetFilePath "$config")" --files "$(GetFileName "$config")" "${profileArgs[@]}" || return
+	# Docker container menus
+	profileDir="${ACONFIG}/netboot.xyz/nginx menus"
+	if [[ -d "$profileDir" ]]; then
+		profile $noPrompt --app "$dockerImageName" --method "$profileDir" --files "nginx menus" "${profileArgs[@]}" || return
+	fi
+
+	# web deploy defaults
+	profile $noPrompt --sudo --app "$dockerImageName-config" --method "$(GetFilePath "$config")" --files "$(GetFileName "$config")" "${profileArgs[@]}" || return
 }
 
 #
@@ -83,7 +88,7 @@ Update the netboot.xyz web site.
 
 webCommand() { usage; }
 webConfigCommand() { TextEdit "$config"; }
-webDeployCommand() { CopyDir --recursive --delete "/var/www/html/" "$SRV/apache-web/htdocs/netboot.xyz" && inst ApacheSync;  }
+webDeployCommand() { sudo CopyDir --recursive --delete "/var/www/html/" "$SRV/apache-web/htdocs/netboot.xyz" && inst ApacheSync;  }
 
 webUpdateCommand()
 {
@@ -107,6 +112,6 @@ webUpdateCommand()
 # helper functions
 #
 
-getContainerId() { docker ps --all | grep "$image" | cut -d" " -f1; }
+getContainerId() { docker ps --all | grep "$dockerImageName" | cut -d" " -f1; }
 
 ScriptRun "$@"
