netbootxyz setup: add test command

diff --git a/netbootxyz b/netbootxyz
--- a/netbootxyz
+++ b/netbootxyz
@@ -276,10 +276,12 @@ infoWinUrl()
 # setup command
 #
 
-setupUsage() { echot "Usage: $(ScriptName) setup [app|config|web](all)\nSetup the netboot.xyz build environment including the application and web source files."; }
+setupUsage() { echot "Usage: $(ScriptName) setup [app|config|test|web](all)\nSetup the netboot.xyz build environment including the application and web source files."; }
 setupCommand() { setupAll; }
 setupAllCommand() { setupAll; }
-setupAll() { setupAppCommand && echo && setupConfigCommand && echo && setupWebCommand; }
+setupAll() { setupAppCommand && echo && setupConfigCommand && echo && setupTestCommand && echo && setupWebCommand; }
+setupTestUsage() { echot "Usage: $(ScriptName) setup test\nSetup the netboot.xyz test programs."; }
+setupTestCommand() { inst install TftpClient --no-header; }
 
 setupAppUsage()
 {
@@ -320,7 +322,7 @@ setupConfigCommand()
 	CloudGet "$confDir"
 }
 
-setupConfigUsage()
+setupWebUsage()
 {
 	echot "Usage: $(ScriptName) setup web
 Setup the netboot.xyz web directories '$webDirApp' and '$(getwebDirTarget)'."
@@ -394,12 +396,11 @@ testAssets()
 
 testTftp()
 {
-	# determine check host
-	# - mac TFTP does not support -c
-	# - WSL does not support UDP
-	local check
-	if IsPlatform mac; then
-		check="ssh $(GetServer "apache-web")" || { testFail "could not get a server to test TFTP"; return; }
+	# determine tftp program
+	local run tftp="${G}tftp"
+	if ! InPath $tftp; then
+		tftp="tftp"
+		run="ssh $(GetServer "apache-web")" || { testFail "could not get a server to test TFTP"; return; }
 	fi
 
 	local file="about.ipxe"
@@ -410,10 +411,10 @@ testTftp()
 		printf "TFTP $desc: "
 		printf "server..."; IsAvailable "$server" || { testFail "not available"; continue; }
 		printf "port..."; IsAvailablePortUdp "$server" 69 || { testFail "not responding (port 69)"; continue; }
-		printf "IPv4..."; RunLog $check tftp -4 $server -c get "$file" > /dev/null || { testFail "failed"; continue; }
-		printf "IPv6..."; RunLog $check tftp -6 $server -c get "$file" > /dev/null || { testFail "failed"; continue; }
+		printf "IPv4..."; RunLog $run $tftp -4 $server -c get "$file" > /dev/null || { testFail "failed"; $run rm -f "$file"; continue; }
+		printf "IPv6..."; RunLog $run $tftp -6 $server -c get "$file" > /dev/null || { testFail "failed"; $run rm -f "$file"; continue; }
 		echo "OK"
-		$check rm -f "$file" # cleanup
+		$run rm -f "$file"
 	done
 }
 
