netbootxyz test tftp: test IPv6

diff --git a/netbootxyz b/netbootxyz
--- a/netbootxyz
+++ b/netbootxyz
@@ -398,7 +398,7 @@ testTftp()
 	# - mac TFTP does not support -c
 	# - WSL does not support UDP
 	local check
-	if IsPlatform mac,WSL; then
+	if IsPlatform mac; then
 		check="ssh $(GetServer "apache-web")" || { testFail "could not get a server to test TFTP"; return; }
 	fi
 
@@ -410,7 +410,8 @@ testTftp()
 		printf "TFTP $desc: "
 		printf "server..."; IsAvailable "$server" || { testFail "not available"; continue; }
 		printf "port..."; IsAvailablePortUdp "$server" 69 || { testFail "not responding (port 69)"; continue; }
-		printf "file..."; RunLog $check tftp $server -c get "$file" > /dev/null || testFail "not available ($file)"
+		printf "IPv4..."; RunLog $check tftp -4 $server -c get "$file" > /dev/null || { testFail "failed"; continue; }
+		printf "IPv6..."; RunLog $check tftp -6 $server -c get "$file" > /dev/null || { testFail "failed"; continue; }
 		echo "OK"
 		$check rm -f "$file" # cleanup
 	done
