network configure netplan: add dynamic and static

diff --git a/network b/network
--- a/network
+++ b/network
@@ -187,7 +187,7 @@ configureCommand() { usage; }
 
 configureStatusCommand()
 {
-	local what; cloudInitVars || return
+	local what
 	for what in cloudInit netplan; do
 		if ${what}IsInstalled; then
 			if [[ $verbose ]]; then
@@ -246,7 +246,7 @@ configureCloud-initEnableCommand()
 }
 
 cloudInitDesc() { echo "cloud-init"; }
-cloudInitIsInstalled() { [[ -d "$baseDir" ]]; }
+cloudInitIsInstalled() { cloudInitVars && [[ -d "$baseDir" ]]; }
 cloudInitIsEnabled() { [[ ! -f "$disableFile" ]]; }
 cloudInitValidate() { cloudInitIsInstalled && return; ScriptErrQuiet "cloud-init is not installed"; return 1; }
 cloudInitVars() { baseDir="/etc/cloud"; enableFile="$baseDir/cloud.cfg.d/50-cloud-init.yaml" disableFile="$baseDir/cloud.cfg.d/99-disable-network-config.cfg"; }
@@ -263,15 +263,126 @@ cloudInitStatus()
 # configure - Netplan
 #
 
-configureNetplanUsage() { echot "Usage: $(ScriptName) configure netplan IsInstalled|renderer|status\nNetplan network configuration."; }
+configureNetplanUsage() { echot "Usage: $(ScriptName) configure netplan dynamic|IsInstalled|renderer|static|status\nNetplan network configuration."; }
+configureNetplanArgStart() { netplanVars; }
 configureNetplanCommand() { usage; }
 configureNetplanRendererUsage() { echot "Usage: $(ScriptName) configure netplan renderer\nReturn the current network render, NetworkManager or networkd."; }
 configureNetplanRendererCommand() { netplanRenderer; }
 configureNetplanStatusCommand() { netplanStatus; }
 
+configureNetplanStaticUsage() { echot "Usage: $(ScriptName) configure netplan static\nConfigure a dynamic IP address."; }
+
+configureNetplanDynamicCommand()
+{
+	netplanValidate || return
+
+	local file="$dynamicFile"
+	if [[ ! -f "$file" || $force ]]; then
+		local interface; interface="$(GetInterface)" || return
+		local renderer; renderer="$(netplanRenderer)" || return
+
+		# update
+		cat <<-EOF | sudoc ${G}tee "$file" > /dev/null || return
+			network:
+			  version: 2
+			  ethernets:
+			    $interface:
+			      renderer: $renderer
+			      dhcp4: true
+			      dhcp6: true
+		EOF
+
+		sudo chmod go-r "$file" || return
+	fi
+
+	netplanCleanup "$staticFile"
+}
+
+configureNetplanStaticUsage() { echot "Usage: $(ScriptName) configure netplan static\nConfigure a static IP address using the existing IP configuration."; }
+
+configureNetplanStaticCommand()
+{
+	netplanValidate || return
+
+	local file="$staticFile"
+	if [[ ! -f "$file" || $force ]]; then
+		local renderer; renderer="$(netplanRenderer)" || return
+		local defaultGatway; defaultGatway="$(GetDefaultGateway)" || return
+		local dnsSearch; dnsSearch="$(GetDnsSearch "${globalArgs[@]}" | sed "s/ /,/g")" || return
+		local dnsServers; dnsServers="$(GetDnsServers4 | sed "s/ /,/g")" || return
+		local interface; interface="$(GetInterface)" || return
+		local ipAddress4; ipAddress4="$(GetIpAddress4)" || return
+		local subnetNumber; subnetNumber="$(GetSubnetNumber)" || return
+		local ipAddress6Token="$(Ipv6Token "$ipAddress4")"
+
+		# validate IPv4
+		! IsIpAddress4 "$defaultGatway" && { ScriptErr "the default gateway '$defaultGatway' is not a valid IPv4 address"; return 1; }
+		! IsIpAddress4 "$ipAddress4" && { ScriptErr "the IPv4 address '$ipAddress4' is not a valid IPv4 address"; return 1; }
+		! IsNumeric "$subnetNumber" && { ScriptErr "the subnet number '$subnetNumber' is not a valid IPv4 subnet number"; return 1; }
+
+		# update
+		cat <<-EOF | sudoc ${G}tee "$file" > /dev/null || return
+			network:
+			  version: 2
+			  ethernets:
+			    $interface:
+			      renderer: $renderer
+			      match:
+			      	name: $interface # required for systemd-networkd
+			      dhcp4: false
+			      dhcp6: true
+			      ipv6-address-token: "$ipAddress6Token" # IPv4 address
+			      addresses:
+			        - $ipAddress4/$subnetNumber
+			      routes:
+			        - to: default
+			          via: $defaultGatway
+			      nameservers:
+			          addresses: [$dnsServers]
+			          search: [$dnsSearch]
+		EOF
+
+		sudo chmod go-r "$file" || return
+	fi
+
+	netplanCleanup "$dynamicFile"
+}
+
 netplanDesc() { echo "netplan"; }
-netplanIsInstalled() { InPath netplan; }
+netplanIsInstalled() { netplanVars && InPath netplan; }
 netplanValidate() { netplanIsInstalled && return; ScriptErrQuiet "Netplan is not installed"; return 1; }
+netplanVars() { baseDir="/etc/netplan"; dynamicFile="$baseDir/01-network-manage-all-dynamic.yaml" staticFile="$baseDir/01-network-manage-all-static.yaml"; }
+
+# netplanCleanup [FILE] - cleanup old configuration and apply new configuration
+netplanCleanup()
+{
+	# cleanup old file
+	local file="$1"
+	[[ $file && -f "$file" ]] && { sudoc rm -f "$file" || return; }
+
+	# disable old configuration file
+	local file="/etc/netplan/01-network-manage-all.yaml"
+	[[ -f "$file" ]] && { sudoc rm "$file" || return; }
+
+	# disable cloud-init DHCP
+	cloudInitIsInstalled && { network configure cloud-init disable || return; }
+
+	if [[ $noPrompt ]]; then
+		sudoc netplan apply || return
+	else
+		sudoc netplan try || return
+	fi
+	
+	sleep 2
+}
+
+netplanDhcp()
+{
+	if [[ -f "$staticFile" ]]; then printf "static"
+	elif [[ -f "$dynamicFile" ]]; then printf "dynamic"
+	else printf "unknown"
+	fi
+}
 
 netplanRenderer()
 {
@@ -288,8 +399,8 @@ netplanStatus()
 	echo "  installed=$(netplanIsInstalled && echo "true" || echo "false")"
 	! netplanIsInstalled && return
 	echo "  renderer=$(netplanRenderer)"
+	echo "  dhcp=$(netplanDhcp)"
 }
-
 
 #
 # current commands
@@ -595,8 +706,7 @@ validateDnsServer()
 # DNS commands
 #
 
-dnsUsage() { echot "Usage: $(ScriptName) adapter edit|list|name
-Network adapter commands."; }
+dnsUsage() { echot "Usage: $(ScriptName) dns flush\nDNS commands."; }
 
 dnsCommand() { dnsFlushCommand; }
 
