service: mac improvements
service: mac improvements

service: mac fixes

diff --git a/service b/service
--- a/service
+++ b/service
@@ -7,7 +7,8 @@ usage()
 Usage: service [OPTION]... [COMMAND](start) 
 Control system services.
 
-	continue|manage|pause|reload|restart|start|stop SERVICE							control service
+	continue|manage|pause|restart|start|stop SERVICE										control service
+	load|reload|unload SERVICE																					control service
 	auto|boot|delete|demand|disable|manual SERVICE		 									configure service
 	detail|exists|info|log|show|StartType|state|status|running SERVICE	service information
 	dir|list|refresh|ui
@@ -63,46 +64,50 @@ serviceInit()
 	[[ $host && ! $ignoreHost ]] && { RunLog $ssh service --ignore-host "${originalArgs[@]}"; exit $?; }
 
 	# initialize service variables
-	[[ $service ]] && { serviceCheck || return; }
+	[[ $service ]] && { serviceCheck "$service" || return; }
 
 	return 0
 }
 
+# serviceCheck SERVICE - initialize the service
 serviceCheck()
 {
-	# initialize - set _platformOs for subsequent commands
-	_platformOs="$PLATFORM_OS"
-
+	# initialize
+	service="$1" serviceOriginal="$1"
+	_platformOs="$PLATFORM_OS" # set _platformOs for subsequent commands
+	
 	# check
 	case "$_platformOs" in
+
 		mac)
-			macServiceLoaded="true"
-			unset macServiceInfo macServiceFile macServiceFileContent
+			local serviceNameOk
+			unset macService macServiceFile macServiceFileContent macServiceFileValidated
 
-			# remove file extension, so we can use a plist file as the service 
-			[[ -f "$service" ]] && service="$(GetFileNameWithoutExtension "$service")"
+			# service is file (i.e. a property list file)
+			if [[ -f "$service" ]]; then
+				macServiceFile="$service"
+				service="$(macServiceFileGetServiceName)" || return
+			fi
 
-			# check loaded services
-			if macServiceInfo="$(launchctl print "system/$service" 2>&1)"; then macServiceDomain="system/"
-			elif macServiceInfo="$(launchctl print "gui/$UID/$service" 2>&1)"; then macServiceDomain="gui/$UID/"
-			elif macServiceInfo="$(launchctl print "user/$UID/$service" 2>&1)"; then macServiceDomain="user/$UID/"
-
-			# check services on disk - includes unloaded services
-			else
-				unset macServiceInfo macServiceLoaded
-				getMacServiceFiles || return
-				if echo "$macServiceFiles" | qgrep "^/Users/$USER/.*/$service.plist$"; then
-					macServiceDomain="user/$UID/"
-				elif echo "$macServiceFiles" | qgrep -E "^/(System|Library)/.*/$service.plist$"; then
-					macServiceDomain="system/"
-				else
-					unknownService; return
-				fi
+			# check loaded services then services on disk
+			if ! getMacServiceInfo && [[ ! $macServiceFile ]]; then # sets macServiceDomain, macServiceInfo, and macServiceLoaded
+				quiet="--quiet" getMacServiceFile || { unknownService; return; }
+				service="$(macServiceFileGetServiceName)" || return
+				getMacServiceInfo # try and get the loaded service information with the new service name
 			fi 
 
-			macService="$macServiceDomain$service" || return
+			# get the service domain if possible
+			if [[ ! $macServiceDomain ]]; then				
+				if [[ "$(infoTypeMac)" == "LaunchDaemon" ]]; then macServiceDomain="system/" # launch daemons must be in the system/ doamin
+				elif [[ "$macServiceFile" =~ ^/Users/ ]]; then macServiceDomain="user/$UID/"
+				else macServiceDomain="unknown"						
+				fi
+			fi
+
+			# finalize
+			[[ $macServiceDomain ]] && macService="$macServiceDomain$service"
 			sudo=""; [[ "$macServiceDomain" == "system/" ]] && sudo="sudoc"
-			log1 "macService=$macService domain=$macServiceDomain loaded=$macServiceLoaded sudo=$sudo"
+			log1 "service=$service macService=$macService domain=$macServiceDomain loaded=$macServiceLoaded sudo=$sudo"
 			;;
 
 		linux) 
@@ -132,43 +137,10 @@ serviceCheck()
 
 	esac
 
+	# logging
+	[[ "$serviceOriginal" != "$service" ]] && log1 "using actual service name '$service'"
+
 	return 0
-}
-
-checkSystemd() { IsSystemd && useSystemd="true"; return 0; }
-
-getMacServiceFileContent() 
-{
-	[[ $macServiceFileContent ]] && return
-	getMacServiceFile && macServiceFileContent="$(plutil -p "$macServiceFile")" || macServiceFileContent="unknown"
-}
-
-getMacServiceFiles() 
-{
-	[[ $macServiceFiles ]] && return
-	macServiceFiles="$(listFilesMac)"
-}
-
-getMacServiceFile()
-{
-	[[ $macServiceFile ]] && return
-
-	# look in the cached macServiceInfo
- 	if [[ $macServiceInfo ]]; then
- 		macServiceFile="$(echo "$macServiceInfo" | ${G}grep "path =.*\.plist$" | cut -d"=" -f2 | RemoveSpaceTrim)"
- 		[[ ! -f "$macServiceFile" ]] && { log2 "getMacServiceFile: service '$macService' file '$macServiceFile' from the cached service information does not exist"; unset macServiceFile; }
- 	fi
-
- 	# look for service files on disk
- 	if [[ ! $macServiceFile ]]; then 	
- 		getMacServiceFiles || return
-		macServiceFile="$(echo "$macServiceFiles" | ${G}grep "/$service.plist$" | head -1)"
-		[[ ! $macServiceFile ]] && { log2 "getMacServiceFile: service '$macService' does not have a service file on disk"; unset macServiceFile; }
-	fi
-
-	[[ ! $macServiceFile ]] && macServiceFile="unknown"
-	log2 "getMacServiceFile: macServiceFile='$macServiceFile'"
-	[[ $macServiceFile ]]
 }
 
 unknownService() 
@@ -182,7 +154,7 @@ unknownService()
 # commands
 #
 
-existsCommand() { serviceCheck >& /dev/null; }
+existsCommand() { serviceCheck "$service" >& /dev/null; }
 runningCommand() { [[ "$(stateCommand)" == "RUNNING" ]]; }
 uiCommand() { ! IsPlatform win && return; start services.msc; }
 
@@ -237,19 +209,12 @@ refreshUsage()
 Load new services and reset failed services."
 }
 
-refreshCommand()
-{
-	! IsSystemd && return
-	sudo systemctl daemon-reload && sudo systemctl reset-failed
-}
+refreshCommand() { RunPlarform refresh; }
 
-reloadCommand()
+refreshLinux()
 {
-	if [[ $useSystemd ]]; then
-		sudoc systemctl reload "$service" || return
-	else
-		restartCommand || return
-	fi
+	[[ ! $useSystemd ]] && return
+	sudo systemctl daemon-reload && sudo systemctl reset-failed
 }
 
 restartCommand() 
@@ -274,8 +239,13 @@ statusCommand()
 
 autoCommand() { doCommand "auto"; }
 autoLinux() { linuxService enable "$service"; }
-autoMac() { RunLog $sudo launchctl enable "$macService"; }
 autoWin() { local result; result="$($sc config $hostUnc "$service" start= auto)" && return; EchoErr "$result"; return 1; }
+
+autoMac()
+{
+	[[ $macService ]] && { RunLog $sudo launchctl enable "$macService" && return; }
+	ScriptErr "unable to set service '$service' to auto in domain '$domain'"
+}
 
 #
 # continue command
@@ -311,16 +281,31 @@ deleteLinux()
 # detail command
 #
 
+detailUsage() { EchoWrap "Usage: $(ScriptName) detail [brief]\nShow service detail, optionally in a concise format."; }
 detailCommand() { statusCommand && RunPlatform "detail" --host; }
+detailBriefCommand() { brief="brief" RunPlatform "detail" --host; }
 
 detailLinux()
-{
-	
+{	
 	echo "$(infoTypeLinux) service: $(infoFileLinux)"
 	linuxService status "$service" || return
 }
 
-detailMac() {	infoFileContentsCommand; }	
+detailMac()
+{
+	# detailed information
+	local sep=$'\n'; [[ $brief ]] && sep=" "
+	getMacServiceFile
+	echo -e "macService=$macService${sep}file=$macServiceFile${sep}domain=$macServiceDomain${sep}loaded=$macServiceLoaded${sep}sudo=$sudo"
+	
+	# service definition
+	[[ ! $brief ]] && { hilight "Service Definition"; infoFileContentsCommand || return; }
+
+	# service info
+	[[ ! $brief && $macServiceLoaded ]] && { hilight "Service Information"; echo "$macServiceInfo"; }
+
+	return 0
+}
 
 detailWin()
 {
@@ -336,9 +321,14 @@ detailWin()
 #
 
 disableCommand() { doCommand "disable"; }
-disableMac() { RunLog $sudo launchctl disable "$macService"; }
 disableWin() { $sc config $hostUnc "$service" start= disabled; }
 disableLinux() { linuxService disable "$service"; }
+
+disableMac()
+{
+	[[ $macService ]] && { RunLog $sudo launchctl disable "$macService" && return; }
+	ScriptErr "unable to set service '$service' to auto in domain '$domain'"
+}
 
 #
 # list command
@@ -347,7 +337,7 @@ disableLinux() { linuxService disable "$service"; }
 listUsage()
 {
 	ScriptUsageEcho "\
-Usage: service list [files|running]
+Usage: service list [files|running|unloaded]
 List services.
 
 	-d, --detail		show more detail about the services
@@ -375,14 +365,6 @@ listCommand()
 	TextEdit "$file"
 }
 
-listMac()
-{ 
-	{ 
-		{ launchctl list; sudoc launchctl list; } | cut -d"	" -f3 | ${G}grep -v "^Label$"		# loaded services
-		listFilesMac | rev | ${G}cut -d$'/' -f1 | cut -d"." -f2- | rev 											# unloaded services
-	} | sort | uniq; 
-}
-
 listLinux()
 {
 	if IsSystemd; then
@@ -394,6 +376,14 @@ listLinux()
 	elif [[ -d "/etc/init.d" ]]; then
 		grep "force-reload" "/etc/init.d/"* --files-with-matches | cut -d'/' -f4
 	fi
+}
+
+listMac()
+{ 
+	{ 
+		{ launchctl list; sudoc launchctl list; } | cut -d"	" -f3 | ${G}grep -v "^Label$"		# loaded services
+		listFilesMac | rev | ${G}cut -d$'/' -f1 | cut -d"." -f2- | rev 											# unloaded services
+	} | sort | uniq; 
 }
 
 listWin()
@@ -421,6 +411,82 @@ listRunningUserCommand() { RunPlatform listRunningUser; }
 listRunningUserMac() { launchctl list | grep -v "^-" | cut -d"	" -f3 | sort; }
 listRunningSystemCommand() { RunPlatform listRunningSystem; }
 listRunningSystemMac() { sudoc launchctl list | grep -v "^-" | cut -d"	" -f3 | sort ; }
+
+listUnloadedUsage() { ScriptUsageEcho "Usage: $(ScriptName) list unloaded [files]\nList unloaded services."; }
+listUnloadedArgStart() { unset files; }
+listUnloadedCommand() { RunPlatform listUnloaded; }
+listUnloadedFilesCommand() { files="files" RunPlatform listUnloaded; }
+
+listUnloadedMac()
+{
+	# loaded services 
+	local loaded="$({ launchctl list; sudoc launchctl list; } | cut -d"	" -f3 | ${G}grep -v "^Label$" | sort | uniq)"
+
+	# service files - format FILE:SERVICE
+	local both="$(eval "$(service list files | awk '{ print "printf " $0" ; printf : ; defaults read " $0 " Label" }')" 2>/dev/null)"
+	local services="$(echo "$both" | cut -d':' -f2 | sort | uniq)"
+
+	# services that are not loaded
+	services="$(comm -23 <(echo "$services") <(echo "$loaded"))"
+
+	# return services
+	[[ ! $files ]] && { echo "$services"; return; }
+
+	# return service files
+	echo "$both" | ${G}grep -f <(echo "$services") | sort
+}
+
+#
+# load commands
+#
+
+loadUsage() { EchoWrap "Usage: $(ScriptName) load SERVICE\nLoad the service."; }
+loadCommand() { RunPlatform load; }
+
+loadMac()
+{
+	{ [[ $macServiceLoaded || ! $macServiceDomain ]] || ! getMacServiceFile; } && return
+	printf "loading..."
+	$sudo launchctl bootstrap "$macServiceDomain" "$macServiceFile" || { echo "failed"; return 1; }
+	echo "done"
+}
+
+reloadUsage()
+{
+	EchoWrap "Usage: $(ScriptName) reload SERVICE
+Reload the service to pickup any configuration changes."
+}
+
+reloadCommand() { RunPlatform reload; }
+
+reloadLinux()
+{
+	[[ ! $useSystemd ]] && return
+	printf "reloading..."
+	sudoc systemctl reload "$service" || { echo "failed"; return 1; }
+	echo "done"
+}
+
+reloadMac()
+{
+	{ [[ ! $macServiceDomain ]] || ! getMacServiceFile; } && return
+	printf "reloading..."
+	[[ $macServiceLoaded ]] && { printf "unloading..."; $sudo launchctl bootout "$macServiceDomain" "$macServiceFile" &> /dev/null; }
+	printf "loading..."; $sudo launchctl bootstrap "$macServiceDomain" "$macServiceFile" &> /dev/null || { echo "failed"; return 1; }
+	echo "done"
+}
+
+unloadUsage() { EchoWrap "Usage: $(ScriptName) unload SERVICE\nUnload the service."; }
+unloadCommand() { RunPlatform unload; }
+
+unloadMac()
+{
+	{ [[ ! $macServiceLoaded || ! $macServiceDomain ]] || ! getMacServiceFile; } && return
+	printf "unloading..."
+	$sudo launchctl bootout "$macServiceDomain" "$macServiceFile" || { echo "failed"; return 1; }
+	echo "done"
+}
+
 
 #
 # log command
@@ -578,7 +644,10 @@ startWin() { local result; result="$($sc $hostUnc start "$service")" && return; 
 
 startMac()
 {
-	getMacServiceFile && { RunLog $sudo launchctl bootstrap "$macServiceDomain" "$macServiceFile"; return; }
+	loadMac || return
+
+	{ [[ ! $macServiceLoaded || ! $macServiceDomain ]] || ! getMacServiceFile; } && return
+	[[ ! $macService ]] && { ScriptErr "unable to start service '$service' in domain '$domain'"; return 1; }
 	RunLog $sudo launchctl start "$macService"
 }
 
@@ -615,8 +684,8 @@ stateMac()
 	[[ "$state" == "running" ]] && { echo "RUNNING"; return; }
 
 	# failed - lastExitCode != 0
-	local lastExitCode; lastExitCode="$(echo "$macServiceInfo" | grep "^	last exit code = " | ${G}cut -d"=" -f2)" || return
-	[[ "$lastExitCode" == "lastExitCode" ]] && { echo "FAILED"; return; }
+	local lastExitCode; lastExitCode="$(echo "$macServiceInfo" | ${G}grep "^	last exit code = " | ${G}cut -d"=" -f2)"
+	IsInteger "$lastExitCode" && [[ "$lastExitCode" != "0" ]] && { echo "FAILED"; return; }
 
 	# stopped
 	echo "STOPPED"
@@ -669,14 +738,13 @@ startTypeMac()
 	local file;
 
 	# disabled
-	if launchctl print-disabled "$macServiceDomain" | ${G}grep --quiet "\"$service\" => disabled"; then
+	if [[ "$macServiceDomain" != "unknown" ]] && launchctl print-disabled "$macServiceDomain" | ${G}grep --quiet "\"$service\" => disabled"; then
 		echo "DISABLED"
 		return
 	fi
 
 	# auto
-	getMacServiceFileContent || return
-	if echo "$macServiceFileContent" | qgrep '"RunAtLoad" => 1$'; then
+	if [[ "$(quiet="--quiet" macServiceFileRead "RunAtLoad")" == "1" ]]; then
 		echo "AUTO_START"
 		return
 	fi
@@ -700,8 +768,9 @@ stopWin() { local result="$($sc $hostUnc stop "$service")" && return; EchoErr "$
 
 stopMac()
 {
-	getMacServiceFile && { RunLog $sudo launchctl bootout $macServiceDomain "$macServiceFile"; return; }
-	RunLog $sudo launchctl stop "$macService"
+	getMacServiceFile && [[ $macServiceDomain ]] && { RunLog $sudo launchctl bootout $macServiceDomain "$macServiceFile" && return; }
+	[[ $macService ]] && { RunLog $sudo launchctl stop "$macService" && return; }
+	ScriptErr "unable to stop service '$service' in domain '$domain'"
 }
 
 #
@@ -794,10 +863,16 @@ infoAllCommand()
 	{
 		echo "service#domain#type#start type#state"
 
-		for service in "${services[@]}"; do
-			serviceCheck || return
-			echo "$service#$macServiceDomain#$(infoTypeMac)#$(startType)#$(stateCommand)"
-		done
+		PrintErr "Checkin $(ArraySize services) services..."
+		{
+			for service in "${services[@]}"; do
+				PrintErr "."
+				serviceCheck "$service" || return
+				echo "$service#$macServiceDomain#$(infoTypeMac)#$(startType)#$(stateCommand)"
+			done	
+		} | sort | uniq
+		EchoErrEnd "done"
+
 	} | column -c $(tput cols -T "$term") -t -s#
 }
 
@@ -835,6 +910,7 @@ infoPlatformMac()
 {
 	[[ $macServiceLoaded ]] && { echo "$macServiceInfo"; return; }
 	getMacServiceFileContent && echo "$macServiceFileContent"
+	return 0
 }
 
 infoTypeUsage() { EchoWrap "Usage: $(ScriptName) info type\nShow the platform specific type of the service."; RunPlatform infoTypeUsage; }
@@ -890,7 +966,7 @@ waitStart()
 waitEnd()
 {
 	! waitNeeded && return
-	[[ ! $wait ]] && { [[ ! $quiet ]] && echo done; return 0; }
+	[[ ! $wait ]] && { [[ ! $quiet ]] && echo "done"; return 0; }
 	RunFunction waitForState "$command"
 }
 
@@ -915,6 +991,96 @@ waitForState()
 
 	[[ ! $quiet ]] && echo "did not $present in $seconds seconds";
 	return 1
+}
+
+#
+# helper
+#
+
+checkSystemd() { IsSystemd && useSystemd="true"; return 0; }
+
+getMacServiceFileContent() 
+{
+	[[ $macServiceFileContent ]] && return
+	getMacServiceFile && macServiceFileContent="$(defaults read "$macServiceFile")" || macServiceFileContent="unknown"
+}
+
+# getMacServiceFile - set macServiceFile (i.e. the property list file) for the current service
+getMacServiceFile()
+{
+	[[ $macServiceFile ]] && return
+
+	# look in the cached macServiceInfo
+ 	if [[ $macServiceInfo ]]; then
+ 		macServiceFile="$(echo "$macServiceInfo" | ${G}grep "path =.*\.plist$" | cut -d"=" -f2 | RemoveSpaceTrim)"
+ 		[[ ! -f "$macServiceFile" ]] && { log2 "getMacServiceFile: service '$service' file '$macServiceFile' from the cached service information does not exist"; unset macServiceFile; }
+ 	fi
+
+ 	# look for service files on disk
+ 	if [[ ! $macServiceFile ]]; then 	
+ 		getMacServiceFiles || return
+		macServiceFile="$(echo "$macServiceFiles" | ${G}grep "/$service.plist$" | head -1)"
+		[[ ! $macServiceFile ]] && { log2 "getMacServiceFile: service '$service' does not have a service file on disk"; unset macServiceFile; }
+	fi
+
+	# validation, logging, and return
+	local result=0
+	[[ ! $macServiceFile ]] && { result=1 macServiceFile="unknown"; }
+	log2 "getMacServiceFile: macServiceFile='$macServiceFile'"
+	return $result
+}
+
+# getMacServiceFiles - set macServiceFiles to all of the known service files (i.e. property list files)
+getMacServiceFiles() 
+{
+	[[ $macServiceFiles ]] && return
+	macServiceFiles="$(listFilesMac)"
+}
+
+# macServiceFileGetServiceName - get the service name (the propert list Label) from the service file
+macServiceFileGetServiceName()
+{
+	quiet="--quiet" macServiceFileRead "Label" && return
+	GetFileNameWithoutExtension "$macServiceFile"
+}
+
+# macServiceFileRead KEY - read the key from the service file
+macServiceFileRead()
+{
+	# validate the file
+	local key="$1"; macServiceFileValidate || return
+
+	# validate and return the key
+	local value; value="$(defaults read "$macServiceFile" "$key" 2>&1)" && { echo "$value"; return; }
+	ScriptErrQuiet "service file '$(FileToDesc "$macServiceFile")' does not have key '$macServiceFile'"
+	(( verboseLevel > 1 )) && defaults read "$macServiceFile" "$key"
+	return 1
+}
+
+# macServiceFileValidate - validate the contents of the service file
+macServiceFileValidate()
+{
+	[[ $macServiceFileValidated ]] && return
+
+	# validate the file
+	{ getMacServiceFile && ScriptFileCheck "$macServiceFile"; } || return
+
+	# validate and get the contents of the properly list file
+	plutil -lint "$macServiceFile" >& /dev/null && { macServiceFileValidated="true"; return; }
+	ScriptErrQuiet "service file '$(FileToDesc "$macServiceFile")' is not a valid property list file"
+	(( verboseLevel > 1 )) && plutil -lint "$macServiceFile"
+	return 1
+}
+
+# getMacServiceInfo - gets information on a loaded server, sets macServiceDomain, macServiceInfo, and macServiceLoaded
+getMacServiceInfo()
+{
+	macServiceLoaded="true"
+	if macServiceInfo="$(launchctl print "system/$service" 2>&1)"; then macServiceDomain="system/"
+	elif macServiceInfo="$(launchctl print "gui/$UID/$service" 2>&1)"; then macServiceDomain="gui/$UID/"
+	elif macServiceInfo="$(launchctl print "user/$UID/$service" 2>&1)"; then macServiceDomain="user/$UID/"
+	else unset macServiceDomain macServiceInfo macServiceLoaded; return 1
+	fi
 }
 
 ScriptRun "$@"
