service: fixes

diff --git a/service b/service
--- a/service
+++ b/service
@@ -199,7 +199,7 @@ waitForStop()
 	for (( i=1; i<=seconds; ++i )); do
  		read -n 1 -t 1 -s && { echo "cancelled after $i seconds"; return 1; }
  		[[ "$(stateCommand)" == "STOPPED" ]] && { echo "stopped in $i seconds"; return 0; }
- 		[[ "$(stateCommand)" == "failed" ]] && { echo "failed in $i seconds"; return 0; }
+ 		[[ "$(stateCommand)" == "FAILED" ]] && { echo "failed in $i seconds"; return 0; }
 		printf "."
 	done
 
@@ -259,6 +259,7 @@ reloadCommand()
 	if [[ $useSystemd ]]; then
 		sudo systemctl daemon-reload || return
 		sudo systemctl reset-failed || return
+		sudo systemctl reload "$service" || return
 	else
 		restartCommand || return
 	fi
