service: fix issues with Linux systemd services

diff --git a/service b/service
--- a/service
+++ b/service
@@ -324,7 +324,7 @@ logWin() { EventViewer; }
 
 startCommand()
 {
-	[[ ! $force && "$(stateCommand)" != "STOPPED" ]] && return 
+	[[ ! $force && "$(stateCommand)" != @(FAILED|STOPPED) ]] && return 
 
 	checkWaiting; printf "Starting $service service$hostDescription...$waiting"
 	start$type || return
@@ -342,11 +342,16 @@ startWin() { local result; result="$($sc $hostUnc start "$service")" || { EchoEr
 
 stateCommand() { state$type; }
 
+
 stateLinux()
 {
-	if [[ $useSystemd ]]; then linuxService status "$service" | grep "inactive (.*)" > /dev/null && echo "STOPPED" || echo "RUNNING"
-	else linuxService status "$service" | grep "is running" > /dev/null && echo "RUNNING" || echo "STOPPED"
-	fi
+	[[ ! $useSystemd ]] && { linuxService status "$service" | grep "is running" > /dev/null && echo "RUNNING" || echo "STOPPED"; return; }
+
+	local status="$(linuxService status "$service" | head -3 | grep "^[ ]*Active:" | sed 's/^[ ]*//' | cut -d" " -f2-3)"
+
+	[[ "$status" = "active (running)" ]] && { echo "RUNNING"; return; }
+	[[ "$status" =~ ^failed.* ]] && { echo "FAILED"; return; }
+	echo "STOPPED"; return; # Active: inactive	
 }
 
 stateMac() { { sudoc launchctl list; launchctl list; } | cut -f3 | grep "^${label}$" >& /dev/null && echo "RUNNING" || echo "STOPPED"; }
