function.sh: add RunPlatformOs for performance

diff --git a/service b/service
--- a/service
+++ b/service
@@ -168,7 +168,7 @@ autoStartCommand() { autoCommand && startCommand; }
 demandStopCommand() { demandCommand && stopCommand; }
 disableStopCommand() { disableCommand && stopCommand; }
 
-dirCommand() { RunPlatform "dir" --host;  }
+dirCommand() { RunPlatformOs "dir" --host;  }
 dirMac() { ArrayShow macServices; }
 dirWin() { dirLinux; }
 
@@ -204,7 +204,7 @@ refreshUsage()
 Load new services and reset failed services."
 }
 
-refreshCommand() { RunPlatform refresh; }
+refreshCommand() { RunPlatformOs refresh; }
 
 refreshLinux()
 {
@@ -258,7 +258,7 @@ continueWin() { local result; result="$($sc $hostUnc continue "$service")" && re
 # delete command
 #
 
-deleteCommand() { stopCommand && disableCommand && RunPlatform "delete" --host; }
+deleteCommand() { stopCommand && disableCommand && RunPlatformOs "delete" --host; }
 deleteWin() {	$sc delete $hostUnc "$service"; }
 
 deleteLinux()
@@ -274,8 +274,8 @@ deleteLinux()
 #
 
 detailUsage() { EchoWrap "Usage: $(ScriptName) detail [brief]\nShow service detail, optionally in a concise format."; }
-detailCommand() { statusCommand && RunPlatform "detail" --host; }
-detailBriefCommand() { brief="brief" RunPlatform "detail" --host; }
+detailCommand() { statusCommand && RunPlatformOs "detail" --host; }
+detailBriefCommand() { brief="brief" RunPlatformOs "detail" --host; }
 
 detailLinux()
 {	
@@ -312,10 +312,10 @@ detailWin()
 # disable command
 #
 
-disableCommand() { RunPlatform "disable"; }
-disableWin() { $sc config $hostUnc "$service" start= disabled; }
+disableCommand() { RunPlatformOs "disable"; }
 disableLinux() { linuxService disable "$service"; }
 disableMac() { macServiceFileWrite "Disabled" "true"; }
+disableWin() { $sc config $hostUnc "$service" start= disabled; }
 
 #
 # install command
@@ -323,7 +323,7 @@ disableMac() { macServiceFileWrite "Disabled" "true"; }
 
 installUsage() {	ScriptUsageEcho "Usage: service install FILE\nInstall a service from a file."; }
 installArgs() { ScriptArgGet "file" -- "$@" && ScriptCheckFile "$file"; }
-installCommand() { RunPlatform "install"; }
+installCommand() { RunPlatformOs "install"; }
 
 installMac()
 {
@@ -378,11 +378,11 @@ listOpt()
 
 listCommand()
 {
-	[[ ! $file ]] && { RunPlatform "list"; return; }
+	[[ ! $file ]] && { RunPlatformOs "list"; return; }
 
 	local file="$TMP/services.txt";
 	printf "" > "$file" || return
-	RunPlatform "list" >> "$file" || return
+	RunPlatformOs "list" >> "$file" || return
 	TextEdit "$file"
 }
 
@@ -422,21 +422,21 @@ listWinDetail()
 }
 
 listFilesUsage() { ScriptUsageEcho "Usage: $(ScriptName) list files\nList files associated with all services."; }
-listFilesCommand() { RunPlatform listFiles; }
+listFilesCommand() { RunPlatformOs listFiles; }
 listFilesMac() { find "${macServices[@]}" -type f | sort | uniq; }
 
 listRunningUsage() { ScriptUsageEcho "Usage: $(ScriptName) list running [user|system]\nList running services."; }
-listRunningCommand() { RunPlatform listRunning; }
+listRunningCommand() { RunPlatformOs listRunning; }
 listRunningMac() { { launchctl list; sudoc launchctl list; } | grep -v "^-" | cut -d"	" -f3 | sort | uniq; }
-listRunningUserCommand() { RunPlatform listRunningUser; }
+listRunningUserCommand() { RunPlatformOs listRunningUser; }
 listRunningUserMac() { launchctl list | grep -v "^-" | cut -d"	" -f3 | sort; }
-listRunningSystemCommand() { RunPlatform listRunningSystem; }
+listRunningSystemCommand() { RunPlatformOs listRunningSystem; }
 listRunningSystemMac() { sudoc launchctl list | grep -v "^-" | cut -d"	" -f3 | sort ; }
 
 listUnloadedUsage() { ScriptUsageEcho "Usage: $(ScriptName) list unloaded [files]\nList unloaded services."; }
 listUnloadedArgStart() { unset files; }
-listUnloadedCommand() { RunPlatform listUnloaded; }
-listUnloadedFilesCommand() { files="files" RunPlatform listUnloaded; }
+listUnloadedCommand() { RunPlatformOs listUnloaded; }
+listUnloadedFilesCommand() { files="files" RunPlatformOs listUnloaded; }
 
 listUnloadedMac()
 {
@@ -476,7 +476,7 @@ loadValidateMac()
 }
 
 isLoadedUsage() { EchoWrap "Usage: $(ScriptName) IsLoaded SERVICE\nReturn LOADED or UNLOADED."; }
-isLoadedCommand() { RunPlatform isLoaded && printf "LOADED" || printf "UNLOADED"; }
+isLoadedCommand() { RunPlatformOs isLoaded && printf "LOADED" || printf "UNLOADED"; }
 isLoadedMac() {	[[ $macServiceLoaded ]]; }
 
 reloadUsage() { EchoWrap "Usage: $(ScriptName) reload SERVICE\nReload the service to pickup any configuration changes."; }
@@ -517,8 +517,7 @@ logOpt()
 	esac
 }
 
-logCommand() { RunPlatform "log" --host; }
-logWin() { start eventvwr.msc; }
+logCommand() { RunPlatformOs "log" --host; }
 
 logLinux()
 {
@@ -537,7 +536,10 @@ logMac()
 	logValidate "$file" && "$command" "$file"
 }
 
-logClearCommand() { RunPlatform "logClear"; }
+logWin() { start eventvwr.msc; }
+
+logClearCommand() { RunPlatformWin "logClear"; }
+
 logClearLinux() { sudo journalctl --rotate && sudoc journalctl --vacuum-time=1s; }
 
 logClearMac()
@@ -698,7 +700,7 @@ stateUsage()
 Show service state, one of RUNNING, STOPPED, FAILED, or PAUSED."
 }
 
-stateCommand() { RunPlatform "state" --host; }
+stateCommand() { RunPlatformWin "state" --host; }
 
 stateLinux()
 {
@@ -738,15 +740,15 @@ stateWin()
 #
 
 showUsage() { EchoWrap "Usage: $(ScriptName) show active|start\nShow service information."; }
-showCommand() { RunPlatform show; }
+showCommand() { RunPlatformWin show; }
 showLinux() { [[ ! $useSystemd ]] && return; systemctl show "$service"; }
 
 showActiveUsage() { EchoWrap "Usage: $(ScriptName) show active\nShow time service became active."; }
-showActiveCommand() { RunPlatform showActive; }
+showActiveCommand() { RunPlatformWin showActive; }
 showActiveLinux() { getProp "ActiveEnterTimestamp"; }
 
 showStartUsage() { EchoWrap "Usage: $(ScriptName) show start\nShow service start time."; }
-showStartCommand() { RunPlatform showStart; }
+showStartCommand() { RunPlatformWin showStart; }
 showStartLinux() { local result="$(getProp "ExecMainStartTimestamp")"; [[ $result ]] && { echo $result; return; }; showActiveLinux; }
 
 getProp() { showCommand | grep "^$1=" | cut -d= -f2; }
@@ -762,7 +764,7 @@ Show service start type, one of AUTO_START, DISABLED, or DEMAND_START."
 }
 
 starttypeCommand() { startType; }
-startType() { RunPlatform "startType" --host; }
+startType() { RunPlatformWin "startType" --host; }
 
 startTypeLinux()
 {
@@ -841,7 +843,7 @@ doCommandRun()
 	fi
 
 	# run command
-	RunPlatform "$command" --host
+	RunPlatformOs "$command" --host
 }
 
 macDaemons=( "/System/Library/LaunchDaemons" "/Library/LaunchDaemons" )
@@ -905,7 +907,7 @@ infoAllUsage() { EchoWrap "Usage: $(ScriptName) info all\nService information fo
 
 infoAllCommand()
 {
-	local service services; IFS=$'\n' ArrayMake services "$(RunPlatform "list")" || return
+	local service services; IFS=$'\n' ArrayMake services "$(RunPlatformOs "list")" || return
 
 	{
 		echo "service#domain#type#start type#state"
@@ -924,12 +926,11 @@ infoAllCommand()
 }
 
 infoDumpUsage() { EchoWrap "Usage: $(ScriptName) info dump\nDump all service information if possible."; }
-infoDumpCommand() { RunPlatform "infoDump"; }
+infoDumpCommand() { RunPlatformOs "infoDump"; }
 infoDumpMac() { launchctl dumpstate; }
 
 infoFileUsage() { EchoWrap "Usage: $(ScriptName) info file [contents]\nShow the file associated with the service, if applicable."; }
-infoFileCommand() { RunPlatform "infoFile"; }
-infoFileMac() { getMacServiceFile && echo "$macServiceFile"; }
+infoFileCommand() { RunPlatformOs "infoFile"; }
 
 infoFileLinux()
 {
@@ -942,16 +943,18 @@ infoFileLinux()
 	fi
 }
 
+infoFileMac() { getMacServiceFile && echo "$macServiceFile"; }
+
 infoFileContentsCommand()
 {
-	local file; file="$(RunPlatform "infoFile")"; [[ ! $file ]] && return; 
+	local file; file="$(RunPlatformOs "infoFile")"; [[ ! $file ]] && return; 
 	ScriptFileCheck "$file" || return
 	IsPlatform mac && { plutil -p "$file"; return; }
 	cat "$file"
 }
 
 infoPlatformUsage() { EchoWrap "Usage: $(ScriptName) info platform\nShow platform specific service information."; }
-infoPlatformCommand() { RunPlatform "infoPlatform"; }
+infoPlatformCommand() { RunPlatformOs "infoPlatform"; }
 
 infoPlatformMac()
 {
@@ -960,11 +963,10 @@ infoPlatformMac()
 	return 0
 }
 
-infoTypeUsage() { EchoWrap "Usage: $(ScriptName) info type\nShow the platform specific type of the service."; RunPlatform infoTypeUsage; }
-infoTypeCommand() { RunPlatform "infoType"; }
-infoTypeLinux() { [[ $useSystemd ]] && echo "systemd" || echo "init.d"; }
-
+infoTypeUsage() { EchoWrap "Usage: $(ScriptName) info type\nShow the platform specific type of the service."; RunPlatformOs infoTypeUsage; }
 infoTypeUsageMac() { echo "Valid service types: Extension LaunchAgent LaunchDaemon pid Submitted XPCService"; }
+infoTypeCommand() { RunPlatformOs "infoType"; }
+
 infoTypeMac()
 {
 	# get type from loaded service
@@ -978,6 +980,8 @@ infoTypeMac()
 
 	echo "unknown"
 }
+
+infoTypeLinux() { [[ $useSystemd ]] && echo "systemd" || echo "init.d"; }
 
 #
 # helper - checkState
@@ -1003,9 +1007,9 @@ checkStateStop() { [[ "$(stateCommand)" != "RUNNING" ]]; }
 runStatus()
 {
 	local command="$1" description="$2"
-	RunPlatform ${command}NotNeeded && return
+	RunPlatformOs ${command}NotNeeded && return
 	[[ ! $quiet ]] && printf "$description..."
-	RunPlatform "$command" || { echo "failed"; return 1; }
+	RunPlatformOs "$command" || { echo "failed"; return 1; }
 	[[ ! $quiet ]] && echo "done"
 	return 0
 }
