SshAgent: use writable filesystem for environmnet file

diff --git a/SshAgent b/SshAgent
--- a/SshAgent
+++ b/SshAgent
@@ -12,10 +12,12 @@ Control the SSH agent."
 init()
 {
 	! InPath "ssh-agent" && { EchoErr "The ssh-agent is not installed"; return 1; }
-	defaultCommand="check"
+
+	defaultCommand="check"	
+	passwordUsage="	-p, --password=PASSWORD 	password to unlock SSH keys"	
 	sshDir="$HOME/.ssh"
-	environmentFile="$sshDir/environment"
-	passwordUsage="	-p, --password=PASSWORD 	password to unlock SSH keys"
+
+	environmentFile="$(GetWritableDir "$sshDir")/environment" || return
 }
 
 #
@@ -165,14 +167,23 @@ cleanupAgent()
 	log1 "cleaning up the SSH agent"
 
 	# kill ssh-agent process	
-	ProcessKill ssh-agent &> /dev/null
+	if ProcessIdExists "$SSH_AGENT_PID"; then
+		log1 "cleanupAgent: killing the ssh-agent process for user '$USER' process '$SSH_AGENT_PID'"
+		kill -9 "$SSH_AGENT_PID" || { rm -fr "$dir" || ScriptErrQuiet "unable to kill the SSH agent process '$SSH_AGENT_PID'"; }
+	fi
 
-	# clenup SSH socket directory - the socket file must be in a directory that begins with ssh- to prevent accidental deletion
+	# cleanup SSH socket directory - the socket file must be in a directory that begins with ssh- to prevent accidental deletion
 	local dir="$(GetFilePath "$SSH_AUTH_SOCK")"
-	[[ "$(GetFileName "$dir")" =~ ^ssh- && -d "$dir" ]] && rm -fr "$dir"
+	if [[ "$(GetFileName "$dir")" =~ ^ssh- && -d "$dir" ]]; then
+		log1 "cleanupAgent: removing the SSH agent socket directory '$dir'"
+	 	rm -fr "$dir" || ScriptErrQuiet "unable to remove the SSH agent socket directory '$dir'"
+	 fi
 
 	# cleanup environment file
-	[[ -f "$environmentFile" ]] && rm -f "$environmentFile"
+	if [[ -f "$environmentFile" ]]; then
+		log1 "cleanupAgent: removing the SSH agent environment file '$environmentFile'"
+		rm -f "$environmentFile" || ScriptErrQuiet "unable to remove the SSH agent environment file '$environmentFile'"
+	fi
 
 	return 0
 }
