SshHelper: enhance logging
Add logging if there is an SSH error that is suppressed.

diff --git a/SshHelper b/SshHelper
--- a/SshHelper
+++ b/SshHelper
@@ -111,10 +111,10 @@ connectCommand()
 	fi
 
 	# arguments
-	args=()
+	local args=() quietArg
 	[[ $user ]] && args+=("$user@$host") || args+="$host"
 	[[ $port ]] && args+=(-p "$port")
-	[[ ! $mosh ]] && args+=(-q) # supresses warnings
+	[[ ! $mosh && ! $verbose ]] && quietArg="-q" # supresses warnings first time through
 
 	if [[ $commandsArg ]]; then
 		args+=(-- bash $interactive -c "\"$commandsArg\"" "${otherArgs[@]}")
@@ -141,15 +141,24 @@ connectCommand()
 		command="ssh -X $pseudoTerminal"
 	fi
 
-	[[ $verbose ]] && { EchoErr "$command $@"; }
+	[[ $verbose ]] && { EchoErr "command=$command $@"; }
 	[[ $test ]] && return
 
+	# connect
+	local result
 	if [[ "$password" ]]; then
-		command="spawn -noecho $command $@; expect \"password:\"; send \"DpqZ9qa3p6Z19G92\r\"; interact"
+		command="spawn -noecho $command $verbose $quietArg "$@"; expect \"password:\"; send \"DpqZ9qa3p6Z19G92\r\"; interact"
 		expect -c "$command"
 	else
-		$command "$@"
+		$command $verbose $quietArg "$@"
 	fi
+	result="$?"
+	
+	# display SSH error (exit status 255) if supressed with -q
+	(( result == 255 )) && [[ $quietArg ]] && ScriptErr "SSH error occurred\nTry again with 'SshHelper --verbose' for more detail"
+
+	return "$result"
+
 }
 
 #
