support multiple platforms

diff --git a/SyncDir b/SyncDir
--- a/SyncDir
+++ b/SyncDir
@@ -71,8 +71,9 @@ SyncDirCommand()
 	# src or dest directory is excluded
 	{ IsInArray -aw "${src##*/}" x || IsInArray -aw "${dest##*/}" x; } && return
 
-	IsUncPath "$src" && { src="$(unc mount "$src")" || return; }
-	IsUncPath "$dest" && { dest="$(unc mount "$dest")" || return; }
+	local srcOrig="$src" destOrig="$dest"
+	IsUncPath "$src" && { src="$(unc mount "$src")" || { printf "\nUnable to mount $srcOrig\n"; return 1; }; }
+	IsUncPath "$dest" && { dest="$(unc mount "$dest")" || { printf "\nUnable to mount $destOrig\n"; return 1; }; }
 
 	[[ $exist && (! -d "$src" && ! -d "$dest") ]] && return 0
 
@@ -298,9 +299,6 @@ SyncMissingDir()
 CopyMissingDir()
 {
 	local src="$1" dest="$2" srcDesc="$3" destDesc="$4"
-
-	printf "copy $srcDesc\n"
-	mkdir -p "$dest" || return
 	CopyDir "$src" "$dest" $recursive --retry -xf "${x[@]}" -xd "${x[@]}"
 }
 
@@ -473,6 +471,7 @@ ReplaceFile()
 
 	printf "replace $desc..."
 	${G}cp --preserve=timestamps "$src" "$dest" || return	
+	touch "$dest" --reference "$src" || return
 }
 
 # SyncFileTimes() - touch not functional over WebDAV
