SyncDir: do not set file times for WSL 1

diff --git a/SyncDir b/SyncDir
--- a/SyncDir
+++ b/SyncDir
@@ -439,9 +439,9 @@ setLastSync()
 # syncTime FILE REFERENCE_FILE - make the last modification time of file the same as the reference file
 setFileTime()
 {
-	local file="$1" reference="$2" sudo; IsPlatform wsl1 && sudo="sudoc"
+	local file="$1" reference="$2" sudo; IsPlatform wsl1 && return # WSL 1 does not support setting file time
 	$sudo ${G}touch "$file" --reference "$reference" && return
-	setFileTimes "$file" "$reference"
+	setFileTimes "$file" "$reference" # if the touch fails try and sync both files to current time
 }
 
 # syncFileTimes FILE1 FILE1_AGE FILE2 FILE2_AGE - synronize file times to the newer file
@@ -465,10 +465,10 @@ syncFileTimes()
 # setFileTimes FILES - set all file times to the current time
 setFileTimes()
 {
-	local now="$(GetSeconds)"
+	local now="$(GetSeconds)"; IsPlatform wsl1 && return # WSL 1 does not support setting file time
 
 	for file in "$@"; do
-		${G}touch "$file" -d "@$now"
+		${G}touch "$file" -d "@$now" || return
 	done
 }
 
