SyndDir: fix compare error in macOS
In macOS, after editing files, identical files are reported as different.

diff --git a/SyncDir b/SyncDir
--- a/SyncDir
+++ b/SyncDir
@@ -246,8 +246,9 @@ syncFile()
 
 		case $(( $?+1 )) in
 		  1)  # edit
-				merge --wait "$olderPath" "$newerPath"
-		    if (( $? != 1 )); then
+				[[ $verbose ]] && printf "olderPath=$olderPath newerPath=$newerPath"
+				merge --wait "$olderPath" "$newerPath" #  merge return values vary, Beyond Compare return 1 for "Binary Same" on all platforms except macOS
+		    if ! cmp --quiet "$olderPath" "$newerPath"; then
 		    	echo "$srcFile is still diferent"
 	    		continue
 	  		fi
