wiggin backup job updates

diff --git a/TestJob b/TestJob
--- a/TestJob
+++ b/TestJob
@@ -1,33 +1,106 @@
 #!/usr/bin/env bash
 . function.sh || exit
 
-header "Test Job"
+# Assumes:
+# 1) the SSH agent is configured (SshAgentStart --quiet)
+# 2) Hashi tools are configured (ScriptEval hashi config environment)
+# This can be accomplished by tunning the script with with 'RunScript --ssh-agent --hashi'
 
-hilight "Configuration..."
-echo "HOSTNAME=$HOSTNAME"
-echo "USER=$USER"
-echo "PATH=$PATH"
-echo
+run()
+{
+	local destHost="pi1" countTo="4" result
 
-hilight "Configuring vault..."
-eval "$(hashi config environment)" || exit
-echo
+	header "Test Job"
+	configuration && testCredential && testScp && testSsh && testBackupLocal && testBackupRemote && count
+	result="$?"
+	
+	(( $result == 0 )) && hilight "success" || echo "${RED}fail${reset}"
+	return "$result"
+}
 
-hilight "Testing credentials..."
-echo "credential type=$(credential type)"
-echo "test/key1=$(credential get test key1)"
-echo
+configuration()
+{
+	hilight "Configuration..."
+	echo "HOSTNAME=$HOSTNAME"
+	echo "USER=$USER"
+	echo "PATH=$PATH"
+	echo
 
-hilight "SSH Agent status..."
-SshAgent status || exit
+	hilight "SSH Agent status..."
+	SshAgent status || return
+	echo
 
-hilight "Testing scp..."
-file="/tmp/now.txt"
-GetTimeStamp > "$file" || exit
-scp -P 608 "$file" "admin@nas3:$file" || exit
+	hilight "Hashi status..."
+	hashi status || return
+	echo
+}
 
-hilight "Counting up..."
-for (( i = 0; i < 5; i++ )); do
-	echo "$i"
-	sleep 1
-done
+count()
+{
+	hilight "Counting up to $countTo..."
+	for (( i = 0; i <= $countTo; i++ )); do
+		echo "$i"
+		sleep 1
+	done
+	echo
+}
+
+testCredential()
+{
+	hilight "Testing credentials..."
+	echo "credential type=$(credential type)" || return
+	echo "test/key1=$(credential get test key1)"
+	echo
+}
+
+testScp()
+{
+	hilight "Testing scp to $destHost..."
+	srcFile="/tmp/now_src.txt"
+	destFile="/tmp/now_dest.txt"
+	GetTimeStamp > "$srcFile" || return
+	scp "$srcFile" "$destHost:$destFile" || return
+	echo
+}
+
+testSsh()
+{
+	hilight "Testing ssh to $destHost..."
+	ssh "$destHost" cat "$destFile" || return
+	echo
+}
+
+testBackupLocal()
+{
+	hilight "Testing local backup..."
+	local archive="TestJobLocal"
+	BorgHelper backup "/tmp" --archive="$archive" || return
+	backupFinish "$archive" || return
+}
+
+testBackupRemote()
+{
+	hilight "Testing remote backup..."
+	local archive="TestJobRemote"
+	SshHelper "$destHost" --interactive --pseudo-terminal -- BorgHelper backup "/tmp" --archive "$archive" || return
+	backupFinish "$archive" --repository "$destHost" || return
+}
+
+backupFinish()
+{
+	local archive="$1"; shift; ScriptEval BorgHelper environment "$@" || return
+	echo
+
+	# prune
+	echo "Pruning $archive..."
+	borg prune --keep-last 2 --prefix "$archive-" || return
+	echo
+
+	# status
+	echo "Backup status..."
+	echo "BORG_REPO=$BORG_REPO"
+	borg list --prefix "$archive-" || return
+	echo
+}
+
+run "$@"
diff --git a/wiggin b/wiggin
--- a/wiggin
+++ b/wiggin
@@ -90,9 +90,24 @@ backupLastpassCommand()
 
 backupProxymanagerCommand()
 { 
-	local server="ProxyManager.butare.net"
-	! unc IsAvailable "$server" && { ScriptErr "'$server' is not available"; return 1; }
-	AppBackup "$(RemoveDnsSuffix "$server").ProxyManager" "//$server/admin$SRV/nginx-proxy-manager"
+	local archive="ProxyManager" server="ProxyManager.butare.net"
+
+	! SshIsAvailable "$server" && { ScriptErr "'$server' is not available"; return 1; }
+	
+	SshHelper "$(ConfigGet "user")@$server" --interactive --pseudo-terminal "${globalArgs[@]}" -- BorgHelper backup "/srv/nginx-proxy-manager" --archive "$archive" "${globalArgs[@]}" || return
+	echo
+
+	# prune
+	hilight "Pruning $archive..."
+	ScriptEval BorgHelper environment --repository "$(GetHostname "$server")" "${globalArgs[@]}" || return
+	borg prune --keep-last 2 --prefix "$archive-" || return
+	echo
+
+	# status
+	hilight "$archive backups..."
+	borg list --prefix "$archive-" || return
+	echo
+
 }
 
 backupQnapCommand()
@@ -122,9 +137,12 @@ backupWebCommand()
 
 	# Debian Apache Servers
 	for server in "${servers[@]}"; do
-		! unc IsAvailable "$server" && { ScriptErr "'$server' is not available"; status=1; continue; }
-		AppBackup "$(RemoveDnsSuffix "$server").web" "//$server/admin/var/www/html" -- -x "Web/netboot.xyz/*" || return	
-		AppBackup "$(RemoveDnsSuffix "$server").web.config" "//$server/admin/etc/apache2" || return	
+
+		! SshIsAvailable "$server" && { ScriptErr "'$server' is not available"; status=1; continue; }
+
+		SshHelper "$(ConfigGet "user")@$server" --interactive --pseudo-terminal "${globalArgs[@]}" -- \
+			BorgHelper backup "/var/www/html" "/etc/apache2" --archive "web" "${globalArgs[@]}" || return
+
 	done
 
 	# nas3 - QNAP Apache Server
@@ -132,6 +150,7 @@ backupWebCommand()
 		AppBackup "nas3.web" "//nas3/root/share/CACHEDEV1_DATA/Web" -- -x "Web/@Recycle/*" -x "Web/netboot.xyz/*" -x "Web/ProxyServer/*" || return
 	fi
 
+	(( $status != 0 )) && ScriptErr "backup of one or more web servers failed"
 	return $status
 }
 
@@ -157,8 +176,15 @@ backupJobCommand()
 	hilight "SSH Agent status..."
 	SshAgent status || exit
 
-	#backupDomains && backupDomotz && backupHomebridge && backupProxyManager && backupUniFi && backupWeb
-	backupDomains && backupDomotz && backupHomebridge && backupProxyManager && backupUniFi
+	# backup 
+	local result
+	backupDomains && backupDomotz && backupHomebridge && backupProxyManager && backupUniFi && backupWeb
+	result="$?"
+	echo
+
+	# result
+	(( $result == 0 )) && hilight "success" || echo "${RED}fail${reset}"
+	return "$result"
 }
 
 backupDo()
@@ -747,8 +773,8 @@ deviceStatus()
 # Helper
 #
 
-mountVol() { VeraCrypt mount "$@" p; }
-unmountVol() { VeraCrypt unmount p; }
+mountVol() { VeraCrypt mount "$@" p "${globalArgs[@]}"; }
+unmountVol() { VeraCrypt unmount p "${globalArgs[@]}"; }
 
 getHosts() 
 {
