wiggin cert: updates

diff --git a/wiggin b/wiggin
--- a/wiggin
+++ b/wiggin
@@ -211,7 +211,7 @@ Usage: $(ScriptName) cert all|renew|copy|hubitat|lb|nas|printer|cleanup\nCertifi
 certArgStart() { unset -v noCleanup; }
 certCommand() { certAllCommand; }
 certAllUsage() { ScriptUsageEcho "Usage: $(ScriptName) renew cert all\nPerform all certificate commands."; }
-certAllCommand() { certRenewCommand && certCopyCommand && certLbCommand && certHubitatCommand && certNasCommand && certPrinterCommand; }
+certAllCommand() { certRenewCommand && certCopyCommand && certLbCommand && certNasCommand && certPrinterCommand; }
 certCleanupCommand() { :; }
 
 certOpt()
@@ -230,8 +230,8 @@ certArgEnd()
 
 	# Let's Encrypt
 	letsEncryptDir="/etc/letsencrypt"
-	[[ ! -d "$letsEncryptDir" ]] && { ScriptErr "Let's Encrypt is not installed.  Use 'inst install certbot' to install and configure it."; return 1; }
 	certDir="$letsEncryptDir/live"
+	{ ! InPath certbot || [[ ! -d "$letsEncryptDir" ]]; } && { inst certbot || return; }
 
 	# mount existing certificates
 	encryptedDir="$(CloudConf && encrypt mount "$CLOUD/data/app/CryFS/personal")/data/letsencrypt" || return
@@ -243,14 +243,16 @@ certArgEnd()
 
 certCleanup() { [[ $noCleanup ]] && return; log1 "cleanup"; certStageCleanup && encrypt unmount "personal"; }
 
+# certStage - copy Let's Encrypt certificates from the encryped directory to a temp directory
 certStage()
 {
 	local from="$encryptedDir/$domain/." to="$certDirTmp"
 	[[ ! -d "$from" ]] && return # certificate does not exist yet
 	log1 "copy certificate files from '$from' to '$to'"
-	cp -rp "$from" "$to"
+	cp -rp "$from" "$to" || return
 }
 
+# certStageCleanup - cleanup the certificate temp directory
 certStageCleanup()
 {
 	[[ $noCleanup || ! -d "$certDirTmp" ]] && return
@@ -261,8 +263,13 @@ certStageCleanup()
 certRenewCommand()
 {
 	hilight "Renewing certificate..."
-	CertGetDates "$certDir/$domain/cert.pem" || return
+
+	# validate
+	local file="$certDir/$domain/cert.pem"
+	[[ -f "$file" ]] && { CertGetDates "$certDir/$domain/cert.pem" || return; }
 	! ask 'Do you want to renew the certificate' && return
+
+	# renew
 	sudoc certbot certonly -d '*.butare.net' --dns-cloudflare --dns-cloudflare-credentials "$letsEncryptDir/credentials/cloudflare.ini" || return
 }
 
@@ -293,10 +300,13 @@ certCopyCommand()
 	cp -r "$certDirTmp/." "$encryptedDir/$domain" || return
 }
 
-certHubitatCommand() { cd "$certDirTmp" && certHubitat 1 && certHubitat 2; }
+certHubitatCommand() { ( cd "$certDirTmp" && certHubitat 1 && certHubitat 2; ); }
 
 certHubitat()
 {
+	echo "Hubitat does not currently support eleptical curve certificates"	
+	return
+
 	local n="$1"; hilight "Updating the Hubitat $n certificates..."
 	open "https://hubitat${n}.butare.net/hub/advanced/certificate" || return
 
@@ -315,6 +325,7 @@ certLbCommand()
 
 	# update certificates used by the load balancer
 	local lbDir="$UDATA/sync/etc/letsencrypt/live/$domain"
+	! sudoc ls "$live" >& /dev/null && { wiggin sync lb-cert || return; }
 	sudoc cp -r "$certDirTmp/." "$lbDir" || return
 	sudoc chown -R root "$lbDir" || return
 
