wiggin network update dns: add IPv6 forward lookup

diff --git a/wiggin b/wiggin
--- a/wiggin
+++ b/wiggin
@@ -1187,7 +1187,19 @@ networkUpdateDns()
 	cp "$config/named.conf."* "$dir" || return
 	cp "$config/$baseDomain" "$dir" || return
 	cp "$config/forward.txt" "$dir/$domain" || return
+	
+	# A records - IPv4
 	configFileToCommaDelimited "$dhcpReservations4" | awk -F "," '{ print $1 ".'$domain'.	A	" $3 }' | column -t	>> "$dir/$domain" || return
+
+	# AAAA records - IPv6
+	local line lines items
+	IFS=$'\n' ArrayMake lines "$(configFileToCommaDelimited "$dhcpReservations4" | awk -F "," '{ print $1 "  AAAA    " $3 }' | column -t | awk -F "," '{ print $1 "  AAAA    " $3 }' | column -t)"
+	{ 
+		for line in "${lines[@]}"; do
+			StringToArray "$line" " " items
+			echo "${items[0]}    ${items[1]}       NETWORK_PREFIX$(Ipv6Token "${items[2]}")"
+		done
+	} | column -t >> "$dir/$domain" || return
 
 	# names
 	${G}sed -i "s/NETWORK_PREFIX/$networkPrefix6/g" "$dir/$domain" || return
@@ -1368,20 +1380,20 @@ networkValidateDns()
 # networkValidateDns4 HOST - validate a DNS server using IPv4
 networkValidateDns4()
 {
-	local host="$1"; networkValidateDnsCommon || return
+	local host="$1" name="router.$(GetDnsDomain)"; networkValidateDnsCommon || return
 	
 	# forward lookup 
-	nslookup "router.$(GetDnsDomain)" "$host" >& /dev/null || { log2 "$host IPv4 forward lookup of router.$(GetDnsDomain) failed"; return 1; }
+	nslookup "$name" "$host" >& /dev/null || { log2 "$host IPv4 forward lookup of router.$(GetDnsDomain) failed"; return 1; }
 
 	# reverse lookup
-	local ip; ip="$(DnsResolve "router")" || return
+	local ip; ip="$(DnsResolve "$name")" || return
 	nslookup "$ip" "$host" >& /dev/null || { log2 "$host reverse lookup of 10.10.100.1 failed"; return 1; }
 }
 
 # networkValidateDns6 HOST - validate a DNS server using IPv6
 networkValidateDns6()
 {
-	local host="$1"; networkValidateDnsCommon || return
+	local host="$1" name="router.$(GetDnsDomain)"; networkValidateDnsCommon || return
 
 	# forward lookup
 	# dig -6 -t AAAA +short "router.$(GetDnsDomain)" @host >& /dev/null || { log2 "$host IPv6 forward lookup of router.$(GetDnsDomain) failed"; return 1; }
@@ -1393,6 +1405,8 @@ networkValidateDns6()
 # networkValidateDnsCommon - common validations for DNS servers 
 networkValidateDnsCommon()
 {
+	log2 "validating DNS server on '$host' by checking '$name' resolution (ipv=$ipv)"
+
 	# check if the host is available
 	HostAvailable "$host" || return
 
