wiggin maintenance: fixes

diff --git a/wiggin b/wiggin
--- a/wiggin
+++ b/wiggin
@@ -527,13 +527,15 @@ maintenanceAllCommand() { maintenanceApCommand; }
 maintenanceApCommand()
 {
 	local firstAp="LivingRoomAp.hagerman.butare.net"
+	#local firstAp="FrontYardAp.hagerman.butare.net"
 
-	RunLog power reboot --wait-ssh "$firstAp" || return
+	RunLog power reboot --wait "$firstAp" "${globalArgs[@]}" || return
+	SleepStatus 30 || return # --wait-ssh fails running under Nomad
 
 	local ap aps=(); IFS=$'\n' ArrayMakeC aps UniFiController ls --access-point || return
 	for ap in "${aps[@]}"; do
 		[[ "${ap,,}" == "${firstAp,,}" ]] && continue
-		RunLog power reboot "$ap" || return
+		RunLog power reboot "$ap" "${globalArgs[@]}" || return
 	done
 }
 
