HostUpdate zsh: fiz issue with pause command after calling zsh

diff --git a/ZshHelper b/ZshHelper
--- a/ZshHelper
+++ b/ZshHelper
@@ -13,7 +13,8 @@ init()
 usage() 
 {	
 	echot "\
-usage: ZshHelper profile dir|SaveDir|save|restore [<profile name>|default](latest)
+usage: ZshHelper update
+	profile dir|SaveDir|save|restore [<profile name>|default](latest)
 	-np, --no-prompt	   	suppress interactive prompts"
 	exit $1
 }
@@ -48,6 +49,27 @@ profileCommand()
 	fi
 
 	profile $noPrompt --app "zsh" --method "$HOME/.oh-my-zsh" --files "* .git* .editorconfig" "$@" || usage 1
+}
+
+updateCommand()
+{
+	local t="$ohMyZsh/custom/themes" p="$ohMyZsh/custom/plugins"
+	local plugins=( "$t/powerlevel10k" "$p/zsh-syntax-highlighting" )
+
+	# update zsh
+	ZshUpdate || return # pause fails if run update from bash using zsh -i -c
+
+	# update plugings using git pull
+	pushd "$HOME/.oh-my-zsh" >& /dev/null
+
+	for plugin in "${plugins[@]}"; do
+		[[ ! -d "$plugin/.git" ]]	&& continue
+		printf "${BLUE}%s${RESET}\n" "Updating $(GetFileName "$plugin")..."
+		cd "$plugin" || return
+		git pull || return
+	done
+
+	popd >& /dev/null
 }
 
 run "$@"
